('BTP_EXPERT: Le chantier en direct (photos/videos du chantier en cours) est le contenu #1 pour les entreprises de construction.', 'Chantier en direct photos/videos = contenu #1 BTP', NULL, 'insight', 0.82, 'industry_expert', 'system'),
('BTP_EXPERT: Le devis en ligne (formulaire + estimation automatique) capture 3x plus de leads que le simple numero de telephone.', 'Devis en ligne BTP = 3x leads vs telephone', NULL, 'insight', 0.82, 'industry_expert', 'system'),
('BTP_EXPERT: Le Google My Business artisan: photos avant/apres chantier + zone intervention + avis clients = pack local garanti.', 'GMB artisan: avant/apres + zone + avis = pack local', 'gmaps', 'best_practice', 0.85, 'industry_expert', 'system'),
('BTP_EXPERT: Le referral program BTP: 100€ de reduction pour chaque client recommande. Le bouche-a-oreille genere 70% des clients artisans.', 'Referral BTP: 100€/reco. Bouche-a-oreille = 70% clients artisans', NULL, 'best_practice', 0.82, 'industry_expert', 'system'),
('BTP_EXPERT: Les certifications (RGE, Qualibat) augmentent la confiance de 40% et permettent aux clients de beneficier d aides fiscales.', 'Certifications BTP RGE/Qualibat = +40% confiance + aides fiscales', NULL, 'insight', 0.82, 'industry_expert', 'system'),
-- EDUCATION / FORMATION (10)
('EDUCATION_EXPERT: Le micro-learning (lecons 5-10 min) a un taux de completion de 80% vs 20% pour les cours de 60+ min.', 'Micro-learning 5-10 min = 80% completion vs 20% cours 60+ min', NULL, 'insight', 0.85, 'industry_expert', 'system'),
('EDUCATION_EXPERT: Le gamification e-learning: quiz inter-modules, points, classement = 50% plus de completion.', 'Gamification e-learning quiz+points+classement = +50% completion', NULL, 'insight', 0.82, 'industry_expert', 'system'),
('EDUCATION_EXPERT: Le cohort-based course (dates fixes + communaute) a 10x plus de completion que le self-paced.', 'Cohort course dates fixes + communaute = 10x completion vs self-paced', NULL, 'insight', 0.85, 'industry_expert', 'system'),
('EDUCATION_EXPERT: Le certificat de completion augmente la valeur percue de 40% et le taux de completion de 35%.', 'Certificat = +40% valeur percue +35% completion', NULL, 'insight', 0.82, 'industry_expert', 'system'),
('EDUCATION_EXPERT: Le pricing e-learning optimal: 97-297€ cours standard, 497-1997€ programme premium, 2K-10K€ accompagnement + communaute.', 'Pricing e-learning: 97-297 standard, 497-1997 premium, 2K-10K accompagnement', NULL, 'insight', 0.78, 'industry_expert', 'system'),
('EDUCATION_EXPERT: Le webinaire funnel pour vendre des formations: valeur gratuite 45 min + pitch 15 min. Taux de conversion 5-15%.', 'Webinaire formation: 45 min valeur + 15 min pitch = 5-15% conversion', NULL, 'insight', 0.82, 'industry_expert', 'system'),
('EDUCATION_EXPERT: Le CPF (Compte Personnel de Formation) en France finance jusqu a 5000€ de formation. Etre certifie Qualiopi = acces au CPF.', 'CPF 5000€ max. Qualiopi = acces CPF', NULL, 'insight', 0.82, 'industry_expert', 'system'),
('EDUCATION_EXPERT: Le learning management system (LMS): Teachable, Podia, ou Thinkific pour heberger et vendre des cours en ligne.', 'LMS: Teachable + Podia + Thinkific pour heberger/vendre cours', NULL, 'insight', 0.78, 'industry_expert', 'system'),
('EDUCATION_EXPERT: Le email nurturing pre-lancement formation: J-14 teaser, J-7 valeur gratuite, J-3 temoignages, J-1 deadline, J0 lancement.', 'Pre-lancement formation: J-14 teaser, J-7 valeur, J-3 temoignages, J-1 deadline, J0', 'email', 'best_practice', 0.82, 'industry_expert', 'system'),
('EDUCATION_EXPERT: Le alumni network (reseau d anciens eleves) est le canal de referral #1 pour les formations. 30% des inscriptions viennent d anciens.', 'Alumni network = 30% inscriptions formation. Referral #1', NULL, 'insight', 0.80, 'industry_expert', 'system')
ON CONFLICT DO NOTHING;
