import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { getIp, hashIp, anonTag } from '@/lib/anon-ip';

export const runtime = 'nodejs';

/**
 * POST /api/anon-gen/save
 *
 * Persists a visual generated by a LOGGED-OUT visitor so it never disappears
 * (founder 03/07). Stored in saved_images with user_id=null + a tag
 * `anon:<ipHash>` so it can be claimed into the user's library when they
 * create an account (see /api/anon-gen/claim).
 *
 * Body: { image_url, thumbnail_url?, business_type?, business_description?,
 *         visual_style?, tone?, text_overlay?, generation_prompt?, ai_model?, title? }
 * Returns { ok, id }.
 */
export async function POST(req: NextRequest) {
  const body = await req.json().catch(() => ({}));
  const imageUrl = String(body?.image_url || '').trim();
  if (!imageUrl || !/^https?:\/\//.test(imageUrl)) {
    return NextResponse.json({ ok: false, error: 'image_url required' }, { status: 400 });
  }

  const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!);
  const ipHash = hashIp(getIp(req));

  try {
    const { data, error } = await supabase.from('saved_images').insert({
      user_id: null,
      image_url: imageUrl,
      thumbnail_url: body?.thumbnail_url || imageUrl,
      business_type: body?.business_type || null,
      business_description: body?.business_description || null,
      visual_style: body?.visual_style || null,
      tone: body?.tone || null,
      text_overlay: body?.text_overlay || null,
      generation_prompt: body?.generation_prompt || null,
      ai_model: body?.ai_model || 'anon-free',
      title: body?.title || 'Ton visuel gratuit',
      tags: [anonTag(ipHash)],
    }).select('id').maybeSingle();

    if (error) return NextResponse.json({ ok: false, error: error.message }, { status: 500 });
    return NextResponse.json({ ok: true, id: data?.id });
  } catch (e: any) {
    return NextResponse.json({ ok: false, error: e?.message || 'save failed' }, { status: 500 });
  }
}
