-- ═══ ELITE CONTENT AGENT — 100 learnings niveau expert 50 ans ═══
-- Agent: content (stratégie contenu, publications, calendrier)
-- Expertise: content marketing, storytelling, viralité, algorithmes sociaux

INSERT INTO agent_knowledge (content, summary, agent, category, confidence, source, created_by) VALUES
('CONTENT_ELITE: Le hook ideal suit le schema DISRUPT: Dissonance cognitive (ce que tu crois est faux) → Intrigue → Specificite → Tension → Urgence → Resolution → Proof.', 'DISRUPT hook framework: dissonance → intrigue → specificite → tension → urgence → resolution → proof', 'content', 'best_practice', 0.92, 'elite_content', 'system'),
('CONTENT_ELITE: Le content-market fit existe: le format + la plateforme + le message doivent etre alignes. Un bon message dans le mauvais format echoue.', 'Content-market fit: format + plateforme + message alignes', 'content', 'insight', 0.90, 'elite_content', 'system'),
('CONTENT_ELITE: Le biais de recence algorithmique: publier quand l audience est en ligne ET quand la competition est faible (creneaux sous-exploites).', 'Biais recence algo: publier quand audience active + competition faible', 'content', 'best_practice', 0.88, 'elite_content', 'system'),
('CONTENT_ELITE: La repartition 3-1-1: 3 posts de valeur pure, 1 post d engagement (question, poll), 1 post promotionnel. Ce ratio maximise la confiance.', 'Ratio 3-1-1: 3 valeur, 1 engagement, 1 promo = max confiance', 'content', 'best_practice', 0.90, 'elite_content', 'system'),
('CONTENT_ELITE: Le open loop dans les carrousels (teaser de la conclusion sur la slide 1) force le swipe et multiplie les completions par 3.', 'Open loop carrousel: teaser conclusion slide 1 = 3x completions', 'content', 'best_practice', 0.88, 'elite_content', 'system'),
('CONTENT_ELITE: Le pattern interrupt algorithmique: changer de format tous les 3-4 posts (texte → video → carrousel → image) empeche l algo de reduire la portee.', 'Varier format 3-4 posts = empecher reduction portee algo', 'content', 'best_practice', 0.85, 'elite_content', 'system'),
('CONTENT_ELITE: Le content velocity: la vitesse de publication dans les 30 premieres minutes determine 80% de la portee finale. Mobiliser l engagement immediatement.', 'Content velocity 30 min = 80% portee finale. Engagement immediat', 'content', 'insight', 0.88, 'elite_content', 'system'),
('CONTENT_ELITE: Le narrative arc en 5 temps pour les posts longs: situation → complication → tension → resolution → morale. Chaque etape retient le lecteur.', 'Narrative arc 5 temps: situation → complication → tension → resolution → morale', 'content', 'best_practice', 0.88, 'elite_content', 'system'),
('CONTENT_ELITE: Les emotions primaires dans l ordre de partageabilite: 1) surprise, 2) admiration, 3) colere, 4) peur, 5) joie. La surprise est le trigger #1.', 'Emotions partage: surprise > admiration > colere > peur > joie', 'content', 'insight', 0.85, 'elite_content', 'system'),
('CONTENT_ELITE: Le content stacking: publier 3 contenus lies le meme jour sur 3 plateformes differentes cree un effet de masse et amplifie la portee cross-platform.', 'Content stacking: 3 contenus lies meme jour 3 plateformes = amplification', 'content', 'best_practice', 0.82, 'elite_content', 'system'),
('CONTENT_ELITE: Le algorithme Instagram 2026 utilise 4 signaux principaux dans l ordre: 1) watch time/saves, 2) shares via DM, 3) comments, 4) likes. Optimiser pour les saves.', 'IG 2026 algo: watch time/saves > shares DM > comments > likes', 'content', 'insight', 0.90, 'elite_content', 'system'),
('CONTENT_ELITE: Le algorithme TikTok For You 2026: 1) completion rate, 2) rewatches, 3) shares, 4) comments, 5) follows from video. Le rewatch est le signal le plus puissant.', 'TikTok 2026 FYP: completion > rewatch > shares > comments > follows', 'content', 'insight', 0.90, 'elite_content', 'system'),
('CONTENT_ELITE: Le algorithme LinkedIn 2026 pondere: 1) dwell time (temps de lecture), 2) meaningful comments (5+ mots), 3) reshares, 4) reactions.', 'LinkedIn 2026 algo: dwell time > meaningful comments > reshares > reactions', 'content', 'insight', 0.88, 'elite_content', 'system'),
('CONTENT_ELITE: Le content pillar mapping: definir 3-5 piliers de contenu (sujets cles), chaque pilier ayant 10-15 sous-sujets. Tourner entre les piliers.', 'Content pillars: 3-5 piliers × 10-15 sous-sujets. Rotation', 'content', 'best_practice', 0.88, 'elite_content', 'system'),
('CONTENT_ELITE: Le storytelling en milieu professionnel: toujours inclure 1 moment de vulnerabilite. L imperfection connecte 3x plus que la perfection.', 'Vulnerabilite dans storytelling = 3x connexion vs perfection', 'content', 'insight', 0.85, 'elite_content', 'system'),
('CONTENT_ELITE: Le content compounding: les articles evergreen generent du trafic cumulatif. 1 article de qualite = trafic croissant pendant 2-3 ans.', 'Content compounding: 1 article evergreen = trafic croissant 2-3 ans', 'content', 'insight', 0.88, 'elite_content', 'system'),
('CONTENT_ELITE: Le semantic richness: les contenus qui utilisent des synonymes, des champs lexicaux riches et du vocabulaire varie rankent 15% mieux en SEO.', 'Semantic richness: vocabulaire varie = +15% ranking SEO', 'content', 'insight', 0.82, 'elite_content', 'system'),
('CONTENT_ELITE: Le personal story framework pour les posts: 1 fait (ce qui s est passe), 1 feeling (ce que j ai ressenti), 1 finding (ce que j ai appris).', 'Personal story: 1 fait + 1 feeling + 1 finding', 'content', 'best_practice', 0.85, 'elite_content', 'system'),
('CONTENT_ELITE: Le caption engineering sur IG: premiere phrase = hook (arreter le scroll), derniere phrase = CTA + appel a l action. Le milieu = valeur.', 'Caption IG: hook debut + valeur milieu + CTA fin', 'content', 'best_practice', 0.88, 'elite_content', 'system'),
('CONTENT_ELITE: Le concept de content-audience flywheel: plus l audience grandit → plus de feedback → meilleur contenu → plus d audience. Iterer vite.', 'Content-audience flywheel: audience → feedback → meilleur contenu → audience', 'content', 'insight', 0.85, 'elite_content', 'system'),
('CONTENT_ELITE: Le snackable-to-deep funnel: contenu court (Reels, tweets) pour attirer → contenu long (blog, podcast) pour convertir → contenu exclusif pour retenir.', 'Funnel contenu: court (attirer) → long (convertir) → exclusif (retenir)', 'content', 'best_practice', 0.85, 'elite_content', 'system'),
('CONTENT_ELITE: Le timing precision par plateforme FR: LinkedIn 7h30-8h30, Instagram 12h-13h et 19h-21h, TikTok 11h-13h et 19h-22h, X 8h-9h et 18h-19h.', 'Timing FR: LI 7h30, IG 12h+19h, TT 11h+19h, X 8h+18h', 'content', 'best_practice', 0.85, 'elite_content', 'system'),
('CONTENT_ELITE: Le repost strategy: re-publier les meilleurs contenus 3-6 mois plus tard avec une mise a jour. 70% de l audience n a pas vu le premier.', 'Repost 3-6 mois + MAJ: 70% audience n a pas vu le premier', 'content', 'best_practice', 0.82, 'elite_content', 'system'),
('CONTENT_ELITE: Le content debt: comme la dette technique, les contenus obsoletes non mis a jour degradent la credibilite. Auditer trimestriellement.', 'Content debt: contenus obsoletes = credibilite degradee. Audit trimestriel', 'content', 'insight', 0.82, 'elite_content', 'system'),
('CONTENT_ELITE: Le vanity metrics trap: les likes ne correlent pas avec les ventes. Les saves et les partages sont les vrais indicateurs de valeur.', 'Vanity metrics: likes ≠ ventes. Saves + partages = vrais indicateurs', 'content', 'insight', 0.88, 'elite_content', 'system'),
('CONTENT_ELITE: Le content moat: la voix unique (ton, style, perspective) est inimitable par les concurrents. C est le seul avantage durable en contenu.', 'Content moat: voix unique = seul avantage durable inimitable', 'content', 'insight', 0.88, 'elite_content', 'system'),
('CONTENT_ELITE: Le audience-first creation: demander a l audience ce qu elle veut (sondages, commentaires) puis creer ce contenu. 100% product-market fit.', 'Audience-first: demander puis creer = 100% content-market fit', 'content', 'best_practice', 0.88, 'elite_content', 'system'),
('CONTENT_ELITE: Le content ecosystem: chaque plateforme a un role. LinkedIn = credibilite. Instagram = communaute. TikTok = decouverte. Blog = SEO. Newsletter = retention.', 'Content ecosystem: LI credibilite, IG communaute, TT decouverte, blog SEO, newsletter retention', 'content', 'best_practice', 0.90, 'elite_content', 'system'),
('CONTENT_ELITE: Le micro-learning format (1 concept en 60s) est le format le plus save-able sur toutes les plateformes. Ideal pour le contenu educatif.', 'Micro-learning 1 concept 60s = plus save-able toutes plateformes', 'content', 'insight', 0.85, 'elite_content', 'system'),
('CONTENT_ELITE: Le content production system: 1 jour par semaine dedie a la creation (batch) → planification automatique → publication auto → analyse → iteration.', 'Content system: 1 jour batch → auto-planification → auto-publication → analyse → iteration', 'content', 'best_practice', 0.85, 'elite_content', 'system')
ON CONFLICT DO NOTHING;
