-- ═══ MASSIVE BOOST BATCH 13 — Focus expertise specialisee ═══

INSERT INTO agent_knowledge (content, summary, agent, category, confidence, source, created_by) VALUES
('FUNNEL: Le funnel TOFU-MOFU-BOFU: Top (awareness, blog, social) → Middle (consideration, email, webinar) → Bottom (decision, demo, essai).', 'TOFU-MOFU-BOFU funnel', NULL, 'best_practice', 0.92, 'massive_boost_13', 'system'),
('FUNNEL: Chaque etape du funnel perd 50-80% des visiteurs. 1000 visiteurs → 100 leads → 20 essais → 5 clients = normal.', 'Funnel perte: 1000→100→20→5 = normal', NULL, 'insight', 0.88, 'massive_boost_13', 'system'),
('FUNNEL: Le goulot d etranglement est toujours a 1 seul endroit. L identifier et le corriger multiplie les resultats.', 'Identifier 1 goulot = multiplier resultats', NULL, 'best_practice', 0.92, 'massive_boost_13', 'system'),
('COPYWRITING ADVANCED: Le framework PASTOR: Problem, Amplify, Story, Transformation, Offer, Response. Le plus complet pour les pages de vente.', 'Framework PASTOR pages de vente', NULL, 'best_practice', 0.85, 'massive_boost_13', 'system'),
('COPYWRITING ADVANCED: Le "power of free": le mot gratuit augmente les conversions de 321%. "Essai gratuit" > "Essai".', 'Mot gratuit = +321% conversion', NULL, 'insight', 0.85, 'massive_boost_13', 'system'),
('COPYWRITING ADVANCED: Le subhead (sous-titre) est lu par 90% des lecteurs. Aussi important que le titre.', 'Sous-titre lu par 90%', NULL, 'insight', 0.82, 'massive_boost_13', 'system'),
('SOCIAL PROOF: Les logos clients sur la homepage augmentent la conversion de 35%. Minimum 5 logos reconnaissables.', 'Logos clients homepage = +35% conversion', NULL, 'best_practice', 0.88, 'massive_boost_13', 'system'),
('SOCIAL PROOF: Le "nombre de clients" affiche (2000+ commerces nous font confiance) augmente la confiance de 60%.', 'Nombre clients affiche = +60% confiance', NULL, 'best_practice', 0.88, 'massive_boost_13', 'system'),
('SOCIAL PROOF: Les ratings 4.5-4.8 convertissent mieux que 5.0 (trop parfait = suspect).', 'Rating 4.5-4.8 > 5.0 (plus credible)', NULL, 'insight', 0.82, 'massive_boost_13', 'system'),
('SOCIAL PROOF: Les temoignages video de clients reels convertissent 4x mieux que les textes anonymes.', 'Temoignage video reel = 4x conversion', NULL, 'best_practice', 0.90, 'massive_boost_13', 'system'),
('AUTOMATION ADVANCED: Le lead scoring predictif (ML) identifie les prospects prets a acheter avec 85% de precision.', 'Lead scoring ML = 85% precision', 'marketing', 'insight', 0.82, 'massive_boost_13', 'system'),
('AUTOMATION ADVANCED: Les chatbots qualifient les leads 24/7 et transmettent les HOT leads immediatement a l equipe commerciale.', 'Chatbot qualifie 24/7 + transmet HOT leads', 'chatbot', 'best_practice', 0.88, 'massive_boost_13', 'system'),
('AUTOMATION ADVANCED: Le workflow multi-canal (email J0 → SMS J+2 → DM J+5 → appel J+7) a un taux de conversion 5x superieur au mono-canal.', 'Workflow multi-canal = 5x conversion', NULL, 'best_practice', 0.90, 'massive_boost_13', 'system'),
('CUSTOMER JOURNEY: Les 5 moments de verite: 1. Decouverte 2. Evaluation 3. Achat 4. Experience 5. Recommandation. Optimiser chacun.', '5 moments verite: decouverte→evaluation→achat→experience→recommandation', NULL, 'best_practice', 0.88, 'massive_boost_13', 'system'),
('CUSTOMER JOURNEY: Le moment d achat est le PIRE moment pour upsell (buyer remorse). Attendre J+7 pour proposer un upgrade.', 'Upsell: attendre J+7 (pas au moment d achat)', NULL, 'insight', 0.82, 'massive_boost_13', 'system'),
('BRAND LOYALTY: Les clients emotionnellement connectes a une marque ont un LTV 306% superieur.', 'Connexion emotionnelle = +306% LTV', NULL, 'insight', 0.85, 'massive_boost_13', 'system'),
('BRAND LOYALTY: Les marques avec une cause sociale/environnementale ont 4x plus de clients fideles.', 'Cause sociale = 4x fidelite', NULL, 'insight', 0.80, 'massive_boost_13', 'system'),
('BRAND LOYALTY: Le programme de fidelite tiered (Bronze/Silver/Gold) augmente les depenses de 47%.', 'Fidelite tiered = +47% depenses', NULL, 'best_practice', 0.85, 'massive_boost_13', 'system'),
('PRICING PSYCHOLOGY: Le "decoy effect": ajouter une 3eme option (mediocre) pour rendre la 2eme plus attractive.', 'Decoy effect: 3eme option mediocre → 2eme attractive', NULL, 'insight', 0.82, 'massive_boost_13', 'system'),
('PRICING PSYCHOLOGY: Le monthly vs annual: afficher le prix quotidien ("1.63€/jour") reduit la resistance au prix de 50%.', 'Prix quotidien = -50% resistance', NULL, 'insight', 0.85, 'massive_boost_13', 'system'),
('EMAIL DELIVRABILITE: Le sender score (1-100) determine si vos emails arrivent en inbox. Objectif: > 80.', 'Sender score > 80 pour inbox', 'email', 'best_practice', 0.90, 'massive_boost_13', 'system'),
('EMAIL DELIVRABILITE: Le ratio texte/image dans un email doit etre 60/40. Trop d images = spam.', 'Ratio texte/image email: 60/40', 'email', 'best_practice', 0.85, 'massive_boost_13', 'system'),
('EMAIL DELIVRABILITE: L authentification email triple (SPF+DKIM+DMARC) est obligatoire en 2026. Google et Yahoo l exigent.', 'SPF+DKIM+DMARC obligatoire 2026', 'email', 'best_practice', 0.95, 'massive_boost_13', 'system'),
('INNOVATION: Le marche des agents IA autonomes depasse 50 milliards $ en 2026. Les early adopters domineront le marche.', 'Marche agents IA: 50Mds$ 2026', 'ceo', 'insight', 0.80, 'massive_boost_13', 'system'),
('INNOVATION: L IA generative transforme le marketing: creation de contenu 10x plus rapide a 1/10 du cout.', 'IA generative: 10x vitesse, 1/10 cout', 'ceo', 'insight', 0.85, 'massive_boost_13', 'system'),
('INNOVATION: Le commerce social (achat directement depuis les reseaux sociaux) represente 1.2 trillion $ en 2026.', 'Social commerce: 1.2T$ 2026', 'ceo', 'insight', 0.80, 'massive_boost_13', 'system'),
('AI AGENTS: Les agents IA qui apprennent des interactions de TOUS les clients sont exponentiellement meilleurs que ceux isoles.', 'Agents cross-clients = exponentiellement meilleurs', 'ceo', 'insight', 0.92, 'massive_boost_13', 'system'),
('AI AGENTS: La boucle agent: perception → raisonnement → action → apprentissage. Chaque cycle ameliore le suivant.', 'Boucle agent: percevoir → raisonner → agir → apprendre', 'ceo', 'best_practice', 0.90, 'massive_boost_13', 'system'),
('AI AGENTS: Le RAG (Retrieval Augmented Generation) est 10x plus efficace que le fine-tuning pour les connaissances specifiques.', 'RAG > fine-tuning pour connaissances specifiques: 10x', 'ceo', 'insight', 0.88, 'massive_boost_13', 'system'),
('AI AGENTS: Les agents multi-modaux (texte + image + audio) sont 3x plus efficaces que les agents texte seul.', 'Agents multi-modaux = 3x efficaces', 'ceo', 'insight', 0.82, 'massive_boost_13', 'system')
ON CONFLICT DO NOTHING;
