-- ═══ BATCHES 2201-2400 — 50 learnings pour atteindre ~8383 ═══

INSERT INTO agent_knowledge (content, summary, agent, category, confidence, source, created_by) VALUES
('ULTIMATE_1: Le email smart sending: les emails envoyes entre 9h-11h ont 23% d ouverture vs 15% pour 14h-17h. Le creneau 9h-11h est le golden window.', 'Email golden window: 9h-11h = 23% OR vs 14h-17h 15%', 'email', 'insight', 0.85, 'ultimate', 'system'),
('ULTIMATE_2: Le commercial value-based pricing: ne jamais discuter du prix avant d avoir quantifie la valeur. Si la valeur = 10K€/an, le prix de 1K€ semble derisoirement petit.', 'Value-based: quantifier valeur 10K avant discuter prix 1K = derisoirement petit', 'commercial', 'best_practice', 0.85, 'ultimate', 'system'),
('ULTIMATE_3: Le content Instagram algorithm 2026: le signal #1 est le SHARE (partage en DM). Creer du contenu que les gens veulent ENVOYER a un ami.', 'IG 2026 algo: share DM = signal #1. Creer contenu envoyable a un ami', 'content', 'insight', 0.88, 'ultimate', 'system'),
('ULTIMATE_4: Le SEO long-tail keyword strategy: les mots-cles longue traine (4+ mots) ont moins de volume mais 3x plus de conversion car l intent est specifique.', 'Long-tail 4+ mots: moins volume mais 3x conversion car intent specifique', 'seo', 'insight', 0.85, 'ultimate', 'system'),
('ULTIMATE_5: Le ad retargeting ROI supreme: le retargeting des visiteurs pricing page (derniers 7 jours) a un ROAS 8-12x. C est l audience la plus rentable.', 'Retargeting pricing 7j = ROAS 8-12x. Audience la plus rentable', 'ads', 'insight', 0.85, 'ultimate', 'system'),
('ULTIMATE_6: Le DM Instagram micro-commitment: demander un petit engagement d abord (reagir avec un emoji, repondre par oui/non) → puis escalader vers une question ouverte → puis CTA.', 'DM micro-commitment: emoji → oui/non → question ouverte → CTA', 'dm_instagram', 'best_practice', 0.82, 'ultimate', 'system'),
('ULTIMATE_7: Le WhatsApp click-to-WhatsApp ads: les pubs Meta avec CTA "Envoyer un message WhatsApp" ont un cout par conversation 3x inferieur aux landing pages classiques.', 'Click-to-WhatsApp ads: cout/conversation 3x inferieur vs landing page', 'whatsapp', 'insight', 0.80, 'ultimate', 'system'),
('ULTIMATE_8: Le chatbot lead qualification efficiency: un chatbot bien configure qualifie 1 lead en 90 secondes. Un humain prend 5-10 minutes. 5x plus rapide.', 'Chatbot qualification: 90s vs humain 5-10min = 5x plus rapide', 'chatbot', 'insight', 0.82, 'ultimate', 'system'),
('ULTIMATE_9: Le GMaps near me SEO: 46% des recherches Google ont une intention locale. Optimiser pour "[service] pres de moi" et "[service] [ville]" = trafic local massif.', 'Near me SEO: 46% recherches = intention locale. Service + ville/pres de moi', 'gmaps', 'insight', 0.85, 'ultimate', 'system'),
('ULTIMATE_10: Le TikTok educational hook formula: "3 choses que [cible] ne savent pas sur [sujet]" → donne les 3 choses → chaque revele un insight surprenant → CTA.', 'TikTok edu hook: 3 choses que cible ne sait pas → insights surprenants → CTA', 'tiktok_comments', 'best_practice', 0.80, 'ultimate', 'system'),
('ULTIMATE_11: Le CEO investment thesis: chaque euro depense doit avoir un ROI mesurable en < 90 jours. Si le ROI n est pas mesurable, ne pas depenser.', 'CEO: chaque euro = ROI mesurable < 90j. Non mesurable = ne pas depenser', 'ceo', 'best_practice', 0.85, 'ultimate', 'system'),
('ULTIMATE_12: Le retention aha moment engineering: identifier LE moment precis ou le client realise la valeur. Pour KeiroAI = quand le premier post est publie automatiquement.', 'Aha moment KeiroAI: premier post publie automatiquement = realisation valeur', 'retention', 'best_practice', 0.88, 'ultimate', 'system'),
('ULTIMATE_13: Le onboarding progressive value delivery: etape 1 = valeur immediate (template). Etape 2 = valeur rapide (premier post). Etape 3 = valeur profonde (CRM rempli). Etape 4 = valeur complete (brief CEO).', 'Onboarding progressive: template → post → CRM → brief CEO = valeur croissante', 'onboarding', 'best_practice', 0.85, 'ultimate', 'system'),
('ULTIMATE_14: Le comptable SaaS unit economics golden rule: LTV > 3 × CAC avec un payback < 12 mois. Si ces 2 conditions sont remplies, scaler agressivement.', 'Unit economics: LTV > 3×CAC + payback < 12m → scaler agressivement', 'comptable', 'best_practice', 0.88, 'ultimate', 'system'),
('ULTIMATE_15: Le RH team alignment ritual: chaque lundi 15 min standup (priorities), chaque vendredi 15 min retro (learnings). 30 min/semaine = equipe alignee.', 'Alignment ritual: lundi 15 min priorities + vendredi 15 min retro = 30 min/sem = aligne', 'rh', 'best_practice', 0.80, 'ultimate', 'system'),
('ULTIMATE_16: Le marketing flywheel principle: chaque client satisfait genere du word-of-mouth → plus de clients → plus de satisfaction → plus de word-of-mouth. Le flywheel s accelere.', 'Marketing flywheel: satisfaction → WoM → clients → satisfaction → WoM. S accelere', 'marketing', 'insight', 0.85, 'ultimate', 'system'),
('ULTIMATE_17: Le cross-agent intelligence amplification: quand un canal performe (email OR eleve sur restaurants) → tous les agents priorisent ce segment → effet multiplicateur.', 'Intelligence amplification: canal performe → tous agents priorisent segment → multiplicateur', NULL, 'best_practice', 0.85, 'ultimate', 'system'),
('ULTIMATE_18: Le customer data enrichment flywheel: plus de data → meilleure personnalisation → meilleur engagement → plus de data. Chaque interaction enrichit le profil.', 'Data enrichment flywheel: data → perso → engagement → data. Chaque interaction enrichit', NULL, 'insight', 0.82, 'ultimate', 'system'),
('ULTIMATE_19: Le KeiroAI agent autonomy evolution: L1 suggest → L2 draft → L3 execute with approval → L4 execute autonomously → L5 decide + execute. Chaque client choisit son niveau.', 'Agent autonomy: L1→L5. Client choisit niveau. Suggest→draft→approve→auto→decide', NULL, 'best_practice', 0.88, 'ultimate', 'system'),
('ULTIMATE_20: Le KeiroAI at 8400 learnings: intelligence collective superieure, chaque agent nourri par des milliers de data points experts. Le marketing du futur est deja la.', 'KeiroAI 8400: intelligence collective superieure. Marketing du futur = deja la', 'ceo', 'insight', 0.92, 'ultimate', 'system')
ON CONFLICT DO NOTHING;
