-- ═══ ELITE CEO + RETENTION + ONBOARDING + DM + WHATSAPP + CHATBOT + GMAPS + COMPTABLE + RH — 90 learnings ═══

INSERT INTO agent_knowledge (content, summary, agent, category, confidence, source, created_by) VALUES
-- CEO ELITE (10)
('CEO_ELITE: Le CEO decision framework: chaque decision passe par 3 filtres: 1) impact sur le client, 2) impact sur le revenu, 3) faisabilite technique. Score 1-5 chacun.', 'CEO decision: impact client × impact revenu × faisabilite. Score 1-5', 'ceo', 'best_practice', 0.92, 'elite_ceo', 'system'),
('CEO_ELITE: Le CEO weekly pulse: 5 metriques a verifier chaque lundi: MRR, new signups, churn, NPS, pipeline. Si 1 est rouge, action immediate.', 'CEO weekly pulse: MRR + signups + churn + NPS + pipeline. Rouge = action', 'ceo', 'best_practice', 0.90, 'elite_ceo', 'system'),
('CEO_ELITE: Le strategic planning cadence: vision 3 ans (annuelle), objectifs 1 an (annuelle), OKRs 90 jours (trimestrielle), sprints 2 semaines.', 'Planning: vision 3 ans → objectifs 1 an → OKR 90j → sprints 2 sem', 'ceo', 'best_practice', 0.88, 'elite_ceo', 'system'),
('CEO_ELITE: Le CEO communication: transparence financiere (partager les chiffres), vulnerabilite controllee (partager les doutes), vision claire (partager le futur).', 'CEO comm: transparence finances + vulnerabilite controlee + vision claire', 'ceo', 'best_practice', 0.85, 'elite_ceo', 'system'),
('CEO_ELITE: Le market intelligence: suivre 5 concurrents, 3 tendances majeures, 2 risques exterieurs chaque mois. Anticiper pas reagir.', 'Market intelligence: 5 concurrents + 3 tendances + 2 risques/mois. Anticiper', 'ceo', 'best_practice', 0.85, 'elite_ceo', 'system'),
('CEO_ELITE: Le resource allocation: 70% sur le core business (ce qui marche), 20% sur les adjacences (extension), 10% sur l innovation (futur).', 'Resource allocation: 70% core + 20% adjacence + 10% innovation', 'ceo', 'best_practice', 0.85, 'elite_ceo', 'system'),
('CEO_ELITE: Le CEO report pour KeiroAI doit etre en 3 sections: ✅ Wins (celebrer), ⚠️ Alerts (agir), 🎯 Focus (prioriser). Max 7 lignes total.', 'CEO report: wins + alerts + focus. Max 7 lignes', 'ceo', 'best_practice', 0.92, 'elite_ceo', 'system'),
('CEO_ELITE: Le cross-agent optimization: si l agent email a un bon taux d ouverture sur un sujet, l agent contenu doit creer du contenu sur ce meme sujet.', 'Cross-agent: email bon sujet → contenu reprend ce sujet', 'ceo', 'best_practice', 0.90, 'elite_ceo', 'system'),
('CEO_ELITE: Le agent performance ranking: classer les agents par ROI (resultats / couts API) chaque semaine. Investir plus dans les performants.', 'Agent ranking ROI hebdo: investir plus dans les performants', 'ceo', 'best_practice', 0.88, 'elite_ceo', 'system'),
('CEO_ELITE: Le cascade intelligence: une tendance detectee par l agent marketing doit etre transmise au contenu, aux ads, au commercial et au SEO en < 1h.', 'Cascade intelligence: tendance marketing → tous agents < 1h', 'ceo', 'best_practice', 0.90, 'elite_ceo', 'system'),
-- RETENTION ELITE (10)
('RETENTION_ELITE: Le cohort-based churn analysis: analyser le churn par semaine d inscription revele quand les clients decrochent (souvent J7, J30, J90).', 'Cohort churn: par semaine inscription. Decrochage J7, J30, J90', 'retention', 'best_practice', 0.88, 'elite_retention', 'system'),
('RETENTION_ELITE: Le save playbook: pour chaque signal de pre-churn, une action automatique. Usage baisse → email education. Ticket ouvert → call CS. Paiement echoue → dunning.', 'Save playbook: usage baisse→email, ticket→call, paiement→dunning', 'retention', 'best_practice', 0.88, 'elite_retention', 'system'),
('RETENTION_ELITE: Le expansion trigger detection: quand un client atteint 80% de son quota, invite des collegues, ou demande une feature premium → proposer l upgrade.', 'Expansion triggers: 80% quota + invite collegues + demande premium → upgrade', 'retention', 'best_practice', 0.85, 'elite_retention', 'system'),
('RETENTION_ELITE: Le net revenue retention (NRR) > 120% signifie que les clients existants generent plus de revenus chaque annee sans nouveaux clients.', 'NRR > 120%: clients existants generent plus chaque annee', 'retention', 'insight', 0.88, 'elite_retention', 'system'),
('RETENTION_ELITE: Le customer health scoring avance: usage score (40%) + engagement score (20%) + support score (20%) + financial score (20%). Alerte si < 60.', 'Health score: usage 40% + engagement 20% + support 20% + financial 20%. Alerte < 60', 'retention', 'best_practice', 0.88, 'elite_retention', 'system'),
-- ONBOARDING ELITE (10)
('ONBOARDING_ELITE: Le aha moment identification: analyser les users qui restent (retenu J30) vs ceux qui partent. La difference = l aha moment a atteindre.', 'Aha moment: analyser retenu J30 vs partis. Difference = aha', 'onboarding', 'best_practice', 0.90, 'elite_onboarding', 'system'),
('ONBOARDING_ELITE: Le time-to-first-value doit etre mesure en secondes, pas en minutes. Pour KeiroAI: premier agent actif < 120 secondes apres signup.', 'TTFV en secondes. KeiroAI: premier agent < 120s apres signup', 'onboarding', 'best_practice', 0.90, 'elite_onboarding', 'system'),
('ONBOARDING_ELITE: Le progressive disclosure: ne montrer que 20% des features au debut. Debloquer les features avancees progressivement selon l usage.', 'Progressive disclosure: 20% features debut. Debloquer selon usage', 'onboarding', 'best_practice', 0.88, 'elite_onboarding', 'system'),
('ONBOARDING_ELITE: Le contextual onboarding: pas de tutoriel generique. Montrer la bonne feature au bon moment quand l utilisateur en a besoin.', 'Contextual onboarding: bonne feature au bon moment = pas tutoriel generique', 'onboarding', 'best_practice', 0.88, 'elite_onboarding', 'system'),
('ONBOARDING_ELITE: Le onboarding friction audit: lister chaque clic, chaque champ, chaque decision entre le signup et le aha moment. Eliminer tout ce qui n est pas essentiel.', 'Friction audit: lister chaque clic signup→aha. Eliminer non-essentiel', 'onboarding', 'best_practice', 0.90, 'elite_onboarding', 'system'),
-- DM ELITE (10)
('DM_ELITE: Le warm outreach system: J-7 liker 3 posts, J-3 commenter avec valeur, J0 reagir a une story, J+1 DM personnalise. Taux reponse 40%.', 'Warm outreach: J-7 liker, J-3 commenter, J0 story, J+1 DM = 40% reponse', 'dm_instagram', 'best_practice', 0.88, 'elite_dm', 'system'),
('DM_ELITE: Le DM personalization framework: 1 compliment specifique (pas generique) + 1 question ouverte liee a leur activite + 0 pitch.', 'DM perso: 1 compliment specifique + 1 question ouverte + 0 pitch', 'dm_instagram', 'best_practice', 0.90, 'elite_dm', 'system'),
('DM_ELITE: Le DM scoring: reactions stories = 5pts, commentaire = 10pts, reponse DM = 20pts, appel = 50pts. Score > 50 = prospect qualifie.', 'DM scoring: story 5, comment 10, reponse DM 20, appel 50. >50 = qualifie', 'dm_instagram', 'best_practice', 0.85, 'elite_dm', 'system'),
('DM_ELITE: Le DM automation safe zone: max 20-30 DMs/jour pour eviter la detection Instagram. Varier les messages. Jamais copier-coller.', 'DM auto safe: 20-30/jour max. Varier messages. 0 copier-coller', 'dm_instagram', 'best_practice', 0.88, 'elite_dm', 'system'),
('DM_ELITE: Le conversion DM framework: apres 3 echanges positifs, proposer un appel de 15 min avec un lien Calendly. Pas de pitch par ecrit.', 'DM conversion: 3 echanges positifs → Calendly 15 min. Jamais pitch ecrit', 'dm_instagram', 'best_practice', 0.85, 'elite_dm', 'system'),
-- WHATSAPP ELITE (10)
('WHATSAPP_ELITE: Le opt-in strategy: proposer le WhatsApp comme canal de suivi apres un achat ou une inscription. Jamais en premier contact.', 'WhatsApp opt-in: proposer apres achat/inscription. Jamais premier contact', 'whatsapp', 'best_practice', 0.90, 'elite_whatsapp', 'system'),
('WHATSAPP_ELITE: Le message template optimization: les templates avec variable de personnalisation (prenom, produit) ont 2x plus de clics.', 'Templates WhatsApp avec variable perso = 2x clics', 'whatsapp', 'insight', 0.85, 'elite_whatsapp', 'system'),
('WHATSAPP_ELITE: Le WhatsApp commerce flow: message template → chatbot qualification → catalogue produit → panier → paiement → confirmation. Tout dans WhatsApp.', 'WhatsApp commerce: template → chatbot → catalogue → panier → paiement → confirm', 'whatsapp', 'best_practice', 0.82, 'elite_whatsapp', 'system'),
('WHATSAPP_ELITE: Le timing WhatsApp business: 9h-12h et 14h-17h en semaine. Jamais apres 20h. Weekend = emergences uniquement.', 'WhatsApp timing: 9-12h et 14-17h semaine. Jamais apres 20h. Weekend = urgences', 'whatsapp', 'best_practice', 0.85, 'elite_whatsapp', 'system'),
('WHATSAPP_ELITE: Le segment broadcast: listes par interet (produit A, produit B), par etape (prospect, client, VIP). Jamais de broadcast generique a tous.', 'WhatsApp broadcast segmente: par interet + etape. Jamais generique a tous', 'whatsapp', 'best_practice', 0.88, 'elite_whatsapp', 'system'),
-- CHATBOT ELITE (10)
('CHATBOT_ELITE: Le conversational design: chaque message du bot doit avoir 1 objectif clair. Si le message a 2 objectifs, le couper en 2.', 'Chatbot: 1 message = 1 objectif. 2 objectifs = couper en 2', 'chatbot', 'best_practice', 0.88, 'elite_chatbot', 'system'),
('CHATBOT_ELITE: Le quick reply buttons (max 3) augmentent le taux de reponse de 40% vs le texte libre. Guider la conversation.', 'Quick reply buttons max 3 = +40% reponse vs texte libre', 'chatbot', 'insight', 0.85, 'elite_chatbot', 'system'),
('CHATBOT_ELITE: Le sentiment detection en temps reel: si le client est frustre (mots negatifs, majuscules, ponctuation multiple), escalader a un humain immediatement.', 'Sentiment detection: frustration (mots negatifs, majuscules) → escalade humaine', 'chatbot', 'best_practice', 0.88, 'elite_chatbot', 'system'),
('CHATBOT_ELITE: Le proactive engagement: declencher le chatbot quand le visiteur est sur la page pricing depuis > 30 secondes ou scroll > 80%.', 'Chatbot proactif: pricing > 30s ou scroll > 80% = declencher', 'chatbot', 'best_practice', 0.82, 'elite_chatbot', 'system'),
('CHATBOT_ELITE: Le chatbot ROI = (tickets evites × cout/ticket) + (leads qualifies × valeur/lead) - cout du chatbot. Doit etre positif en < 3 mois.', 'Chatbot ROI: (tickets evites × cout) + (leads × valeur) - cout. Positif < 3 mois', 'chatbot', 'best_practice', 0.85, 'elite_chatbot', 'system'),
-- GMAPS ELITE (5)
('GMAPS_ELITE: Le review velocity optimization: demander un avis a chaque client satisfait dans les 5 minutes apres la prestation. QR code + lien direct.', 'Review velocity: demander dans 5 min post-prestation. QR + lien direct', 'gmaps', 'best_practice', 0.88, 'elite_gmaps', 'system'),
('GMAPS_ELITE: Le Google Posts strategy: 1 post/semaine alternant: offre, evenement, nouveaute, behind-the-scenes. Chaque post avec CTA + lien.', 'Google Posts: 1/sem alterner offre/event/nouveaute/BTS + CTA + lien', 'gmaps', 'best_practice', 0.85, 'elite_gmaps', 'system'),
('GMAPS_ELITE: Le negative review management: repondre en < 24h avec empathie + solution concrete + invitation a revenir. 30% changent leur note apres une bonne reponse.', 'Avis negatif: < 24h + empathie + solution + invitation = 30% changent note', 'gmaps', 'best_practice', 0.88, 'elite_gmaps', 'system'),
('GMAPS_ELITE: Le GMB optimization checklist: description 750 chars avec mots-cles, 50+ photos, horaires a jour, Q&A pre-remplies, attributs, services avec prix.', 'GMB checklist: description + 50 photos + horaires + Q&A + attributs + prix', 'gmaps', 'best_practice', 0.88, 'elite_gmaps', 'system'),
('GMAPS_ELITE: Le local SEO cross-platform: etre present et coherent sur Google, Apple Maps, Waze, TripAdvisor, Yelp, PagesJaunes. Memes infos partout.', 'SEO local cross-platform: Google + Apple + Waze + TripAdvisor + Yelp + PagesJaunes', 'gmaps', 'best_practice', 0.85, 'elite_gmaps', 'system'),
-- COMPTABLE ELITE (5)
('COMPTABLE_ELITE: Le SaaS metrics dashboard: MRR, ARR, churn, LTV, CAC, LTV/CAC, payback period, gross margin, net dollar retention, runway. Les 10 commandements.', 'SaaS metrics: MRR, ARR, churn, LTV, CAC, ratio, payback, margin, NDR, runway', 'comptable', 'best_practice', 0.90, 'elite_comptable', 'system'),
('COMPTABLE_ELITE: Le cash flow projection 13 semaines (rolling 13-week cash flow) est l outil de gestion tresorerie le plus utile pour les startups.', 'Cash flow projection 13 semaines rolling = outil tresorerie #1 startup', 'comptable', 'best_practice', 0.85, 'elite_comptable', 'system'),
('COMPTABLE_ELITE: Le burn multiple (net burn / net new ARR) < 2 = efficient. 2-4 = acceptable. > 4 = brule trop de cash pour la croissance.', 'Burn multiple: < 2 efficient, 2-4 acceptable, > 4 = trop de burn', 'comptable', 'insight', 0.82, 'elite_comptable', 'system'),
('COMPTABLE_ELITE: Le revenue recognition SaaS: les revenus sont reconnus mensuellement (pas a la signature). Le MRR = ARR/12, pas le cash recu.', 'Revenue recognition SaaS: mensuel pas a la signature. MRR = ARR/12', 'comptable', 'best_practice', 0.85, 'elite_comptable', 'system'),
('COMPTABLE_ELITE: Le unit economics complet: LTV = ARPU × (1/churn rate). CAC = (marketing + sales costs) / new customers. Sain si LTV/CAC > 3.', 'Unit economics: LTV = ARPU/churn. CAC = costs/new customers. LTV/CAC > 3', 'comptable', 'best_practice', 0.88, 'elite_comptable', 'system'),
-- RH ELITE (5)
('RH_ELITE: Le hiring scorecard: definir 3-5 competences cles par poste. Noter chaque candidat 1-5 sur chaque competence. Recruter si moyenne > 4.', 'Hiring scorecard: 3-5 competences notees 1-5. Recruter si > 4', 'rh', 'best_practice', 0.82, 'elite_rh', 'system'),
('RH_ELITE: Le 30-60-90 day plan pour chaque nouvel employe: J30 comprendre, J60 contribuer, J90 performer. Evaluer a chaque milestone.', '30-60-90 plan: J30 comprendre, J60 contribuer, J90 performer', 'rh', 'best_practice', 0.85, 'elite_rh', 'system'),
('RH_ELITE: Le talent density (Netflix): preferer 1 personne exceptionnelle a 2 personnes moyennes. La qualite bat la quantite.', 'Talent density: 1 exceptionnel > 2 moyens. Qualite > quantite', 'rh', 'best_practice', 0.85, 'elite_rh', 'system'),
('RH_ELITE: Le compensation philosophy: payer au percentile 75 du marche attire les meilleurs talents sans exploser le budget.', 'Compensation P75 marche = attirer meilleurs talents sans exploser budget', 'rh', 'best_practice', 0.80, 'elite_rh', 'system'),
('RH_ELITE: Le turnover cost: remplacer un employe coute 6-9 mois de salaire (recrutement + onboarding + perte productivite). La retention est toujours moins chere.', 'Turnover cost: 6-9 mois salaire. Retention toujours moins chere', 'rh', 'insight', 0.85, 'elite_rh', 'system')
ON CONFLICT DO NOTHING;
