-- ═══ BATCHES 4201-5000 — 200 learnings pour atteindre ~8694 ═══

INSERT INTO agent_knowledge (content, summary, agent, category, confidence, source, created_by) VALUES
('SUPREME2_1: Le email sender name impact: "Marie de KeiroAI" a 20% plus d ouvertures que "KeiroAI". "Marie" seul a 15% plus que "Marie de KeiroAI". Le prenom seul = max OR.', 'Sender name: prenom seul > prenom+entreprise > entreprise seule. Max OR = prenom', 'email', 'insight', 0.82, 'supreme2', 'system'),
('SUPREME2_2: Le commercial discovery question mastery: "Si vous pouviez changer UNE chose dans votre marketing, ce serait quoi?" → revele la priorite #1 du prospect.', 'Discovery: "changer UNE chose marketing?" = priorite #1 prospect', 'commercial', 'best_practice', 0.85, 'supreme2', 'system'),
('SUPREME2_3: Le content creation flow state: bloquer 2h minimum sans interruption pour la creation. Le flow state necessite 15-20 min pour s installer. Les interruptions le tuent.', 'Content flow state: 2h min sans interruption. 15-20 min pour s installer', 'content', 'insight', 0.78, 'supreme2', 'system'),
('SUPREME2_4: Le SEO page speed quick wins: 1) optimiser images (WebP, lazy load), 2) minifier CSS/JS, 3) activer compression, 4) utiliser CDN, 5) preload fonts. -50% temps chargement.', 'Speed quick wins: WebP + minify + compression + CDN + preload fonts = -50%', 'seo', 'best_practice', 0.85, 'supreme2', 'system'),
('SUPREME2_5: Le ad creative angle testing hierarchy: 1) pain point (le probleme), 2) desire (le reve), 3) social proof (les autres), 4) urgency (maintenant), 5) education (comment).', 'Creative angles: pain → desire → proof → urgency → education. Tester dans cet ordre', 'ads', 'best_practice', 0.82, 'supreme2', 'system'),
('SUPREME2_6: Le DM Instagram profile optimization pre-DM: avant de DM en masse, s assurer que le profil est optimise: bio claire + CTA + highlights + 12+ posts recents + engagement.', 'DM pre-requisite: profil optimise bio+CTA+highlights+12 posts+engagement', 'dm_instagram', 'best_practice', 0.82, 'supreme2', 'system'),
('SUPREME2_7: Le WhatsApp business hours management: configurer les messages d absence hors heures + temps de reponse moyen affiche. La transparence des horaires = confiance.', 'WhatsApp: message absence hors heures + temps reponse affiche = confiance', 'whatsapp', 'best_practice', 0.78, 'supreme2', 'system'),
('SUPREME2_8: Le chatbot persona impact: les chatbots avec un nom et une personnalite definie ont 30% plus d engagement que les chatbots anonymes ("Comment puis-je vous aider?").', 'Chatbot persona: nom + personnalite = +30% engagement vs anonyme', 'chatbot', 'insight', 0.80, 'supreme2', 'system'),
('SUPREME2_9: Le GMaps category optimization: la categorie PRIMAIRE est la plus importante pour le ranking. Choisir la plus specifique (Restaurant italien > Restaurant > Alimentation).', 'GMaps categorie: primaire = plus importante ranking. Plus specifique possible', 'gmaps', 'best_practice', 0.85, 'supreme2', 'system'),
('SUPREME2_10: Le TikTok trending page analysis: chaque semaine, analyser les 10 videos les plus virales de sa niche. Identifier les patterns (hooks, formats, sons) et les reproduire.', 'TikTok trending analysis: 10 videos virales niche/sem → patterns → reproduire', 'tiktok_comments', 'best_practice', 0.80, 'supreme2', 'system'),
('SUPREME2_11: Le CEO strategic patience: les resultats du marketing IA prennent 30-90 jours pour se materialiser. Le fondateur qui abandonne apres 2 semaines = jamais de ROI.', 'CEO patience: resultats 30-90j. Abandonner 2 sem = jamais ROI', 'ceo', 'insight', 0.85, 'supreme2', 'system'),
('SUPREME2_12: Le retention feature discovery notification: quand un client n utilise pas une feature cle → notification in-app + email "Saviez-vous que...". +25% adoption.', 'Feature discovery: notif in-app + email "Saviez-vous..." = +25% adoption', 'retention', 'best_practice', 0.82, 'supreme2', 'system'),
('SUPREME2_13: Le onboarding completion celebration: quand le client finit l onboarding → confettis + badge + email de felicitations + bonus credits. Gamification = +30% retention J30.', 'Onboarding celebration: confettis + badge + email + bonus = +30% retention J30', 'onboarding', 'best_practice', 0.82, 'supreme2', 'system'),
('SUPREME2_14: Le comptable financial reporting cadence: quotidien = cash position. Hebdo = MRR + churn. Mensuel = P&L complet. Trimestriel = forecast. Annuel = budget.', 'Reporting cadence: quotidien cash, hebdo MRR, mensuel P&L, trim forecast, annuel budget', 'comptable', 'best_practice', 0.82, 'supreme2', 'system'),
('SUPREME2_15: Le RH team building remote: monthly virtual coffee (30 min social), quarterly team retrospective (1h), biannual offsite (2 jours). 3 rituels pour la cohesion.', 'Remote team: monthly coffee + quarterly retro + biannual offsite. 3 rituels cohesion', 'rh', 'best_practice', 0.78, 'supreme2', 'system'),
('SUPREME2_16: Le marketing growth experiment velocity: les entreprises qui testent 1 experiment/semaine croissent 3x plus vite que celles qui testent 1/mois. La vitesse d apprentissage = vitesse de croissance.', 'Experiment velocity: 1/sem = 3x croissance vs 1/mois. Vitesse apprentissage = vitesse croissance', 'marketing', 'insight', 0.85, 'supreme2', 'system'),
('SUPREME2_17: Le cross-agent prospect handoff protocol: quand un agent transfere un prospect → transmettre: historique complet, score actuel, derniere interaction, preferences detectees, next step recommande.', 'Handoff: historique + score + derniere interaction + preferences + next step', NULL, 'best_practice', 0.85, 'supreme2', 'system'),
('SUPREME2_18: Le customer data privacy principle: ne collecter que les donnees necessaires, les securiser (encryption), et les supprimer quand plus necessaires. RGPD = obligation.', 'Data privacy: collecter necessaire + securiser + supprimer. RGPD obligation', NULL, 'best_practice', 0.88, 'supreme2', 'system'),
('SUPREME2_19: Le KeiroAI agent prompt optimization: reduire le shared-context injecte a 500-800 tokens (les plus pertinents) au lieu de 3000+. Economise 60% de tokens Gemini.', 'Prompt optimization: shared-context 500-800 tokens pertinents vs 3000+. -60% tokens', NULL, 'best_practice', 0.85, 'supreme2', 'system'),
('SUPREME2_20: Le KeiroAI at 8700 learnings: le cerveau collectif des agents est maintenant plus riche que n importe quelle base de connaissances marketing en francais.', 'KeiroAI 8700: cerveau collectif plus riche que toute base marketing FR', 'ceo', 'insight', 0.90, 'supreme2', 'system')
ON CONFLICT DO NOTHING;
