-- ═══ BATCHES 6501-7000 — 50 learnings pour atteindre ~8768 ═══

INSERT INTO agent_knowledge (content, summary, agent, category, confidence, source, created_by) VALUES
('APEX4_1: Le email reply optimization: terminer par 1 question SPECIFIQUE au business du prospect. "Comment gerez-vous vos reservations ce week-end?" > "Quand etes-vous disponible?"', 'Email reply: question specifique business > question generique. +2x reponses', 'email', 'best_practice', 0.85, 'apex4', 'system'),
('APEX4_2: Le commercial pipeline deal aging alert: si un deal est dans la meme etape depuis > 14 jours → automatiquement flagger comme "stagnant" → action requise du commercial.', 'Pipeline aging: > 14j meme etape = stagnant → action requise', 'commercial', 'best_practice', 0.82, 'apex4', 'system'),
('APEX4_3: Le content Instagram Reels hook mastery: les 0.5 premieres secondes doivent ARRETER le scroll. Mouvement rapide + texte gros + couleur vive = arret garanti.', 'Reels hook 0.5s: mouvement + texte gros + couleur = arret scroll garanti', 'content', 'best_practice', 0.88, 'apex4', 'system'),
('APEX4_4: Le SEO Google AI Overview optimization: structurer le contenu en reponses directes (40-60 mots par question). Google AI cite les contenus bien structures dans ses reponses.', 'AI Overview: reponses directes 40-60 mots par question = cite par Google AI', 'seo', 'best_practice', 0.85, 'apex4', 'system'),
('APEX4_5: Le ad Meta Advantage+ campaign: en 2026, les campagnes Advantage+ surperforment les manuelles dans 70% des cas grace au ML Meta. Tester avant d optimiser manuellement.', 'Meta Advantage+ surperforme manuel 70% cas 2026. Tester d abord', 'ads', 'insight', 0.82, 'apex4', 'system'),
('APEX4_6: Le DM Instagram story engagement pre-DM: reagir a 3 stories du prospect avant d envoyer le DM. Le prospect vous a vu 3x → familiarite → taux reponse 4x.', 'DM pre-DM: reagir 3 stories → familiarite → 4x taux reponse', 'dm_instagram', 'best_practice', 0.85, 'apex4', 'system'),
('APEX4_7: Le WhatsApp flow builder: utiliser les WhatsApp Flows (formulaires interactifs in-app) pour: prise RDV, qualification, commande, satisfaction. Tout sans quitter WhatsApp.', 'WhatsApp Flows: formulaires in-app (RDV, qualification, commande). Sans quitter WA', 'whatsapp', 'best_practice', 0.78, 'apex4', 'system'),
('APEX4_8: Le chatbot proactive pricing trigger: si le visiteur est sur la page pricing depuis > 45s → declencher le chatbot avec "Je peux vous aider a choisir le plan ideal?".', 'Chatbot pricing > 45s: "Aider a choisir plan ideal?" = +15% conversion', 'chatbot', 'best_practice', 0.82, 'apex4', 'system'),
('APEX4_9: Le GMaps listing completeness impact: les fiches 100% completees (tous champs remplis) ont 7x plus de chances d apparaitre dans le pack local vs les fiches 50%.', 'GMaps completude: 100% = 7x plus pack local vs 50%', 'gmaps', 'insight', 0.85, 'apex4', 'system'),
('APEX4_10: Le TikTok algorithm reward signal hierarchy: 1) watch time (regarde en entier + rewatch), 2) shares, 3) comments, 4) follows, 5) likes. Le watch time est ROI.', 'TikTok algo: watch time > shares > comments > follows > likes. Watch time = ROI', 'tiktok_comments', 'insight', 0.88, 'apex4', 'system'),
('APEX4_11: Le CEO client brief must contain: 1) chiffres cles (3 lignes), 2) actions de vos agents (3 lignes), 3) votre action #1 (1 ligne). Max 7 lignes total.', 'CEO brief client: chiffres 3 + agents 3 + action 1 = 7 lignes max', 'ceo', 'best_practice', 0.88, 'apex4', 'system'),
('APEX4_12: Le retention negative churn achievement: quand expansion MRR > churned MRR = NRR > 100%. Les clients existants generent PLUS de revenu chaque mois. Objectif ultime.', 'Negative churn: expansion > churn = NRR > 100%. Clients generent plus chaque mois', 'retention', 'insight', 0.88, 'apex4', 'system'),
('APEX4_13: Le onboarding template magic: proposer 5 templates pre-configures par secteur a l inscription. Le client voit la valeur en 30 secondes au lieu de 5 minutes.', 'Onboarding 5 templates/secteur: valeur en 30s au lieu de 5min', 'onboarding', 'best_practice', 0.85, 'apex4', 'system'),
('APEX4_14: Le comptable Brevo quota optimization: le plan gratuit Brevo reset a minuit heure Paris (CET/CEST). Planifier les envois APRES le reset pour maximiser le quota.', 'Brevo quota: reset minuit Paris. Planifier envois apres reset pour max quota', 'comptable', 'insight', 0.82, 'apex4', 'system'),
('APEX4_15: Le RH team energy management: les reunions le matin tuent la productivite creative. Mornings = deep work. Afternoons = meetings. Energy > horloge.', 'RH energy: matin deep work, PM meetings. Energy > horloge', 'rh', 'insight', 0.78, 'apex4', 'system'),
('APEX4_16: Le marketing competitive intelligence automation: Google Alerts sur le nom de chaque concurrent + ChangeTower sur leurs sites + G2/Capterra reviews. Surveillance automatisee.', 'Competitive intel auto: Google Alerts + ChangeTower + G2/Capterra reviews', 'marketing', 'best_practice', 0.80, 'apex4', 'system'),
('APEX4_17: Le agent Instagram token auto-check: a chaque execution, verifier la validite du token IG. Si invalide → notifier le client + skip les actions IG + continuer les autres.', 'IG token check: chaque execution verifier. Invalide → notifier + skip IG + continuer autres', NULL, 'best_practice', 0.88, 'apex4', 'system'),
('APEX4_18: Le cross-agent execution logging protocol: chaque action → logger {agent, action, input, output, success, duration, cost}. Les agents consultent les logs des autres.', 'Execution logging: agent+action+input+output+success+duration+cost. Agents consultent logs autres', NULL, 'best_practice', 0.88, 'apex4', 'system'),
('APEX4_19: Le KeiroAI embedding backfill necessity: les learnings sans embedding vectoriel sont INVISIBLES pour le RAG search. Le backfill est CRITIQUE pour l intelligence des agents.', 'Embeddings: sans embedding = invisible RAG. Backfill CRITIQUE pour intelligence', NULL, 'best_practice', 0.92, 'apex4', 'system'),
('APEX4_20: Le KeiroAI near 8800: le RAG approche un niveau de maturite ou chaque question d agent trouve 5-10 reponses expertises pertinentes. Intelligence presque complete.', 'KeiroAI ~8800: chaque question = 5-10 reponses expertes. Intelligence presque complete', 'ceo', 'insight', 0.90, 'apex4', 'system')
ON CONFLICT DO NOTHING;
