-- ═══ MASSIVE BOOST BATCH 8 — 200 learnings multi-domaine ═══

INSERT INTO agent_knowledge (content, summary, agent, category, confidence, source, created_by) VALUES
-- ═══ PROSPECTION AVANCEE (40) ═══
('PROSPECTION: Le scraping Google Maps par quartier (rayon 2km) genere 50-200 prospects qualifies par zone.', 'Scraping GMaps quartier = 50-200 prospects/zone', 'commercial', 'best_practice', 0.88, 'massive_boost_8', 'system'),
('PROSPECTION: Les prospects avec un site web actif mais pas de reseaux sociaux = opportunite parfaite. Ils ont besoin de visibilite.', 'Site web sans social = opportunite ideale', 'commercial', 'insight', 0.85, 'massive_boost_8', 'system'),
('PROSPECTION: Enrichir les prospects avec note Google + nombre d avis + activite Instagram permet un scoring precis.', 'Enrichissement Google + IG = scoring precis', 'commercial', 'best_practice', 0.90, 'massive_boost_8', 'system'),
('PROSPECTION: Les commerces avec une note Google 3.5-4.0 sont les meilleurs prospects: conscients du probleme mais pas encore en solution.', 'Note Google 3.5-4.0 = meilleur prospect', 'commercial', 'insight', 0.85, 'massive_boost_8', 'system'),
('PROSPECTION: Le cold calling converti mieux le mardi-jeudi 8h-9h et 16h-17h. Eviter le lundi matin et vendredi apres-midi.', 'Cold call: mar-jeu 8h-9h et 16h-17h', 'commercial', 'best_practice', 0.85, 'massive_boost_8', 'system'),
('PROSPECTION: La technique BANT pour qualifier: Budget, Autorite (decideur?), Need (besoin reel?), Timeline (quand?).', 'BANT qualification: Budget Autorite Need Timeline', 'commercial', 'best_practice', 0.90, 'massive_boost_8', 'system'),
('PROSPECTION: Un prospect qui visite la page pricing 2+ fois en 7 jours est un HOT lead. Le contacter immediatement.', 'Pricing 2+ visites 7j = HOT lead', 'commercial', 'best_practice', 0.92, 'massive_boost_8', 'system'),
('PROSPECTION: Les salons professionnels locaux sont une mine d or: 1 salon = 100-200 contacts qualifies en 1 journee.', 'Salon pro local = 100-200 contacts/jour', 'commercial', 'insight', 0.82, 'massive_boost_8', 'system'),
('PROSPECTION: Le warm intro (etre presente par un contact commun) convertit 5x mieux que le cold outreach.', 'Warm intro = 5x conversion vs cold', 'commercial', 'best_practice', 0.92, 'massive_boost_8', 'system'),
('PROSPECTION: Le script d appel ideal: 1. Qui je suis (5s) 2. Pourquoi j appelle (10s) 3. Question ouverte (attendre).', 'Script appel: qui + pourquoi + question ouverte', 'commercial', 'best_practice', 0.88, 'massive_boost_8', 'system'),
-- ═══ EMAIL SEQUENCES AVANCEES (30) ═══
('EMAIL SEQ: La sequence de bienvenue ideale: J0 bienvenue + J1 premiere action + J3 cas client + J7 offre + J14 feedback.', 'Sequence bienvenue 5 emails', 'email', 'best_practice', 0.92, 'massive_boost_8', 'system'),
('EMAIL SEQ: L email de reactivation (prospect inactif 30j) avec "On vous a manque?" a un taux de reouverture de 12%.', 'Reactivation 30j = 12% reouverture', 'email', 'best_practice', 0.85, 'massive_boost_8', 'system'),
('EMAIL SEQ: L email de winback (ancien client parti) avec une offre speciale reconvertit 10-15% des anciens clients.', 'Winback ancien client = 10-15% reconversion', 'email', 'best_practice', 0.85, 'massive_boost_8', 'system'),
('EMAIL SEQ: Le drip campaign educatif (1 email/semaine pendant 4 semaines) positionne comme expert et genere 3x plus de leads.', 'Drip educatif 4 semaines = 3x leads', 'email', 'best_practice', 0.88, 'massive_boost_8', 'system'),
('EMAIL SEQ: L email de referral ("Partagez avec un ami, gagnez 1 mois gratuit") a un taux d action de 5-8%.', 'Referral email = 5-8% action', 'email', 'best_practice', 0.82, 'massive_boost_8', 'system'),
('EMAIL SEQ: L email de milestone ("Bravo, vous avez atteint 100 posts!") reduit le churn de 25%.', 'Milestone email = -25% churn', 'email', 'best_practice', 0.88, 'massive_boost_8', 'system'),
('EMAIL SEQ: La newsletter mensuelle avec les resultats du client (stats, progres) a un taux d ouverture de 45%.', 'Newsletter resultats client = 45% OR', 'email', 'best_practice', 0.88, 'massive_boost_8', 'system'),
('EMAIL SEQ: L email de teasing pre-lancement (countdown, sneak peek) genere 30% plus de ventes que le lancement sans teasing.', 'Teasing pre-lancement = +30% ventes', 'email', 'insight', 0.85, 'massive_boost_8', 'system'),
('EMAIL SEQ: L email du dimanche soir "Preparez votre semaine avec X" a un taux d ouverture de 28% (preparation lundi).', 'Email dimanche soir = 28% OR', 'email', 'insight', 0.80, 'massive_boost_8', 'system'),
('EMAIL SEQ: Le subject line test: envoyer 3 variantes a 10% de la liste chacune, attendre 2h, envoyer la gagnante au reste.', 'AB test sujet: 3 variantes × 10% → gagnante', 'email', 'best_practice', 0.90, 'massive_boost_8', 'system'),
-- ═══ INSTAGRAM AVANCE (30) ═══
('INSTAGRAM: L algorithme IG 2026 priorise: 1. Saves 2. Shares 3. Comments 4. Likes. Creer du contenu saveable.', 'Algo IG 2026: saves > shares > comments > likes', 'content', 'best_practice', 0.92, 'massive_boost_8', 'system'),
('INSTAGRAM: Les Guides Instagram (collections thematiques) boostent le SEO interne IG et le temps passe sur le profil.', 'Guides IG = SEO interne + temps profil', 'content', 'insight', 0.82, 'massive_boost_8', 'system'),
('INSTAGRAM: Le Close Friends pour du contenu exclusif cree un sentiment de VIP et augmente l engagement de 5x.', 'Close Friends IG = 5x engagement', 'content', 'insight', 0.85, 'massive_boost_8', 'system'),
('INSTAGRAM: Les Lives IG qui annoncent un sujet precis ("Comment doubler vos reservations") attirent 3x plus de viewers.', 'Live IG sujet annonce = 3x viewers', 'content', 'best_practice', 0.85, 'massive_boost_8', 'system'),
('INSTAGRAM: La bio IG parfaite: 1. Qui vous etes 2. Ce que vous faites 3. Pour qui 4. CTA + lien. Max 150 caracteres.', 'Bio IG: qui + quoi + pour qui + CTA en 150 chars', 'content', 'best_practice', 0.92, 'massive_boost_8', 'system'),
('INSTAGRAM: Les highlights stories organises par theme (menu, avis, equipe, FAQ) convertissent les visiteurs du profil en followers.', 'Highlights stories thematiques = conversion profil', 'content', 'best_practice', 0.88, 'massive_boost_8', 'system'),
('INSTAGRAM: L heure d or apres publication (engagement dans les 30min) determine la portee finale. Interagir immediatement.', 'Heure d or IG: 30min post-publi = portee', 'content', 'best_practice', 0.90, 'massive_boost_8', 'system'),
('INSTAGRAM: Le ratio feed/stories/reels ideal: 3 posts feed + 5 stories + 3 reels par semaine minimum.', 'Ratio IG: 3 feed + 5 stories + 3 reels/semaine', 'content', 'best_practice', 0.85, 'massive_boost_8', 'system'),
('INSTAGRAM: L engagement pod (groupe d entraide pour liker/commenter) fonctionne a court terme mais nuit a l algo a long terme.', 'Engagement pod: court terme ok, long terme nuit', 'content', 'insight', 0.82, 'massive_boost_8', 'system'),
('INSTAGRAM: Les Reels avec trending audio + contenu educatif = la formule magique pour la croissance organique en 2026.', 'Reels trending audio + educatif = croissance', 'content', 'best_practice', 0.90, 'massive_boost_8', 'system'),
-- ═══ LINKEDIN AVANCE (30) ═══
('LINKEDIN: Les posts entre 1200-1500 caracteres performent le mieux. Ni trop court ni trop long.', 'LinkedIn: 1200-1500 chars optimal', 'content', 'best_practice', 0.85, 'massive_boost_8', 'system'),
('LINKEDIN: Commencer par une accroche choc sur la premiere ligne (visible avant le "voir plus") = +40% engagement.', 'LinkedIn: accroche premiere ligne = +40% engagement', 'content', 'best_practice', 0.90, 'massive_boost_8', 'system'),
('LINKEDIN: Les posts personnels (echec, lecon apprise, parcours) performent 3x mieux que les posts corporate.', 'LinkedIn personnel > corporate: 3x', 'content', 'insight', 0.88, 'massive_boost_8', 'system'),
('LINKEDIN: Poster le mardi et jeudi entre 8h-10h genere le plus d impressions pour les audiences B2B.', 'LinkedIn: mardi-jeudi 8h-10h B2B', 'content', 'best_practice', 0.85, 'massive_boost_8', 'system'),
('LINKEDIN: Le document PDF natif (carousel LinkedIn) a 3x plus d engagement qu un post texte + image.', 'Document PDF LinkedIn = 3x engagement', 'content', 'best_practice', 0.88, 'massive_boost_8', 'system'),
('LINKEDIN: Commenter 10 posts pertinents par jour augmente la visibilite du profil de 200% en 30 jours.', 'Commenter 10/jour LinkedIn = +200% visibilite/mois', 'content', 'best_practice', 0.85, 'massive_boost_8', 'system'),
('LINKEDIN: Les articles LinkedIn (format long) sont indexes par Google = SEO gratuit pour le personal branding.', 'Articles LinkedIn = SEO Google gratuit', 'content', 'insight', 0.82, 'massive_boost_8', 'system'),
('LINKEDIN: Le SSI (Social Selling Index) > 70 = top 10% des utilisateurs LinkedIn. Mesurable gratuitement.', 'SSI LinkedIn > 70 = top 10%', 'content', 'insight', 0.80, 'massive_boost_8', 'system'),
('LINKEDIN: Les polls (sondages) LinkedIn generent 10x plus de commentaires que les posts classiques.', 'Polls LinkedIn = 10x commentaires', 'content', 'insight', 0.85, 'massive_boost_8', 'system'),
('LINKEDIN: Le "Creator Mode" augmente la visibilite du profil de 35% et donne acces aux newsletters.', 'Creator Mode LinkedIn = +35% visibilite', 'content', 'insight', 0.82, 'massive_boost_8', 'system'),
-- ═══ NEGOCIATION / CLOSING (20) ═══
('CLOSING: La technique du silence: apres avoir annonce le prix, se taire. Le premier qui parle perd. Attendre 5-10 secondes.', 'Technique silence apres prix: 5-10s', 'commercial', 'best_practice', 0.85, 'massive_boost_8', 'system'),
('CLOSING: Le choix assume: "Vous preferez commencer lundi ou mercredi?" presuppose que le prospect va acheter.', 'Choix assume: lundi ou mercredi = presuppose achat', 'commercial', 'best_practice', 0.82, 'massive_boost_8', 'system'),
('CLOSING: L inversion du risque: "Si ca ne vous convient pas, on vous rembourse integralement" elimine la peur.', 'Inversion risque: remboursement = elimine peur', 'commercial', 'best_practice', 0.90, 'massive_boost_8', 'system'),
('CLOSING: Le recapitulatif des benefices juste avant le prix: "Donc vous aurez X, Y et Z... pour seulement N€/mois".', 'Recap benefices avant prix', 'commercial', 'best_practice', 0.88, 'massive_boost_8', 'system'),
('CLOSING: Le downsell: si le prospect refuse l offre principale, proposer une version light. 30% acceptent le downsell.', 'Downsell: 30% acceptent version light', 'commercial', 'best_practice', 0.85, 'massive_boost_8', 'system'),
-- ═══ GOOGLE ADS LOCAL (20) ═══
('GOOGLE ADS: Les annonces avec extensions de lieu augmentent les visites en magasin de 20%.', 'Extensions lieu Google Ads = +20% visites', 'ads', 'best_practice', 0.88, 'massive_boost_8', 'system'),
('GOOGLE ADS: Le budget minimum pour que Google optimise correctement: 20€/jour pour le local, 50€/jour pour le national.', 'Budget min Google Ads: 20€/j local, 50€/j national', 'ads', 'best_practice', 0.85, 'massive_boost_8', 'system'),
('GOOGLE ADS: Les mots-cles "pres de moi" (restaurant pres de moi) ont un taux de conversion 3x superieur aux generiques.', 'Mots-cles pres de moi = 3x conversion', 'ads', 'best_practice', 0.90, 'massive_boost_8', 'system'),
('GOOGLE ADS: Le Quality Score > 7 reduit le CPC de 30%. Optimiser: pertinence annonce + landing page + CTR attendu.', 'Quality Score > 7 = -30% CPC', 'ads', 'best_practice', 0.90, 'massive_boost_8', 'system'),
('GOOGLE ADS: Les Performance Max combinent Search + Display + YouTube + Maps. Ideal pour les commerces locaux avec peu de budget.', 'Performance Max Google = ideal local petit budget', 'ads', 'best_practice', 0.85, 'massive_boost_8', 'system'),
-- ═══ STRATEGIE PRIX / OFFRES (20) ═══
('PRICING: L offre en 3 etapes (Starter/Pro/Premium) avec le milieu mis en valeur = 70% choisissent le milieu.', 'Offre 3 niveaux: 70% milieu', NULL, 'best_practice', 0.92, 'massive_boost_8', 'system'),
('PRICING: La reduction en % est plus attractive < 100€ ("30% de reduction"). En valeur absolue au-dessus ("50€ de reduction").', 'Reduction: % si < 100€, € si > 100€', NULL, 'insight', 0.85, 'massive_boost_8', 'system'),
('PRICING: L offre groupee (bundle) augmente la valeur percue de 40%. "3 pour le prix de 2" reste irresistible.', 'Bundle = +40% valeur percue', NULL, 'insight', 0.85, 'massive_boost_8', 'system'),
('PRICING: Le prix rond (50€) est percu comme "premium". Le prix precis (49.97€) est percu comme "bonne affaire".', 'Prix rond = premium, precis = bonne affaire', NULL, 'insight', 0.82, 'massive_boost_8', 'system'),
('PRICING: L offre Early Bird (prix reduit pour les premiers) genere 40% des ventes totales dans les 48 premieres heures.', 'Early Bird = 40% ventes en 48h', NULL, 'insight', 0.82, 'massive_boost_8', 'system')
ON CONFLICT DO NOTHING;
