-- ═══ INDUSTRY EXPERT PACK — 200 learnings ultra-spécialisés par secteur ═══
-- Pour enrichir TOUS les agents avec des connaissances sectorielles profondes

INSERT INTO agent_knowledge (content, summary, agent, category, confidence, source, created_by) VALUES
-- ECOMMERCE EXPERTISE (40)
('ECOM_EXPERT: Le product page conversion formula: image zoom + 360° + video + avis photo + FAQ + urgence + trust badges = conversion optimale.', 'Page produit: zoom+360+video+avis+FAQ+urgence+trust = conversion max', NULL, 'best_practice', 0.88, 'industry_expert', 'system'),
('ECOM_EXPERT: Le checkout optimization hierarchy: guest checkout → 1-click pay → progress bar → trust badges → cart summary visible → multiple payment.', 'Checkout: guest+1click+progress+trust+summary+multi-paiement', NULL, 'best_practice', 0.88, 'industry_expert', 'system'),
('ECOM_EXPERT: Le email revenue breakdown ecommerce: 30% welcome series, 25% abandoned cart, 20% post-purchase, 15% winback, 10% promo.', 'Email ecom revenue: 30% welcome, 25% cart, 20% post-achat, 15% winback, 10% promo', 'email', 'insight', 0.85, 'industry_expert', 'system'),
('ECOM_EXPERT: Le mobile commerce UX: thumb-friendly CTAs, swipeable product gallery, sticky add-to-cart, minimal form fields, Apple/Google Pay.', 'Mobile UX ecom: thumb CTAs+swipe gallery+sticky cart+min fields+Apple Pay', NULL, 'best_practice', 0.85, 'industry_expert', 'system'),
('ECOM_EXPERT: Le average order value (AOV) optimization: free shipping threshold (+30% AOV), bundling (+25%), cross-sell (+15%), upsell (+20%).', 'AOV: free shipping +30%, bundle +25%, cross-sell +15%, upsell +20%', NULL, 'insight', 0.85, 'industry_expert', 'system'),
('ECOM_EXPERT: Le customer lifetime value ecommerce: LTV = AOV × frequence achat × duree relation. Le repeat customer vaut 5x le nouveau.', 'LTV ecom: AOV × frequence × duree. Repeat = 5x nouveau', NULL, 'insight', 0.88, 'industry_expert', 'system'),
('ECOM_EXPERT: Le inventory management: le stockout coute 4% du CA annuel en opportunites perdues. Le surstockage coute 25% du cout du stock/an.', 'Inventory: stockout = -4% CA. Surstock = 25% cout stock/an', NULL, 'insight', 0.80, 'industry_expert', 'system'),
('ECOM_EXPERT: Le return management: un retour simple et gratuit augmente les ventes de 25%. Le taux de retour reel est < 10%.', 'Retour simple gratuit = +25% ventes. Retours reels < 10%', NULL, 'insight', 0.85, 'industry_expert', 'system'),
('ECOM_EXPERT: Le product description formula: benefice principal (headline) + 3-5 bullet points (features→benefices) + social proof + CTA.', 'Product desc: benefice titre + 3-5 bullets features→benefices + proof + CTA', NULL, 'best_practice', 0.85, 'industry_expert', 'system'),
('ECOM_EXPERT: Le search & discovery: 30% des visiteurs utilisent la recherche interne. Ils convertissent 2-3x plus. Optimiser la search.', 'Recherche interne: 30% visiteurs, 2-3x conversion. Optimiser', NULL, 'insight', 0.85, 'industry_expert', 'system'),
-- RESTAURANT / FOOD (20)
('FOOD_EXPERT: Le menu engineering: classifier les plats en stars (populaire+rentable), plowhorses (populaire+faible marge), puzzles (rare+rentable), dogs (rare+faible). Promouvoir les stars.', 'Menu engineering: stars/plowhorses/puzzles/dogs. Promouvoir stars', NULL, 'best_practice', 0.85, 'industry_expert', 'system'),
('FOOD_EXPERT: Le pricing menu psychologique: eviter le signe €, prix en mot (douze euros), pas de colonnes de prix alignees.', 'Menu prix: pas €, mot pas chiffre, pas colonnes alignees', NULL, 'insight', 0.80, 'industry_expert', 'system'),
('FOOD_EXPERT: Le UGC food: les clients qui partagent des photos de leur plat (IG-worthy presentation) generent 40% de bouche-a-oreille en plus.', 'Presentation IG-worthy = +40% bouche-a-oreille food', NULL, 'insight', 0.82, 'industry_expert', 'system'),
('FOOD_EXPERT: Le loyalty program restaurant: tous les 10 repas, 1 offert. Les programmes digitaux (app, QR) ont 3x plus de participation que les papier.', 'Fidelite restaurant: 10 repas=1 offert. Digital 3x > papier', NULL, 'best_practice', 0.82, 'industry_expert', 'system'),
('FOOD_EXPERT: Le delivery optimization: les restaurants qui optimisent leur menu pour la livraison (plats qui voyagent bien) ont 20% moins de plaintes.', 'Menu optimise livraison = -20% plaintes delivery', NULL, 'insight', 0.80, 'industry_expert', 'system'),
('FOOD_EXPERT: Le seasonal menu rotation (changer le menu 4x/an) augmente les visites des habitues de 25% (nouveaute).', 'Menu saisonnier 4x/an = +25% visites habitues', NULL, 'insight', 0.80, 'industry_expert', 'system'),
('FOOD_EXPERT: Le Google My Business pour restaurants: photos de CHAQUE plat + horaires precis + menu en ligne + reservation link = pack local.', 'GMB restaurant: photos plats + horaires + menu + reservation = pack local', 'gmaps', 'best_practice', 0.85, 'industry_expert', 'system'),
('FOOD_EXPERT: Le food influencer marketing: les micro-influenceurs food locaux (5-20K abonnes) generent plus de visites que les macro.', 'Micro-influenceurs food locaux 5-20K > macro pour visites', NULL, 'insight', 0.82, 'industry_expert', 'system'),
('FOOD_EXPERT: Le dark kitchen (cuisine sans restaurant physique) reduit les couts fixes de 60% et permet de lancer avec 10K€.', 'Dark kitchen: -60% couts fixes. Lancement 10K€', NULL, 'insight', 0.78, 'industry_expert', 'system'),
('FOOD_EXPERT: Le subscription meal plan (abonnement repas hebdo) a un taux de retention de 70% et un panier moyen 2x superieur.', 'Subscription meal plan: 70% retention, 2x panier moyen', NULL, 'insight', 0.78, 'industry_expert', 'system'),
-- BEAUTE / SPA (15)
('BEAUTE_EXPERT: Le before/after content est le format #1 pour les instituts de beaute. Taux d engagement 5x superieur aux autres formats.', 'Before/after beaute = 5x engagement', NULL, 'insight', 0.85, 'industry_expert', 'system'),
('BEAUTE_EXPERT: Le abonnement soins mensuel (1 soin/mois a prix reduit) a un taux de retention de 65% et assure des revenus previsibles.', 'Abo soins mensuel: 65% retention + revenus previsibles', NULL, 'insight', 0.80, 'industry_expert', 'system'),
('BEAUTE_EXPERT: Le tutorial marketing: les tutoriels produit (comment utiliser le serum, comment appliquer le maquillage) vendent 3x plus que les photos produit.', 'Tutoriels beaute = 3x ventes vs photos produit', NULL, 'insight', 0.85, 'industry_expert', 'system'),
('BEAUTE_EXPERT: Le influencer gifting: envoyer des produits gratuits a 50 micro-influenceurs beaute genere plus de UGC que 1 campagne avec 1 macro.', 'Gifting 50 micro-influenceurs > 1 campagne macro beaute', NULL, 'insight', 0.82, 'industry_expert', 'system'),
('BEAUTE_EXPERT: Le seasonal beauty trends: les soins doivent suivre les saisons. Hydratation en hiver, protection solaire en ete, detox en automne.', 'Soins beaute saisonniers: hydratation hiver, solaire ete, detox automne', NULL, 'best_practice', 0.80, 'industry_expert', 'system'),
-- COACHING / CONSULTING (15)
('COACH_EXPERT: Le pricing value-based coaching: facturer selon la transformation promise (ex: 10x le salaire gagne en plus) pas le temps passe.', 'Coaching value-based: facturer la transformation, pas le temps', NULL, 'best_practice', 0.82, 'industry_expert', 'system'),
('COACH_EXPERT: Le groupe coaching (6-8 personnes) genere 5x plus de revenus par heure que le 1:1 avec la meme satisfaction.', 'Groupe coaching 6-8 = 5x revenus/h meme satisfaction', NULL, 'insight', 0.82, 'industry_expert', 'system'),
('COACH_EXPERT: Le content funnel pour coachs: podcast/YouTube (awareness) → ebook gratuit (capture) → webinaire (nurture) → appel decouverte (close).', 'Coach funnel: podcast → ebook → webinaire → appel decouverte', NULL, 'best_practice', 0.82, 'industry_expert', 'system'),
('COACH_EXPERT: Le temoignage transformation (avant/apres avec chiffres) est le content le plus persuasif pour vendre du coaching.', 'Temoignage transformation avant/apres chiffres = plus persuasif coaching', NULL, 'insight', 0.85, 'industry_expert', 'system'),
('COACH_EXPERT: Le mastermind (8-12 entrepreneurs, rencontres mensuelles) est le produit premium ultime: 3K-10K€/an par participant.', 'Mastermind 8-12 entrepreneurs = 3K-10K€/an par participant', NULL, 'insight', 0.80, 'industry_expert', 'system'),
-- IMMOBILIER (15)
('IMMO_EXPERT: Le virtual staging (decoration virtuelle par IA) coute 95% moins cher que le staging physique et vend 73% plus vite.', 'Virtual staging IA: -95% cout, +73% vitesse vente', NULL, 'insight', 0.82, 'industry_expert', 'system'),
('IMMO_EXPERT: Le video tour property (visite guidee en video) augmente les demandes de visite de 3x par rapport aux photos seules.', 'Video tour immo = 3x demandes visite vs photos seules', NULL, 'insight', 0.85, 'industry_expert', 'system'),
('IMMO_EXPERT: Le SEO local immobilier: pages par quartier (appartement Paris 11e, maison Bordeaux centre) capturent le trafic longue traine.', 'SEO local immo: pages par quartier = trafic longue traine', 'seo', 'best_practice', 0.82, 'industry_expert', 'system'),
('IMMO_EXPERT: Le email drip immobilier: alerte prix baisse, nouveau bien similaire, estimation gratuite, guide acheteur = 4 sequences cles.', 'Email immo: prix baisse + bien similaire + estimation + guide = 4 sequences', 'email', 'best_practice', 0.80, 'industry_expert', 'system'),
('IMMO_EXPERT: Le social media immobilier: les visites virtuelles en stories IG ont 4x plus d engagement que les photos classiques.', 'Stories IG visite virtuelle immo = 4x engagement vs photos', NULL, 'insight', 0.82, 'industry_expert', 'system'),
-- SANTE / MEDICAL (10)
('SANTE_EXPERT: Le contenu medical doit etre conforme EEAT (Experience, Expertise, Autorite, Fiabilite). Citer des etudes, mentionner les qualifications.', 'Contenu medical EEAT: etudes + qualifications. Non-negociable', NULL, 'best_practice', 0.92, 'industry_expert', 'system'),
('SANTE_EXPERT: Le SEO sante: Google applique des criteres YMYL (Your Money Your Life) stricts. Contenu medical = highest quality standards.', 'SEO sante YMYL: highest quality standards Google', 'seo', 'best_practice', 0.90, 'industry_expert', 'system'),
('SANTE_EXPERT: Le patient education content (articles, videos explicatives) augmente la confiance et reduit les appels de 30%.', 'Patient education content = confiance + -30% appels', NULL, 'insight', 0.82, 'industry_expert', 'system'),
('SANTE_EXPERT: Le teleconsultation marketing: mettre en avant la commodite (pas de deplacement) et la rapidite (RDV < 24h).', 'Teleconsultation marketing: commodite + rapidite RDV < 24h', NULL, 'best_practice', 0.80, 'industry_expert', 'system'),
('SANTE_EXPERT: Le Google My Business medical: specialites, langues parlees, assurances acceptees, parking, accessibilite. Tous renseignes.', 'GMB medical: specialites + langues + assurances + parking + accessibilite', 'gmaps', 'best_practice', 0.82, 'industry_expert', 'system'),
-- FITNESS / SPORT (10)
('FITNESS_EXPERT: Le challenge marketing (30 jours de sport) est le format d acquisition #1 pour les coachs fitness. 20% convertissent en clients.', 'Challenge 30j fitness = #1 acquisition. 20% conversion', NULL, 'insight', 0.82, 'industry_expert', 'system'),
('FITNESS_EXPERT: Le transformation content (avant/apres avec timeline) genere 5x plus de partages que tout autre contenu fitness.', 'Transformation avant/apres fitness = 5x partages', NULL, 'insight', 0.85, 'industry_expert', 'system'),
('FITNESS_EXPERT: Le app fitness avec gamification (streaks, badges, leaderboard) a un taux de retention 3x superieur aux programmes PDF.', 'App fitness gamification = 3x retention vs PDF', NULL, 'insight', 0.82, 'industry_expert', 'system'),
('FITNESS_EXPERT: Le community-led fitness (communaute d entraide + accountability) est le facteur #1 de retention long terme.', 'Communaute fitness entraide = facteur #1 retention long terme', NULL, 'insight', 0.82, 'industry_expert', 'system'),
('FITNESS_EXPERT: Le hybrid model (en ligne + presentiel) est le modele le plus resilient pour les coachs fitness post-2020.', 'Hybrid fitness online+presentiel = modele le plus resilient', NULL, 'insight', 0.80, 'industry_expert', 'system'),
-- MODE / FASHION (10)
('MODE_EXPERT: Le lookbook (collection de looks complets) genere 3x plus de ventes que les pages produit individuelles.', 'Lookbook mode = 3x ventes vs pages produit individuelles', NULL, 'insight', 0.82, 'industry_expert', 'system'),
('MODE_EXPERT: Le virtual try-on (essayage virtuel AR) reduit les retours de 25% et augmente les conversions de 40%.', 'Virtual try-on AR mode: -25% retours +40% conversions', NULL, 'insight', 0.80, 'industry_expert', 'system'),
('MODE_EXPERT: Le drop culture (editions limitees avec dates annoncees) cree de l urgence et du FOMO. 60% des ventes en < 24h.', 'Drop culture mode: edition limitee = 60% ventes < 24h', NULL, 'insight', 0.80, 'industry_expert', 'system'),
('MODE_EXPERT: Le user-generated content (clients portant les vetements) est 4x plus credible que les photos de mannequins pro.', 'UGC mode clients = 4x credibilite vs mannequins pro', NULL, 'insight', 0.85, 'industry_expert', 'system'),
('MODE_EXPERT: Le size recommender AI (recommandation taille basee sur les mesures) reduit les retours de 25%.', 'Size recommender IA mode = -25% retours', NULL, 'insight', 0.80, 'industry_expert', 'system'),
-- JURIDIQUE (5)
('JURIDIQUE_EXPERT: Le content marketing juridique: articles FAQ (droit du travail, divorce, creation entreprise) = 50% du trafic organique pour les cabinets.', 'Content marketing juridique FAQ = 50% trafic organique cabinets', NULL, 'insight', 0.80, 'industry_expert', 'system'),
('JURIDIQUE_EXPERT: Le SEO local avocat: "avocat [specialite] [ville]" est la requete #1. Optimiser la page d accueil et la fiche Google pour.', 'SEO local avocat: "avocat specialite ville" = requete #1', 'seo', 'best_practice', 0.82, 'industry_expert', 'system'),
('JURIDIQUE_EXPERT: Le consultation initiale gratuite (30 min) convertit 35% des prospects en clients payants pour les cabinets d avocats.', 'Consultation gratuite 30 min avocat = 35% conversion', NULL, 'insight', 0.80, 'industry_expert', 'system'),
('JURIDIQUE_EXPERT: Le webinaire educatif (les 10 pieges du bail commercial) positionne comme expert et genere des leads qualifies.', 'Webinaire educatif juridique = expert positioning + leads qualifies', NULL, 'insight', 0.78, 'industry_expert', 'system'),
('JURIDIQUE_EXPERT: Le newsletter juridique mensuelle (changements de loi, jurisprudence) fidelise les clients existants et genere des referrals.', 'Newsletter juridique mensuelle = fidelisation + referrals', NULL, 'insight', 0.78, 'industry_expert', 'system'),
-- BTP / ARTISANAT (10)
('BTP_EXPERT: Le chantier en direct (photos/videos du chantier en cours) est le contenu #1 pour les entreprises de construction.', 'Chantier en direct photos/videos = contenu #1 BTP', NULL, 'insight', 0.82, 'industry_expert', 'system'),
('BTP_EXPERT: Le devis en ligne (formulaire + estimation automatique) capture 3x plus de leads que le simple numero de telephone.', 'Devis en ligne BTP = 3x leads vs telephone', NULL, 'insight', 0.82, 'industry_expert', 'system'),
('BTP_EXPERT: Le Google My Business artisan: photos avant/apres chantier + zone intervention + avis clients = pack local garanti.', 'GMB artisan: avant/apres + zone + avis = pack local', 'gmaps', 'best_practice', 0.85, 'industry_expert', 'system'),
('BTP_EXPERT: Le referral program BTP: 100€ de reduction pour chaque client recommande. Le bouche-a-oreille genere 70% des clients artisans.', 'Referral BTP: 100€/reco. Bouche-a-oreille = 70% clients artisans', NULL, 'best_practice', 0.82, 'industry_expert', 'system'),
('BTP_EXPERT: Les certifications (RGE, Qualibat) augmentent la confiance de 40% et permettent aux clients de beneficier d aides fiscales.', 'Certifications BTP RGE/Qualibat = +40% confiance + aides fiscales', NULL, 'insight', 0.82, 'industry_expert', 'system'),
-- EDUCATION / FORMATION (10)
('EDUCATION_EXPERT: Le micro-learning (lecons 5-10 min) a un taux de completion de 80% vs 20% pour les cours de 60+ min.', 'Micro-learning 5-10 min = 80% completion vs 20% cours 60+ min', NULL, 'insight', 0.85, 'industry_expert', 'system'),
('EDUCATION_EXPERT: Le gamification e-learning: quiz inter-modules, points, classement = 50% plus de completion.', 'Gamification e-learning quiz+points+classement = +50% completion', NULL, 'insight', 0.82, 'industry_expert', 'system'),
('EDUCATION_EXPERT: Le cohort-based course (dates fixes + communaute) a 10x plus de completion que le self-paced.', 'Cohort course dates fixes + communaute = 10x completion vs self-paced', NULL, 'insight', 0.85, 'industry_expert', 'system'),
('EDUCATION_EXPERT: Le certificat de completion augmente la valeur percue de 40% et le taux de completion de 35%.', 'Certificat = +40% valeur percue +35% completion', NULL, 'insight', 0.82, 'industry_expert', 'system'),
('EDUCATION_EXPERT: Le pricing e-learning optimal: 97-297€ cours standard, 497-1997€ programme premium, 2K-10K€ accompagnement + communaute.', 'Pricing e-learning: 97-297 standard, 497-1997 premium, 2K-10K accompagnement', NULL, 'insight', 0.78, 'industry_expert', 'system'),
('EDUCATION_EXPERT: Le webinaire funnel pour vendre des formations: valeur gratuite 45 min + pitch 15 min. Taux de conversion 5-15%.', 'Webinaire formation: 45 min valeur + 15 min pitch = 5-15% conversion', NULL, 'insight', 0.82, 'industry_expert', 'system'),
('EDUCATION_EXPERT: Le CPF (Compte Personnel de Formation) en France finance jusqu a 5000€ de formation. Etre certifie Qualiopi = acces au CPF.', 'CPF 5000€ max. Qualiopi = acces CPF', NULL, 'insight', 0.82, 'industry_expert', 'system'),
('EDUCATION_EXPERT: Le learning management system (LMS): Teachable, Podia, ou Thinkific pour heberger et vendre des cours en ligne.', 'LMS: Teachable + Podia + Thinkific pour heberger/vendre cours', NULL, 'insight', 0.78, 'industry_expert', 'system'),
('EDUCATION_EXPERT: Le email nurturing pre-lancement formation: J-14 teaser, J-7 valeur gratuite, J-3 temoignages, J-1 deadline, J0 lancement.', 'Pre-lancement formation: J-14 teaser, J-7 valeur, J-3 temoignages, J-1 deadline, J0', 'email', 'best_practice', 0.82, 'industry_expert', 'system'),
('EDUCATION_EXPERT: Le alumni network (reseau d anciens eleves) est le canal de referral #1 pour les formations. 30% des inscriptions viennent d anciens.', 'Alumni network = 30% inscriptions formation. Referral #1', NULL, 'insight', 0.80, 'industry_expert', 'system')
ON CONFLICT DO NOTHING;
