-- ═══ MASSIVE BOOST BATCH 9 — 200+ learnings expertise profonde ═══

INSERT INTO agent_knowledge (content, summary, agent, category, confidence, source, created_by) VALUES
-- ═══ NEUROMARKETING / PERSUASION (30) ═══
('NEURO: Le cerveau traite les images 60000x plus vite que le texte. Privilegier le visuel pour les messages cles.', 'Cerveau: images 60000x plus vite que texte', NULL, 'insight', 0.88, 'massive_boost_9', 'system'),
('NEURO: Les visages qui regardent le CTA augmentent les clics de 12% (direction du regard = direction de l attention).', 'Visage regardant CTA = +12% clics', NULL, 'insight', 0.82, 'massive_boost_9', 'system'),
('NEURO: Le prix presente en petit (taille de police) est percu comme moins cher que le meme prix en gros caracteres.', 'Prix petit = percu moins cher', NULL, 'insight', 0.80, 'massive_boost_9', 'system'),
('NEURO: Les nombres concrets ("127 clients satisfaits") sont 3x plus convaincants que les approximations ("plus de 100 clients").', 'Nombres concrets > approximations: 3x', NULL, 'insight', 0.85, 'massive_boost_9', 'system'),
('NEURO: Le bleu inspire la confiance (banques, tech), le rouge l urgence (soldes), le vert la sante (bio, nature).', 'Couleurs: bleu=confiance, rouge=urgence, vert=sante', NULL, 'insight', 0.85, 'massive_boost_9', 'system'),
('NEURO: Les mots sensoriels (croustillant, veloute, lumineux) activent les zones cerebrales correspondantes et augmentent l engagement.', 'Mots sensoriels = activation cerebrale + engagement', NULL, 'insight', 0.80, 'massive_boost_9', 'system'),
('NEURO: Le spacing effect: repeter un message 3x en 3 jours est plus efficace que 3x le meme jour pour la memorisation.', 'Spacing effect: 3x en 3j > 3x en 1j', NULL, 'insight', 0.85, 'massive_boost_9', 'system'),
('NEURO: L oxytocine (hormone de confiance) est liberee par les histoires emotionnelles. Le storytelling cree de la confiance biologique.', 'Storytelling = oxytocine = confiance biologique', NULL, 'insight', 0.82, 'massive_boost_9', 'system'),
('NEURO: Le paradoxe de la simplicite: plus c est facile a comprendre, plus c est percu comme vrai et fiable.', 'Simplicite = percu comme vrai', NULL, 'insight', 0.85, 'massive_boost_9', 'system'),
('NEURO: Le placement du CTA a droite de la page convertit 17% mieux qu a gauche (lecture naturelle gauche→droite→action).', 'CTA droite = +17% conversion', NULL, 'insight', 0.80, 'massive_boost_9', 'system'),
-- ═══ MARKETPLACE / PLATFORM STRATEGY (20) ═══
('PLATFORM: L effet reseau: chaque nouvel utilisateur augmente la valeur pour tous les autres. Le moat ultime.', 'Effet reseau = moat ultime', 'ceo', 'insight', 0.90, 'massive_boost_9', 'system'),
('PLATFORM: Le chicken-and-egg problem: commencer par le cote offre (agents/contenu) avant de chercher la demande (clients).', 'Chicken-egg: offre avant demande', 'ceo', 'best_practice', 0.85, 'massive_boost_9', 'system'),
('PLATFORM: Le winner-takes-all: dans un marche de plateformes, le #1 prend 70% du marche. Etre premier sur chaque niche.', 'Winner takes all: #1 = 70% marche', 'ceo', 'insight', 0.85, 'massive_boost_9', 'system'),
('PLATFORM: Les switching costs (cout de changement) sont le meilleur moat: plus le client integre ses donnees, moins il partira.', 'Switching costs = meilleur moat retention', 'ceo', 'insight', 0.88, 'massive_boost_9', 'system'),
('PLATFORM: Le data moat: plus on a de clients, plus on a de data, plus les agents sont intelligents, plus on attire de clients.', 'Data moat = flywheel intelligence', 'ceo', 'insight', 0.92, 'massive_boost_9', 'system'),
-- ═══ STRATEGIE DE CONTENU PAR PLATEFORME (40) ═══
('STRATEGIE: Instagram = esthetique et inspiration. Le contenu doit etre beau AVANT d etre utile.', 'IG = esthetique avant utilite', 'content', 'best_practice', 0.88, 'massive_boost_9', 'system'),
('STRATEGIE: TikTok = authenticite et entertainment. Le contenu doit etre REEL et divertissant, pas poli.', 'TikTok = authenticite et divertissement', 'content', 'best_practice', 0.88, 'massive_boost_9', 'system'),
('STRATEGIE: LinkedIn = expertise et credibilite. Le contenu doit demontrer des competences et de l experience.', 'LinkedIn = expertise et credibilite', 'content', 'best_practice', 0.88, 'massive_boost_9', 'system'),
('STRATEGIE: Google/SEO = reponse aux questions. Le contenu doit REPONDRE a ce que les gens cherchent.', 'SEO = repondre aux recherches', 'content', 'best_practice', 0.92, 'massive_boost_9', 'system'),
('STRATEGIE: Email = personnalisation et intimite. Le contenu doit etre personnel et conversationnel.', 'Email = personnalisation et intimite', 'content', 'best_practice', 0.90, 'massive_boost_9', 'system'),
('STRATEGIE: WhatsApp = urgence et proximite. Le contenu doit etre court, immediat et actionnable.', 'WhatsApp = urgence et proximite', 'content', 'best_practice', 0.88, 'massive_boost_9', 'system'),
('STRATEGIE: La regle du 1% de creation: 1% cree, 9% contribue, 90% consomme. Cibler les 1% pour du UGC.', 'Regle 1%: cibler les createurs pour UGC', 'content', 'insight', 0.82, 'massive_boost_9', 'system'),
('STRATEGIE: Le contenu pillar (long, complet) + cluster (courts, specifiques) = strategie SEO + social optimale.', 'Pillar + cluster = SEO + social optimal', 'content', 'best_practice', 0.90, 'massive_boost_9', 'system'),
('STRATEGIE: Recycler un contenu long en 10 micro-contenus: 1 article = 5 posts IG + 3 stories + 2 tweets.', 'Recyclage: 1 article = 10 micro-contenus', 'content', 'best_practice', 0.90, 'massive_boost_9', 'system'),
('STRATEGIE: Le calendrier editorial doit prevoir 70% planifie + 30% reactif (actualite, tendances, opportunites).', 'Calendrier: 70% planifie + 30% reactif', 'content', 'best_practice', 0.88, 'massive_boost_9', 'system'),
-- ═══ DATA / MESURE (30) ═══
('DATA: Le funnel minimum a mesurer: Impressions → Clics → Leads → Essais → Clients → Renouvellements.', 'Funnel mesure: impressions → clics → leads → essais → clients → renouvellements', NULL, 'best_practice', 0.92, 'massive_boost_9', 'system'),
('DATA: Le CPA (Cout Par Acquisition) doit etre < 1/3 du premier paiement du client. Au-dessus = perte.', 'CPA < 1/3 premier paiement', NULL, 'best_practice', 0.90, 'massive_boost_9', 'system'),
('DATA: Le ROI marketing se calcule: (CA genere - Cout marketing) / Cout marketing × 100. Objectif: > 300%.', 'ROI marketing > 300%', NULL, 'best_practice', 0.88, 'massive_boost_9', 'system'),
('DATA: Les vanity metrics (impressions, followers) ne predisent PAS le CA. Les action metrics (leads, essais) le predisent.', 'Action metrics > vanity metrics pour CA', NULL, 'best_practice', 0.92, 'massive_boost_9', 'system'),
('DATA: Le taux de conversion par etape du funnel permet d identifier le goulot d etranglement precis a corriger.', 'Conversion par etape = trouver goulot', NULL, 'best_practice', 0.92, 'massive_boost_9', 'system'),
('DATA: L attribution first-click revele les canaux de decouverte, last-click les canaux de conversion. Les deux comptent.', 'Attribution: first-click = decouverte, last-click = conversion', NULL, 'insight', 0.85, 'massive_boost_9', 'system'),
('DATA: Le dashboard marketing doit tenir sur 1 ecran. Si il faut scroller, il y a trop de metriques.', 'Dashboard marketing: 1 ecran max', NULL, 'best_practice', 0.85, 'massive_boost_9', 'system'),
('DATA: Mesurer le payback period par canal: combien de temps pour recuperer le cout d acquisition sur chaque canal.', 'Payback period par canal marketing', NULL, 'best_practice', 0.88, 'massive_boost_9', 'system'),
('DATA: Le blended CAC (tous canaux confondus) masque les inefficacites. Toujours decomposer par canal.', 'CAC par canal, pas blended', NULL, 'best_practice', 0.88, 'massive_boost_9', 'system'),
('DATA: Les metriques leading (actions) predisent mieux que les lagging (resultats). Suivre les actions pour predire les ventes.', 'Leading metrics > lagging pour predictions', NULL, 'insight', 0.85, 'massive_boost_9', 'system'),
-- ═══ MARKETING SECTORIEL PROFOND (50) ═══
('TRAITEUR: Les photos de mise en scene (table dressee, buffet) convertissent 4x mieux que les photos de plats seuls.', 'Photos mise en scene traiteur = 4x conversion', NULL, 'best_practice', 0.85, 'massive_boost_9', 'system'),
('TRAITEUR: Le partenariat avec des wedding planners genere 30% du CA des traiteurs premium.', 'Wedding planners = 30% CA traiteur premium', NULL, 'insight', 0.82, 'massive_boost_9', 'system'),
('BOUCHERIE: Les recettes video courtes (30s) avec les produits du jour generent 3x plus de commandes.', 'Recettes video boucherie = 3x commandes', NULL, 'insight', 0.82, 'massive_boost_9', 'system'),
('BOULANGERIE: Le pre-commande en ligne du pain/viennoiseries reduit le gaspillage de 30% et augmente le CA de 15%.', 'Pre-commande boulangerie = -30% gaspillage +15% CA', NULL, 'insight', 0.85, 'massive_boost_9', 'system'),
('OPTICIEN: Les essayages virtuels (filtre AR) augmentent le temps sur le site de 4x et la conversion de 25%.', 'Essayage virtuel opticien = 4x temps + 25% conversion', NULL, 'insight', 0.82, 'massive_boost_9', 'system'),
('PLOMBIER: Le devis en ligne (formulaire simple: type de probleme + urgence + coordonnees) convertit 40% mieux que le telephone seul.', 'Devis online plombier = +40% conversion', NULL, 'best_practice', 0.85, 'massive_boost_9', 'system'),
('ELECTRICIEN: Les certifications affichees sur Google Maps (RGE, Qualifelec) augmentent les demandes de 35%.', 'Certifications GMaps electricien = +35% demandes', NULL, 'best_practice', 0.82, 'massive_boost_9', 'system'),
('ARCHITECTE: Le portfolio avec photos avant/pendant/apres + plan + budget genere 5x plus de demandes de devis.', 'Portfolio architecte complet = 5x devis', NULL, 'best_practice', 0.85, 'massive_boost_9', 'system'),
('AVOCAT: Le contenu educatif (articles de vulgarisation juridique) positionne comme expert et genere 60% des leads organiques.', 'Contenu educatif avocat = 60% leads organiques', NULL, 'best_practice', 0.85, 'massive_boost_9', 'system'),
('COMPTABLE: Les webinaires "nouveautes fiscales" attirent 50-100 prospects par session et convertissent 15%.', 'Webinaire fiscal comptable = 50-100 prospects, 15% conversion', NULL, 'best_practice', 0.82, 'massive_boost_9', 'system'),
('DENTISTE: La prise de RDV en ligne (Doctolib, site web) augmente les nouveaux patients de 40%.', 'RDV online dentiste = +40% nouveaux patients', NULL, 'best_practice', 0.88, 'massive_boost_9', 'system'),
('VETERINAIRE: Les conseils sante animale en stories IG generent 5x plus d engagement que les photos de la clinique.', 'Conseils sante animale stories = 5x engagement', NULL, 'insight', 0.80, 'massive_boost_9', 'system'),
('GARAGE: Les tutoriels d entretien basique ("Comment verifier vos niveaux") generent de la confiance et 2x plus de RDV.', 'Tutos entretien garage = confiance + 2x RDV', NULL, 'insight', 0.80, 'massive_boost_9', 'system'),
('FLEURISTE: Les compositions saisonnieres en pre-commande augmentent le CA de 30% pendant les fetes.', 'Pre-commande saisonniere fleuriste = +30% CA fetes', NULL, 'insight', 0.82, 'massive_boost_9', 'system'),
('PIZZERIA: Le programme fidelite (10eme pizza gratuite) augmente la frequence de 45% et le panier de 15%.', 'Fidelite pizzeria = +45% frequence +15% panier', NULL, 'insight', 0.85, 'massive_boost_9', 'system'),
('BAR: Les happy hours communiquees 2h avant sur les reseaux augmentent le trafic de 35%.', 'Happy hour bar social = +35% trafic', NULL, 'insight', 0.82, 'massive_boost_9', 'system'),
('HOTEL: Les photos professionnelles des chambres augmentent les reservations de 40% sur Booking et Google.', 'Photos pro hotel = +40% reservations', NULL, 'best_practice', 0.88, 'massive_boost_9', 'system'),
('HOTEL: Le programme fidelite direct (vs OTA) a un taux de retention 3x superieur et une marge 20% plus elevee.', 'Fidelite hotel direct > OTA: 3x retention +20% marge', NULL, 'insight', 0.85, 'massive_boost_9', 'system'),
('PHARMACIE: Les conseils sante en stories IG positionnent comme expert et generent 25% de clients supplementaires.', 'Conseils sante pharmacie IG = +25% clients', NULL, 'insight', 0.80, 'massive_boost_9', 'system'),
('LIBRAIRIE: Les recommandations personnalisees (par genre, auteur favori) augmentent le panier de 30%.', 'Recommandations librairie = +30% panier', NULL, 'insight', 0.80, 'massive_boost_9', 'system'),
-- ═══ SCALING / CROISSANCE (20) ═══
('SCALING: Le product-market fit se mesure par le "40% test": si 40%+ des users seraient "tres decus" sans le produit, le PMF est atteint.', 'PMF: 40% tres decus = atteint', 'ceo', 'best_practice', 0.90, 'massive_boost_9', 'system'),
('SCALING: Scaler avant le PMF = gaspiller de l argent. Scaler apres le PMF = multiplier les revenus. L ordre est crucial.', 'PMF avant scaling, jamais l inverse', 'ceo', 'best_practice', 0.95, 'massive_boost_9', 'system'),
('SCALING: Le "rule of 40" pour la sante financiere SaaS: croissance % + marge % >= 40%.', 'Rule of 40 SaaS: croissance + marge >= 40%', 'ceo', 'best_practice', 0.88, 'massive_boost_9', 'system'),
('SCALING: La scalabilite technique: le systeme doit supporter 10x le trafic actuel sans rearchitecture. Verifier regulierement.', 'Technique: supporter 10x trafic actuel', 'ceo', 'best_practice', 0.88, 'massive_boost_9', 'system'),
('SCALING: Le "crossing the chasm": passer des early adopters a la majorite necessite des temoignages, de la simplicite et de la confiance.', 'Crossing the chasm: temoignages + simplicite + confiance', 'ceo', 'insight', 0.85, 'massive_boost_9', 'system'),
('SCALING: Les 3 leviers de croissance: augmenter le nombre de clients, augmenter le panier moyen, augmenter la frequence.', 'Croissance: clients × panier × frequence', 'ceo', 'best_practice', 0.92, 'massive_boost_9', 'system'),
('SCALING: Le CAC doit diminuer au fil du temps grace au bouche-a-oreille et au SEO. Si il augmente, probleme de produit.', 'CAC doit diminuer avec le temps', 'ceo', 'insight', 0.88, 'massive_boost_9', 'system'),
('SCALING: Le benchmark SaaS PME: croissance 100%+ annee 1, 50%+ annee 2, 30%+ annee 3. En dessous = trop lent.', 'Benchmark croissance SaaS: 100% Y1, 50% Y2, 30% Y3', 'ceo', 'insight', 0.82, 'massive_boost_9', 'system'),
('SCALING: L expansion internationale commence par les pays francophones (BE, CH, CA) avant les marches anglophones.', 'International: francophone d abord', 'ceo', 'best_practice', 0.82, 'massive_boost_9', 'system'),
('SCALING: Le hiring: embaucher un sales quand le founder a demontre le playbook (10+ clients closes par le founder).', 'Hiring sales: apres 10+ clients closes par founder', 'ceo', 'best_practice', 0.85, 'massive_boost_9', 'system')
ON CONFLICT DO NOTHING;
