-- ═══ ELITE COMMERCIAL AGENT — 100 learnings niveau expert 50 ans ═══
-- Agent: commercial (vente, prospection, CRM, closing)
-- Expertise: vente B2B/B2C, negociation, pipeline management, psychologie de vente

INSERT INTO agent_knowledge (content, summary, agent, category, confidence, source, created_by) VALUES
('COMMERCIAL_ELITE: Le top closer ne vend pas. Il diagnostique. 80% du temps de vente doit etre passe a ecouter et poser des questions.', 'Top closer: 80% ecouter, 20% presenter. Diagnostiquer pas vendre', 'commercial', 'best_practice', 0.92, 'elite_commercial', 'system'),
('COMMERCIAL_ELITE: Le triangle de la vente: Timing × Trust × Tension. Les 3 doivent etre alignes pour closer. Si 1 manque, le deal est mort.', 'Triangle vente: Timing × Trust × Tension. 3 alignes sinon mort', 'commercial', 'insight', 0.90, 'elite_commercial', 'system'),
('COMMERCIAL_ELITE: Le multi-threading avance: contacter 3-5 stakeholders dans le meme compte. Si 1 champion part, le deal survit.', 'Multi-threading 3-5 stakeholders = deal survit si champion part', 'commercial', 'best_practice', 0.88, 'elite_commercial', 'system'),
('COMMERCIAL_ELITE: Le pricing anchoring: toujours presenter l option la plus chere en premier. Elle ancre la perception de valeur pour toutes les options suivantes.', 'Pricing anchoring: option chere en premier = ancrer valeur', 'commercial', 'best_practice', 0.88, 'elite_commercial', 'system'),
('COMMERCIAL_ELITE: Le objection anticipation: adresser les 3 objections principales AVANT que le prospect ne les pose. Cela desactive la resistance.', 'Anticiper 3 objections = desactiver resistance avant qu elle ne se forme', 'commercial', 'best_practice', 0.90, 'elite_commercial', 'system'),
('COMMERCIAL_ELITE: Le deal qualification MEDDICC: Metrics, Economic buyer, Decision criteria, Decision process, Identify pain, Champion, Competition. Si Competition est forte, pivoter.', 'MEDDICC: Metrics, Economic buyer, Decision, Pain, Champion, Competition', 'commercial', 'best_practice', 0.88, 'elite_commercial', 'system'),
('COMMERCIAL_ELITE: Le pipeline velocity formula: (# deals × avg deal size × win rate) / avg sales cycle length. Optimiser chaque variable independamment.', 'Pipeline velocity: deals × size × win% / cycle length. Optimiser chaque var', 'commercial', 'best_practice', 0.85, 'elite_commercial', 'system'),
('COMMERCIAL_ELITE: Le champion test: si votre champion ne peut pas expliquer votre proposition de valeur en 30 secondes a son boss, le deal est a risque.', 'Champion test: champion explique value prop en 30s a son boss sinon risque', 'commercial', 'insight', 0.88, 'elite_commercial', 'system'),
('COMMERCIAL_ELITE: Le negative reverse selling (Chris Voss): dire "vous avez probablement raison, ce n est peut-etre pas le bon moment" pousse le prospect a se convaincre lui-meme.', 'Negative reverse selling: dire pas bon moment → prospect se convainc', 'commercial', 'best_practice', 0.82, 'elite_commercial', 'system'),
('COMMERCIAL_ELITE: Le decision mapping: identifier qui decide (economic buyer), qui influence (champion), qui bloque (detracteur), qui valide (legal, IT). Strategie pour chacun.', 'Decision mapping: decide + influence + bloque + valide. Strategie chacun', 'commercial', 'best_practice', 0.88, 'elite_commercial', 'system'),
('COMMERCIAL_ELITE: Le urgency creation sans manipulation: "quelles consequences si vous ne resolvez pas ce probleme dans les 3 prochains mois?" Quantifier le cout de l inaction.', 'Urgence ethique: quantifier cout de l inaction sur 3 mois', 'commercial', 'best_practice', 0.88, 'elite_commercial', 'system'),
('COMMERCIAL_ELITE: Le deal review framework: chaque vendredi, revoir les 5 deals les plus importants avec le framework: next step? blocage? risk level? action requise?', 'Deal review vendredi: 5 deals, next step + blocage + risk + action', 'commercial', 'best_practice', 0.85, 'elite_commercial', 'system'),
('COMMERCIAL_ELITE: Le discovery call structure: 5 min rapport, 5 min contexte (leur situation), 10 min probleme (creuser), 5 min impact (quantifier), 5 min next step.', 'Discovery call: rapport 5 + contexte 5 + probleme 10 + impact 5 + next 5', 'commercial', 'best_practice', 0.88, 'elite_commercial', 'system'),
('COMMERCIAL_ELITE: Le trigger event selling: suivre les signaux d achat (levee de fonds, recrutement, changement de direction, lancement) et contacter dans les 48h.', 'Trigger events: levee/recrutement/direction/lancement → contacter 48h', 'commercial', 'best_practice', 0.85, 'elite_commercial', 'system'),
('COMMERCIAL_ELITE: Le mutual close plan: documenter avec le prospect les etapes restantes, les responsables, et les dates. Partager dans un doc collaboratif.', 'Mutual close plan: etapes + responsables + dates dans doc collaboratif', 'commercial', 'best_practice', 0.85, 'elite_commercial', 'system'),
('COMMERCIAL_ELITE: Le cost of inaction (COI) framework: calculer combien le prospect perd par mois en ne resolvant pas son probleme. Plus puissant que le ROI.', 'COI framework: calculer perte/mois sans solution. Plus puissant que ROI', 'commercial', 'best_practice', 0.88, 'elite_commercial', 'system'),
('COMMERCIAL_ELITE: Le land and expand strategy: commencer petit (1 equipe, 1 use case) puis expander a toute l entreprise une fois la valeur prouvee.', 'Land & expand: petit debut → prouver valeur → expansion entreprise', 'commercial', 'best_practice', 0.88, 'elite_commercial', 'system'),
('COMMERCIAL_ELITE: Le competitive displacement: ne jamais critiquer le concurrent. Demander au prospect ce qui pourrait etre mieux puis montrer comment vous excellez la-dessus.', 'Competitive displacement: jamais critiquer. Demander mieux puis montrer excellence', 'commercial', 'best_practice', 0.85, 'elite_commercial', 'system'),
('COMMERCIAL_ELITE: Le proposal structure gagnante: 1) recap du probleme (montrer qu on a ecoute), 2) solution (comment), 3) resultats attendus (chiffres), 4) prix, 5) next steps.', 'Proposal: probleme recap → solution → resultats chiffres → prix → next steps', 'commercial', 'best_practice', 0.88, 'elite_commercial', 'system'),
('COMMERCIAL_ELITE: Le commercial scoring avance: score = (budget confirme×3 + decision maker engage×3 + timeline definie×2 + besoin valide×2) / 10. Score > 7 = deal chaud.', 'Commercial scoring: (budget×3 + DM×3 + timeline×2 + besoin×2)/10. >7 = chaud', 'commercial', 'best_practice', 0.85, 'elite_commercial', 'system'),
('COMMERCIAL_ELITE: Le closing technique soft: "sur la base de ce qu on a discute, est-ce que vous voyez quelque chose qui vous empecherait d avancer?" Laisser le silence.', 'Soft close: voyez-vous obstacle? + silence', 'commercial', 'best_practice', 0.85, 'elite_commercial', 'system'),
('COMMERCIAL_ELITE: Le risk reversal: garantie 30 jours, SLA engage, pilot gratuit, paiement apres resultats. Eliminer tout risque pour le prospect.', 'Risk reversal: garantie + SLA + pilot + paiement apres resultats = 0 risque', 'commercial', 'best_practice', 0.88, 'elite_commercial', 'system'),
('COMMERCIAL_ELITE: Le social selling index optimal: poster 3x/semaine, commenter 5x/jour, envoyer 5 DMs personnalises/jour, partager 2x/semaine. SSI > 80 en 90 jours.', 'Social selling: poster 3x/sem + 5 commentaires/jour + 5 DM/jour = SSI 80 en 90j', 'commercial', 'best_practice', 0.82, 'elite_commercial', 'system'),
('COMMERCIAL_ELITE: Le pipeline coverage ratio ideal: 3x le quota pour les deals < 30j, 4x pour 30-60j, 5x pour 60-90j. En dessous = risque de quota miss.', 'Pipeline coverage: 3x <30j, 4x 30-60j, 5x 60-90j. Sinon risque quota miss', 'commercial', 'best_practice', 0.85, 'elite_commercial', 'system'),
('COMMERCIAL_ELITE: Le cold email expert: 1 phrase perso (montrer qu on a cherche), 1 phrase valeur (probleme specifique resolu), 1 phrase CTA (question simple). Max 80 mots.', 'Cold email: 1 perso + 1 valeur + 1 CTA. Max 80 mots', 'commercial', 'best_practice', 0.88, 'elite_commercial', 'system'),
('COMMERCIAL_ELITE: Le follow-up timing science: email J+2 (mardi), call J+4 (jeudi), LinkedIn J+6 (lundi), email J+9, breakup J+14. Jamais le meme canal consecutif.', 'Follow-up: email J2, call J4, LinkedIn J6, email J9, breakup J14. Varier canaux', 'commercial', 'best_practice', 0.85, 'elite_commercial', 'system'),
('COMMERCIAL_ELITE: Le negotiation framework ZOPA: identifier la zone d accord possible (votre minimum et le maximum du prospect). Le deal se fait dans cette zone.', 'ZOPA: zone accord entre votre min et leur max. Deal dans cette zone', 'commercial', 'best_practice', 0.82, 'elite_commercial', 'system'),
('COMMERCIAL_ELITE: Le value engineering: quantifier la valeur en euros (economie de temps × taux horaire × nombre d employes × 12 mois). Presenter ce chiffre avant le prix.', 'Value engineering: economie temps × taux horaire × employes × 12 mois. Avant prix', 'commercial', 'best_practice', 0.88, 'elite_commercial', 'system'),
('COMMERCIAL_ELITE: Le dead deal resurrection: relancer les deals perdus apres 90 jours avec un angle different (nouveau feature, nouveau case study, changement de prix). 10% convertissent.', 'Dead deal resurrection 90j + nouvel angle = 10% conversion', 'commercial', 'insight', 0.82, 'elite_commercial', 'system'),
('COMMERCIAL_ELITE: Le customer as closer: faire intervenir un client satisfait (reference call) dans les deals strategiques. Taux de closing +40%.', 'Reference call client satisfait = +40% closing', 'commercial', 'best_practice', 0.88, 'elite_commercial', 'system')
ON CONFLICT DO NOTHING;
