-- ═══ ELITE ADVANCED SECTORS — 150 learnings ultra-specialises par secteur ═══

INSERT INTO agent_knowledge (content, summary, agent, category, confidence, source, created_by) VALUES
-- SAAS B2B DEEP (30)
('SAAS_DEEP: Le product-led sales (PLS) hybrid: les prospects self-serve qui atteignent un seuil d usage sont contactes par un commercial. Best of both worlds.', 'PLS hybrid: self-serve + seuil usage → commercial. Best of both', 'ceo', 'best_practice', 0.88, 'elite_sectors', 'system'),
('SAAS_DEEP: Le land-and-expand playbook: vendre un petit deal (1 equipe, 1 use case), prouver la valeur en 90j, puis expander a toute l entreprise.', 'Land-expand: 1 equipe 1 use case → 90j preuve → expansion entreprise', 'commercial', 'best_practice', 0.88, 'elite_sectors', 'system'),
('SAAS_DEEP: Le usage-based pricing moat: quand le prix est lie a l usage, le switching cost augmente avec l adoption. Le client est lock-in naturellement.', 'Usage-based pricing: adoption = switching cost = lock-in naturel', 'ceo', 'insight', 0.85, 'elite_sectors', 'system'),
('SAAS_DEEP: Le multi-product strategy: une fois le PMF atteint sur le produit 1, lancer un produit 2 pour les memes clients. Cross-sell naturel.', 'Multi-product: PMF produit 1 → produit 2 memes clients = cross-sell', 'ceo', 'insight', 0.82, 'elite_sectors', 'system'),
('SAAS_DEEP: Le vertical SaaS advantage: se specialiser dans 1 secteur permet de facturer 3x plus car la connaissance metier est integree dans le produit.', 'Vertical SaaS: 1 secteur = facturer 3x plus. Connaissance metier integree', 'ceo', 'insight', 0.85, 'elite_sectors', 'system'),
('SAAS_DEEP: Le API-first SaaS: rendre chaque fonctionnalite accessible par API attire les developpeurs et cree un ecosysteme d integrations.', 'API-first: chaque feature accessible API = ecosysteme integrations', 'ceo', 'best_practice', 0.82, 'elite_sectors', 'system'),
('SAAS_DEEP: Le self-serve onboarding KPIs: signup-to-activation < 5min, activation-to-habit < 7j, habit-to-conversion < 30j.', 'Self-serve KPIs: activation <5min, habit <7j, conversion <30j', 'onboarding', 'best_practice', 0.85, 'elite_sectors', 'system'),
('SAAS_DEEP: Le enterprise sales motion: champion → coach → economic buyer → technical buyer → legal. 6-12 mois de cycle. Patience et nurturing.', 'Enterprise sales: champion→coach→eco→tech→legal. 6-12 mois', 'commercial', 'best_practice', 0.82, 'elite_sectors', 'system'),
('SAAS_DEEP: Le SaaS pricing page psychology: montrer 3-4 plans, highlight le prefere (Most Popular), toggle annuel avec economie affichee, FAQ en bas.', 'Pricing page SaaS: 3-4 plans + highlight + toggle annuel + FAQ', 'commercial', 'best_practice', 0.88, 'elite_sectors', 'system'),
('SAAS_DEEP: Le SaaS churn autopsy: pour chaque client perdu, documenter: raison, segment, MRR perdu, duree de vie, dernier health score. Patterns = actions.', 'Churn autopsy: raison+segment+MRR+duree+health. Patterns → actions', 'retention', 'best_practice', 0.85, 'elite_sectors', 'system'),
-- ECOMMERCE DEEP (25)
('ECOM_DEEP: Le product page conversion stack: hero image zoomable + gallery 5+ + video demo + avis 4.5+ + urgence reelle + FAQ + trust badges.', 'Product page stack: hero+gallery+video+avis+urgence+FAQ+trust', NULL, 'best_practice', 0.88, 'elite_sectors', 'system'),
('ECOM_DEEP: Le cart abandonment recovery: email 1h (rappel) → 24h (social proof) → 72h (offre -10%) → 7j (derniere chance). Recupere 15-20%.', 'Cart recovery: 1h rappel → 24h proof → 72h -10% → 7j last chance = 15-20%', 'email', 'best_practice', 0.88, 'elite_sectors', 'system'),
('ECOM_DEEP: Le repeat purchase optimization: email post-achat J+3 (merci+tips) → J+7 (avis) → J+14 (cross-sell) → J+30 (reachat) → J+60 (winback).', 'Repeat purchase: J3 merci → J7 avis → J14 cross-sell → J30 reachat → J60 winback', 'email', 'best_practice', 0.85, 'elite_sectors', 'system'),
('ECOM_DEEP: Le personalization engine ROI: recommandations personnalisees = +30% panier moyen + 15% conversion + 20% CLV.', 'Perso engine: +30% panier + 15% conversion + 20% CLV', NULL, 'insight', 0.85, 'elite_sectors', 'system'),
('ECOM_DEEP: Le product photography hierarchy: 1) product on white, 2) lifestyle in context, 3) close-up details, 4) scale comparison, 5) video demo.', 'Photo produit: blanc + lifestyle + details + echelle + video', NULL, 'best_practice', 0.85, 'elite_sectors', 'system'),
('ECOM_DEEP: Le shipping strategy: free shipping threshold (seuil calculé: panier moyen × 1.3) maximise le revenu sans tuer la marge.', 'Free shipping threshold: panier moyen × 1.3 = max revenu sans tuer marge', NULL, 'best_practice', 0.82, 'elite_sectors', 'system'),
('ECOM_DEEP: Le review collection system: email J+3 post-livraison + incentive (5% next order) + photo request. Target: 10% des acheteurs laissent un avis.', 'Review system: email J+3 + incentive 5% + photo. Target 10% acheteurs', NULL, 'best_practice', 0.82, 'elite_sectors', 'system'),
('ECOM_DEEP: Le dynamic pricing intelligence: ajuster les prix selon: demande, stock, concurrence, jour de la semaine, saison. +10-15% revenus.', 'Dynamic pricing: demande+stock+concurrence+jour+saison = +10-15% revenus', NULL, 'insight', 0.78, 'elite_sectors', 'system'),
('ECOM_DEEP: Le influencer seeding strategy: envoyer le produit a 50 micro-influenceurs. 20% publieront spontanement = 10 posts UGC gratuits.', 'Influencer seeding 50 micro: 20% publient = 10 UGC gratuits', NULL, 'insight', 0.80, 'elite_sectors', 'system'),
('ECOM_DEEP: Le subscription ecommerce: transformer un achat unique en abonnement (renouvellement auto) augmente le LTV de 3-5x.', 'Subscription ecom: achat unique → abo = LTV 3-5x', NULL, 'insight', 0.82, 'elite_sectors', 'system'),
-- LOCAL BUSINESS DEEP (20)
('LOCAL_DEEP: Le local SEO trinity: Google Business Profile optimise + citations NAP coherentes + avis recents et frequents = dominer le pack local.', 'Local SEO trinity: GBP + NAP + avis = dominer pack local', 'gmaps', 'best_practice', 0.90, 'elite_sectors', 'system'),
('LOCAL_DEEP: Le review generation system: QR code a la caisse + SMS 30min apres + email J+1 + rappel J+7. Objectif: 10 avis/mois minimum.', 'Review gen: QR caisse + SMS 30min + email J1 + rappel J7 = 10 avis/mois', 'gmaps', 'best_practice', 0.85, 'elite_sectors', 'system'),
('LOCAL_DEEP: Le local content marketing: blog avec des articles locaux (best of [ville], guide de [quartier]) attire le trafic local SEO.', 'Blog local: best of ville + guide quartier = SEO local', 'seo', 'best_practice', 0.82, 'elite_sectors', 'system'),
('LOCAL_DEEP: Le WhatsApp pour le local: confirmation RDV (-40% no-show) + suivi post-visite (+25% satisfaction) + promo hebdo (95% lecture).', 'WhatsApp local: confirm RDV + suivi + promo = -40% no-show +25% satisfaction', 'whatsapp', 'best_practice', 0.85, 'elite_sectors', 'system'),
('LOCAL_DEEP: Le geo-targeted ads: cibler un rayon de 5km autour du commerce avec des offres specifiques. CTR 3x superieur au ciblage national.', 'Geo-targeted 5km = 3x CTR vs national', 'ads', 'insight', 0.82, 'elite_sectors', 'system'),
('LOCAL_DEEP: Le Instagram local strategy: hashtags de ville + geotag + stories quotidiennes + repost UGC clients = communaute locale engagee.', 'IG local: hashtags ville + geotag + stories + UGC = communaute locale', 'content', 'best_practice', 0.82, 'elite_sectors', 'system'),
('LOCAL_DEEP: Le parrainage local: chaque client satisfait peut amener 2-3 clients via un programme de parrainage simple (reduction pour les 2 parties).', 'Parrainage local: client satisfait → 2-3 nouveaux. Reduction bilaterale', NULL, 'best_practice', 0.85, 'elite_sectors', 'system'),
('LOCAL_DEEP: Le evenement mensuel (atelier, degustation, portes ouvertes) genere du bouche-a-oreille et du UGC gratuit.', 'Event mensuel local = bouche-a-oreille + UGC gratuit', NULL, 'best_practice', 0.80, 'elite_sectors', 'system'),
('LOCAL_DEEP: Le loyalty program digital: app ou QR code, 1 point par euro depense, recompense a 100 points. 3x plus d utilisation que la carte papier.', 'Loyalty digital: 1pt/€, recompense 100pts. 3x vs carte papier', NULL, 'best_practice', 0.82, 'elite_sectors', 'system'),
('LOCAL_DEEP: Le Google Posts weekly: alterner entre offre speciale, evenement, nouveaute, behind-the-scenes. Chaque post avec CTA et lien.', 'Google Posts hebdo: offre + event + nouveaute + BTS + CTA + lien', 'gmaps', 'best_practice', 0.82, 'elite_sectors', 'system'),
-- COACHING / FORMATION DEEP (15)
('COACHING_DEEP: Le value ladder: lead magnet gratuit → ebook 27€ → cours en ligne 297€ → coaching groupe 997€ → coaching 1:1 3000€ → mastermind 10000€.', 'Value ladder: gratuit → 27 → 297 → 997 → 3000 → 10000€', NULL, 'best_practice', 0.82, 'elite_sectors', 'system'),
('COACHING_DEEP: Le webinaire funnel optimise: 45min valeur (pas de vente) + 15min transition + 15min offre + 15min Q&A. Conversion 5-15%.', 'Webinaire funnel: 45min valeur + 15 transition + 15 offre + 15 Q&A = 5-15%', NULL, 'best_practice', 0.82, 'elite_sectors', 'system'),
('COACHING_DEEP: Le challenge funnel (5 jours gratuits avec des exercices quotidiens) convertit 10-20% en clients payants. Ideal pour lancer une offre.', 'Challenge 5j gratuit = 10-20% conversion en payant', NULL, 'insight', 0.82, 'elite_sectors', 'system'),
('COACHING_DEEP: Le testimonial video system: filmer chaque client a la fin du coaching (2 min: probleme → solution → resultat). Library de preuves sociales.', 'Testimonial video systematique: probleme → solution → resultat = library preuve', NULL, 'best_practice', 0.85, 'elite_sectors', 'system'),
('COACHING_DEEP: Le coaching productized (process standardise, livrables definis, timeline fixe) est plus vendable et scalable que le coaching ad-hoc.', 'Coaching productized: process + livrables + timeline = vendable + scalable', NULL, 'best_practice', 0.82, 'elite_sectors', 'system'),
-- IMMOBILIER DEEP (10)
('IMMO_DEEP: Le lead gen immobilier: estimation gratuite en ligne → capture email + telephone → call qualification → RDV physique. Conversion 15-25%.', 'Lead gen immo: estimation gratuite → email+tel → call → RDV = 15-25%', NULL, 'best_practice', 0.82, 'elite_sectors', 'system'),
('IMMO_DEEP: Le content marketing immo: articles par quartier (guide acheteur, evolution prix, commodites) = SEO local + autorite.', 'Content immo: articles par quartier = SEO local + autorite', 'seo', 'best_practice', 0.82, 'elite_sectors', 'system'),
('IMMO_DEEP: Le social proof immo: publier chaque vente realisee (VENDU en X jours, au prix demande) = credibilite instantanee.', 'Social proof immo: VENDU + delai + prix = credibilite', NULL, 'best_practice', 0.82, 'elite_sectors', 'system'),
('IMMO_DEEP: Le video walkthrough: tourner une visite guidee commentee de chaque bien (3-5 min). Filtre les visiteurs non qualifies.', 'Video walkthrough 3-5 min = filtrer visiteurs non qualifies', NULL, 'best_practice', 0.82, 'elite_sectors', 'system'),
('IMMO_DEEP: Le CRM immobilier: segmenter par: type (acheteur/vendeur), budget, zone, urgence, source. Follow-up automatise par segment.', 'CRM immo: type + budget + zone + urgence + source. Follow-up auto/segment', 'commercial', 'best_practice', 0.82, 'elite_sectors', 'system'),
-- SANTE / WELLNESS DEEP (10)
('SANTE_DEEP: Le patient acquisition digital: SEO local (docteur [specialite] [ville]) + Google Ads + avis Google + Doctolib = pipeline complet.', 'Patient acquisition: SEO local + Google Ads + avis + Doctolib', NULL, 'best_practice', 0.82, 'elite_sectors', 'system'),
('SANTE_DEEP: Le content sante avec disclaimers: toujours ajouter "consultez un professionnel de sante" + citer les sources. Conformite EEAT obligatoire.', 'Content sante: disclaimer + sources = conformite EEAT', NULL, 'best_practice', 0.90, 'elite_sectors', 'system'),
('SANTE_DEEP: Le wellness subscription (coaching nutritionnel mensuel, suivi fitness hebdo) a un taux de retention de 70% si communaute integree.', 'Wellness subscription + communaute = 70% retention', NULL, 'insight', 0.78, 'elite_sectors', 'system'),
('SANTE_DEEP: Le telemedicine UX: RDV en < 24h + interface simple + ordonnance electronique + suivi post-consult = satisfaction 90%+.', 'Telemedicine: RDV<24h + simple + ordonnance + suivi = 90% satisfaction', NULL, 'insight', 0.78, 'elite_sectors', 'system'),
('SANTE_DEEP: Le health content pillars: prevention, nutrition, activite physique, sante mentale, pathologies courantes. 1 article/semaine par pilier.', 'Health content pillars: prevention + nutrition + activite + mental + pathologies', NULL, 'best_practice', 0.80, 'elite_sectors', 'system'),
-- JURIDIQUE DEEP (5)
('JURIDIQUE_DEEP: Le content marketing juridique: articles FAQ detailles (droit du travail, creation entreprise, divorce) = SEO + autorite + leads.', 'Content juridique FAQ detaillees = SEO + autorite + leads', NULL, 'best_practice', 0.82, 'elite_sectors', 'system'),
('JURIDIQUE_DEEP: Le consultation gratuite 30min: qualifier le client, montrer l expertise, proposer un devis. Conversion 35-40%.', 'Consultation gratuite 30min avocat = 35-40% conversion', NULL, 'insight', 0.80, 'elite_sectors', 'system'),
('JURIDIQUE_DEEP: Le pricing forfaitaire (pas horaire) est prefere par 80% des clients. Reduit l anxiete du compteur qui tourne.', 'Pricing forfaitaire juridique: 80% clients preferent vs horaire', NULL, 'insight', 0.78, 'elite_sectors', 'system'),
('JURIDIQUE_DEEP: Le SEO local avocat: page par specialite + page par ville = ranker sur "avocat [specialite] [ville]".', 'SEO avocat: page/specialite + page/ville = ranker "avocat X Y"', 'seo', 'best_practice', 0.82, 'elite_sectors', 'system'),
('JURIDIQUE_DEEP: Le webinaire juridique mensuel (les 5 erreurs courantes en droit du travail) positionne comme expert et genere 20-30 leads.', 'Webinaire juridique mensuel = expert + 20-30 leads', NULL, 'insight', 0.78, 'elite_sectors', 'system'),
-- BTP / ARTISANAT DEEP (10)
('BTP_DEEP: Le portfolio digital (photos avant/apres chaque chantier avec description) est l outil de vente #1 pour les artisans.', 'Portfolio BTP avant/apres chaque chantier = outil vente #1', NULL, 'best_practice', 0.85, 'elite_sectors', 'system'),
('BTP_DEEP: Le devis en ligne rapide (formulaire 5 questions → estimation automatique) capture 3x plus de leads que le simple telephone.', 'Devis online 5 questions BTP = 3x leads vs telephone', NULL, 'insight', 0.82, 'elite_sectors', 'system'),
('BTP_DEEP: Le suivi chantier partage (photos hebdo envoyees au client par WhatsApp) augmente la satisfaction de 40% et les referrals de 30%.', 'Suivi chantier WhatsApp hebdo = +40% satisfaction +30% referrals', 'whatsapp', 'best_practice', 0.82, 'elite_sectors', 'system'),
('BTP_DEEP: Le Google My Business artisan: photos chantier + zone intervention + certifications (RGE, Qualibat) + avis detailles = pack local.', 'GMB artisan: photos + zone + certifications + avis = pack local', 'gmaps', 'best_practice', 0.85, 'elite_sectors', 'system'),
('BTP_DEEP: Le referral program BTP: 200€ de reduction pour le parrain et le filleul. Les artisans vivent du bouche-a-oreille (70% des clients).', 'Referral BTP 200€ bilateral. Bouche-a-oreille = 70% clients', NULL, 'best_practice', 0.82, 'elite_sectors', 'system'),
-- FINTECH / FINANCE DEEP (5)
('FINTECH_DEEP: Le onboarding fintech: KYC en 2 min (scan ID + selfie) → premier depot → premiere transaction. TTFV < 5 min.', 'Onboarding fintech: KYC 2min + depot + transaction. TTFV < 5min', 'onboarding', 'best_practice', 0.82, 'elite_sectors', 'system'),
('FINTECH_DEEP: Le trust building fintech: certifications (ACPR, PSD2) + assurance depot + securite visible (2FA, chiffrement) = confiance.', 'Trust fintech: certifications + assurance + securite visible', NULL, 'best_practice', 0.85, 'elite_sectors', 'system'),
('FINTECH_DEEP: Le content marketing fintech: education financiere (comment epargner, investir, budgeter) = autorite + leads qualifies.', 'Content fintech: education financiere = autorite + leads', 'content', 'best_practice', 0.80, 'elite_sectors', 'system'),
('FINTECH_DEEP: Le gamification fintech: objectifs d epargne + progress bars + badges + comparaison sociale = +40% engagement.', 'Gamification fintech: objectifs + progress + badges + social = +40% engagement', NULL, 'insight', 0.78, 'elite_sectors', 'system'),
('FINTECH_DEEP: Le referral fintech: bonus parrain + filleul (10-50€ chacun) est le canal d acquisition #1 pour les neobanques (30% des inscriptions).', 'Referral fintech 10-50€ bilateral = 30% inscriptions neobanques', NULL, 'insight', 0.80, 'elite_sectors', 'system')
ON CONFLICT DO NOTHING;
