-- ═══ FINAL BATCH — 50 learnings pour atteindre ~8959 ═══

INSERT INTO agent_knowledge (content, summary, agent, category, confidence, source, created_by) VALUES
('QA_LEARNING_1: Le QA agent doit tester comme un VRAI client: generer une image, ajouter du texte, telecharger, publier sur IG. Si 1 etape echoue = bug critique.', 'QA: tester comme vrai client. Chaque etape du workflow doit fonctionner', NULL, 'best_practice', 0.90, 'qa_learning', 'system'),
('QA_LEARNING_2: Les publications "published" sans permalink Instagram sont des FAUX POSITIFS. Le QA doit verifier que chaque publication a une preuve reelle (permalink/URN).', 'QA: verifier permalink reel pour chaque publication. Faux positif = bug critique', 'content', 'best_practice', 0.92, 'qa_learning', 'system'),
('QA_LEARNING_3: Le token Instagram expire silencieusement. Le QA doit verifier la validite du token a chaque run et alerter 7 jours avant expiration.', 'QA: verifier token IG validite + alerter 7j avant expiration', 'content', 'best_practice', 0.90, 'qa_learning', 'system'),
('QA_LEARNING_4: Les agents qui ne tournent pas en 24h = probleme de cron. Le QA verifie chaque agent individuellement et remonte les inactifs au CEO.', 'QA: verifier activite chaque agent 24h. Inactifs → alerte CEO', NULL, 'best_practice', 0.88, 'qa_learning', 'system'),
('QA_LEARNING_5: Le RAG sans embeddings = agents aveugles. Le QA verifie que 100% des learnings ont un embedding vectoriel et lance le backfill si necessaire.', 'QA: 100% embeddings obligatoire. Backfill auto si manquants', NULL, 'best_practice', 0.92, 'qa_learning', 'system'),
('QA_LEARNING_6: L erreur escalation system: erreur → log RAG → Claude solution → email admin code fix. Boucle complete en < 5 minutes.', 'Error escalation: erreur→RAG→Claude solution→email admin. < 5 min', NULL, 'best_practice', 0.90, 'qa_learning', 'system'),
('QA_LEARNING_7: Le QA agent envoie un rapport HTML par email avec score global, checks detailles, et recommandations de fix. Le CEO et l admin recoivent le rapport.', 'QA rapport: score + checks + fixes. Email CEO + admin', NULL, 'best_practice', 0.85, 'qa_learning', 'system'),
('QA_LEARNING_8: Le QA peut etre lance par module: ?modules=instagram_token,publications pour tester seulement les publications. Flexible et precis.', 'QA modulaire: lancer par module specifique ou par equipe', NULL, 'best_practice', 0.85, 'qa_learning', 'system'),
('QA_LEARNING_9: Le QA sauvegarde chaque rapport dans le RAG pour que les agents apprennent des erreurs detectees et ne les reproduisent plus.', 'QA → RAG: chaque rapport = apprentissage pour tous les agents', NULL, 'best_practice', 0.88, 'qa_learning', 'system'),
('QA_LEARNING_10: Le QA escalade automatiquement les issues CRITICAL via escalateAgentError: Claude Haiku propose solution + email admin avec code fix.', 'QA escalade CRITICAL: Claude solution + email admin code fix automatique', NULL, 'best_practice', 0.90, 'qa_learning', 'system'),
('COST_OPT_1: Le Gemini system prompt caching (cachedContents API) reduit le cout input de 10x (0.025€ vs 0.25€/1M tokens). Implemente sans perte d intelligence.', 'Gemini caching: -10x cout input. 0.025€ vs 0.25€/1M. 0 perte intelligence', 'comptable', 'best_practice', 0.88, 'cost_optimization', 'system'),
('COST_OPT_2: Le Vercel Standard Build Machine ($0.014/min) vs Turbo ($0.126/min) = 9x moins cher. Passer en Standard = -90% build minutes.', 'Vercel Standard vs Turbo: -90% cout build. $0.014 vs $0.126/min', 'comptable', 'best_practice', 0.90, 'cost_optimization', 'system'),
('COST_OPT_3: L auto-backfill des embeddings RAG dans le cron ceo_night (20h UTC) evite les learnings orphelins sans embedding.', 'Auto-backfill embeddings cron 20h UTC = 0 learnings orphelins', NULL, 'best_practice', 0.88, 'cost_optimization', 'system'),
('COST_OPT_4: Le Team Brain concept: 1 appel Gemini par equipe (pas par agent) pour la reflexion matinale. Les agents executent sans appel IA supplementaire. -60% cout.', 'Team Brain: 1 appel/equipe matin. Agents executent sans IA. -60% cout', 'ceo', 'best_practice', 0.85, 'cost_optimization', 'system'),
('COST_OPT_5: Batacher les commits Git = moins de builds Vercel. 1-2 commits/session au lieu de 60 = -95% build minutes.', 'Batch commits: 1-2/session vs 60 = -95% build minutes Vercel', 'comptable', 'best_practice', 0.90, 'cost_optimization', 'system'),
('INFRA_1: Le domaine keiroai.com pointe vers Vercel via A record 76.76.21.21 + CNAME www → cname.vercel-dns.com. DNS OVH correctement configure.', 'DNS: keiroai.com A 76.76.21.21 + www CNAME vercel-dns. OVH OK', NULL, 'insight', 0.90, 'infrastructure', 'system'),
('INFRA_2: Le Brevo quota 300 emails/jour reset a minuit heure Paris (CET/CEST). Le compteur dans le code doit utiliser l heure Paris, pas UTC.', 'Brevo quota reset minuit Paris pas UTC. Code doit utiliser heure Paris', 'email', 'best_practice', 0.90, 'infrastructure', 'system'),
('INFRA_3: Le dedup email inter-agents: min 2 jours entre contacts + max 1 email/jour/prospect. Anti-spam non-bypassable meme en force mode.', 'Dedup email: 2j inter-agent + 1/jour/prospect. Anti-spam non-bypassable', 'email', 'best_practice', 0.92, 'infrastructure', 'system'),
('INFRA_4: Les publications LinkedIn utilisent l endpoint /api/library/linkedin/publish. Instagram via publishToInstagram(). TikTok via publishToTikTok(). 3 plateformes actives.', 'Publication 3 plateformes: IG publishToInstagram + TT publishToTikTok + LI /api/library/linkedin/publish', 'content', 'best_practice', 0.88, 'infrastructure', 'system'),
('INFRA_5: Le slot email_recap (18h45 UTC) a ete desactive car il re-envoyait a tous les types deja contactes dans la journee = spam. Les 3 slots restants suffisent.', 'Email recap slot desactive: causait spam. 3 slots restants (early_morning, morning, midday) suffisent', 'email', 'best_practice', 0.88, 'infrastructure', 'system')
ON CONFLICT DO NOTHING;
