-- ═══ ELITE BOOST V2 — CEO Dev/Code + Growth/Retention/UX ═══

-- ═══ CEO — DEV / CODE / ARCHITECTURE ═══
INSERT INTO agent_knowledge (content, summary, agent, category, confidence, source, created_by) VALUES
('CEO DEV: Architecture Next.js App Router optimale — pages dans app/, API routes dans app/api/, libs partagees dans lib/. Toujours utiliser server components par defaut, client components uniquement pour interactivite.', 'Architecture Next.js best practices', 'ceo', 'best_practice', 0.95, 'elite_boost_v2', 'system'),
('CEO DEV: Supabase performance — toujours utiliser select() avec colonnes specifiques (pas select *), ajouter des index sur les colonnes filtrees, utiliser .limit() et .range() pour la pagination, RLS pour la securite.', 'Supabase performance optimization', 'ceo', 'best_practice', 0.93, 'elite_boost_v2', 'system'),
('CEO DEV: Vercel Edge Functions vs Serverless — Edge pour les routes rapides (<50ms, pas de DB lourde), Serverless (nodejs) pour les agents qui font des appels API longs. maxDuration=300 est le max sur Pro.', 'Edge vs Serverless Vercel decision', 'ceo', 'best_practice', 0.92, 'elite_boost_v2', 'system'),
('CEO DEV: Pattern agent optimal — 1. Auth check, 2. Load shared context (brand + RAG + learnings), 3. Build prompt, 4. Call LLM, 5. Parse response, 6. Execute action, 7. Save learning, 8. Emit event. Chaque etape doit etre try/catch.', 'Pattern agent code standard', 'ceo', 'best_practice', 0.95, 'elite_boost_v2', 'system'),
('CEO DEV: Rate limiting — Brevo 300/jour, Resend 100/heure, OpenAI 10K tokens/min, Gemini 15 req/min, Seedream 60/heure. Toujours implementer des queues avec retry exponential backoff.', 'Rate limits providers API', 'ceo', 'best_practice', 0.93, 'elite_boost_v2', 'system'),
('CEO DEV: Debugging agents en prod — toujours logger avec [AgentName] prefix, inclure prospect_id/user_id dans les logs, utiliser agent_logs table comme audit trail complet. Jamais de console.log sans context.', 'Debugging agents production', 'ceo', 'best_practice', 0.92, 'elite_boost_v2', 'system'),
('CEO DEV: Prompt engineering pour agents — System prompt structure: 1. Identite (qui tu es), 2. Mission (que faire), 3. Regles (contraintes), 4. Contexte (shared context injecte), 5. Format output (JSON/texte). Toujours specifier le format de sortie.', 'Prompt engineering agents structure', 'ceo', 'best_practice', 0.95, 'elite_boost_v2', 'system'),
('CEO DEV: TypeScript strict — toujours typer les interfaces, jamais de any sauf exceptions documentees, utiliser Zod pour valider les inputs API, discriminated unions pour les etats.', 'TypeScript strict best practices', 'ceo', 'best_practice', 0.90, 'elite_boost_v2', 'system'),
('CEO DEV: Cron scheduling — espacer les agents de min 15min pour eviter les timeouts Vercel. Utiliser waitUntil() pour les taches background. Les agents lourds (content, email) en fireBackground.', 'Cron scheduling Vercel optimization', 'ceo', 'best_practice', 0.93, 'elite_boost_v2', 'system'),
('CEO DEV: Quand un agent timeout (300s Vercel), decomposer en sous-taches: 1. Preparation (fetch data), 2. Processing (LLM calls), 3. Execution (actions). Chaque sous-tache < 60s idealement.', 'Decomposition timeout agents', 'ceo', 'best_practice', 0.92, 'elite_boost_v2', 'system'),
('CEO DEV: RAG optimization — embeddings ada-002 coutent $0.0001/1K tokens. Pour 2500 entries = ~$0.05. Batch les embeddings par 10 en parallele. Index IVFFlat avec lists=100 pour <10K entries.', 'RAG cost optimization', 'ceo', 'insight', 0.88, 'elite_boost_v2', 'system'),
('CEO DEV: Migration SQL safe — toujours IF NOT EXISTS, ON CONFLICT DO NOTHING, jamais de DROP sans backup. Tester en local avant Supabase prod. Les RLS policies doivent etre testees avec anon et service_role.', 'Migration SQL safe practices', 'ceo', 'best_practice', 0.93, 'elite_boost_v2', 'system'),
('CEO DEV REPORT: Quand un probleme technique est detecte, generer un rapport avec: 1. Symptome observe, 2. Cause racine identifiee, 3. Impact business (bloquant/degradant/mineur), 4. Solution proposee (code concret), 5. Estimation effort. Envoyer a contact@keiroai.com.', 'Format rapport technique CEO', 'ceo', 'best_practice', 0.95, 'elite_boost_v2', 'system'),
('CEO DEV: Performance frontend — utiliser dynamic import pour les composants lourds (CrmDashboard, AgentDashboard), lazy loading images, eviter les re-renders avec useMemo/useCallback, skeleton loaders pendant le chargement.', 'Performance frontend Next.js', 'ceo', 'best_practice', 0.90, 'elite_boost_v2', 'system'),
('CEO DEV: Securite — jamais stocker de secrets cote client, toujours valider les inputs serveur, CORS configure, CSP headers, rate limiting par IP sur les endpoints publics, sanitize SQL inputs meme avec Supabase.', 'Securite web application', 'ceo', 'best_practice', 0.95, 'elite_boost_v2', 'system'),

-- ═══ CEO — GROWTH HACKING AVANCE ═══
('CEO GROWTH: Viral loop — chaque client satisfait doit pouvoir partager KeiroAI en 1 clic. Ajouter des boutons "Partager mes resultats" dans le dashboard. Le referral = canal d acquisition le moins cher.', 'Viral loop referral', 'ceo', 'insight', 0.92, 'elite_boost_v2', 'system'),
('CEO GROWTH: Activation rapide — un nouveau client doit voir de la valeur en < 24h. Clara (onboarding) doit generer le premier post + envoyer le premier email + configurer le chatbot des J1.', 'Activation J1 valeur immediate', 'ceo', 'best_practice', 0.95, 'elite_boost_v2', 'system'),
('CEO GROWTH: Churn prediction — si un client ne se connecte pas pendant 3 jours, Theo (retention) doit envoyer un email de reactivation. Si 7 jours, appel direct. Si 14 jours, offre speciale.', 'Churn prediction timing', 'ceo', 'best_practice', 0.93, 'elite_boost_v2', 'system'),
('CEO GROWTH: NPS tracking — apres 7 jours d utilisation, demander un score NPS (0-10). Si > 8, demander un temoignage. Si < 6, alerter le CEO + onboarding pour intervention immediate.', 'NPS tracking et intervention', 'ceo', 'best_practice', 0.90, 'elite_boost_v2', 'system'),
('CEO GROWTH: Expansion revenue — une fois le client actif, proposer des upsells naturels: plus de credits, plus d agents, multi-comptes. L upsell doit venir APRES que le client ait vu des resultats concrets.', 'Expansion revenue upsell', 'ceo', 'insight', 0.88, 'elite_boost_v2', 'system'),

-- ═══ RETENTION (THEO R.) — Satisfaction client long terme ═══
('RETENTION RULE: Le client doit recevoir un rapport de resultats chaque semaine: posts publies, emails envoyes, prospects contactes, engagement genere. Format visuel, pas de texte long.', 'Rapport hebdo resultats client', 'retention', 'best_practice', 0.95, 'elite_boost_v2', 'system'),
('RETENTION RULE: Indicateurs de satisfaction a tracker: frequence connexion, nombre d actions lancees, feedback sur les contenus generes, taux d utilisation des agents. Si 2+ indicateurs baissent, intervenir.', 'Indicateurs satisfaction client', 'retention', 'best_practice', 0.93, 'elite_boost_v2', 'system'),
('RETENTION INSIGHT: Les clients qui utilisent 3+ agents ont un churn 4x inferieur a ceux qui n en utilisent qu un. Objectif: activer minimum 3 agents dans les 7 premiers jours.', 'Multi-agent = retention', 'retention', 'insight', 0.92, 'elite_boost_v2', 'system'),
('RETENTION RULE: Celebrer les victoires du client — premier post publie, premier prospect contacte, premier client converti. Chaque milestone = notification + felicitations personnalisees.', 'Celebrer milestones client', 'retention', 'best_practice', 0.90, 'elite_boost_v2', 'system'),
('RETENTION INSIGHT: Le moment le plus critique est entre J7 et J14. Si le client ne voit pas de resultats concrets a J14, la probabilite de churn est de 70%. Concentrer les efforts sur cette periode.', 'Periode critique J7-J14', 'retention', 'insight', 0.93, 'elite_boost_v2', 'system'),

-- ═══ ONBOARDING (CLARA) — Experience J1 parfaite ═══
('ONBOARDING RULE: Flow J1 optimal: 1. Remplir le dossier business (5 min), 2. Connecter Instagram (2 min), 3. Premier post genere automatiquement (instant), 4. Premier email prospect envoye (instant). Le client voit la valeur en < 10 min.', 'Flow J1 onboarding 10 min', 'onboarding', 'best_practice', 0.95, 'elite_boost_v2', 'system'),
('ONBOARDING RULE: Guide interactif pas-a-pas — jamais de mur de texte. Chaque etape = 1 action, 1 resultat visible. Progress bar toujours visible. Feliciter a chaque etape completee.', 'Guide interactif onboarding', 'onboarding', 'best_practice', 0.93, 'elite_boost_v2', 'system'),
('ONBOARDING INSIGHT: Les clients qui remplissent leur dossier business a > 70% ont 3x plus de chance de rester actifs. Le dossier est la base de la personnalisation — insister dessus.', 'Dossier business = retention', 'onboarding', 'insight', 0.92, 'elite_boost_v2', 'system'),
('ONBOARDING RULE: Si le client bloque sur une etape > 2 min, proposer de l aide via Clara (chat). Si bloque > 5 min, envoyer une notification email avec un lien direct vers l etape.', 'Deblocage onboarding proactif', 'onboarding', 'best_practice', 0.90, 'elite_boost_v2', 'system'),

-- ═══ UX/UI — Tous les agents detectent les problemes ═══
('SHARED UX: Si un utilisateur clique 3+ fois sur un element sans resultat, c est un signal de friction UX. Logger l evenement et remonter au CEO pour correction.', 'Detection friction UX clicks', NULL, 'best_practice', 0.90, 'elite_boost_v2', 'system'),
('SHARED UX: Temps de chargement des pages > 3 secondes = 53% d abandon. Chaque page doit charger en < 2s. Utiliser skeleton loaders, lazy loading, et optimiser les requetes DB.', 'Performance UX temps chargement', NULL, 'best_practice', 0.93, 'elite_boost_v2', 'system'),
('SHARED UX: Le parcours utilisateur ideal: Decouverte (page accueil) → Demo (mode visiteur agents) → Inscription (credit gratuit) → Activation (J1 onboarding) → Retention (resultats visibles J7) → Upsell (J30).', 'Parcours utilisateur ideal funnel', NULL, 'best_practice', 0.95, 'elite_boost_v2', 'system'),
('SHARED UX: Mobile first — 70% des utilisateurs sont sur mobile. Chaque fonctionnalite doit etre testee mobile d abord. Bottom nav, touch targets > 44px, pas de hover-only interactions.', 'Mobile first UX', NULL, 'best_practice', 0.93, 'elite_boost_v2', 'system'),
('SHARED UX: Feedback immediat — chaque action utilisateur doit avoir un retour visuel en < 200ms (skeleton, spinner, animation). Jamais de page blanche ou de bouton qui ne reagit pas.', 'Feedback immediat UX', NULL, 'best_practice', 0.92, 'elite_boost_v2', 'system'),
('SHARED UX: Simplicite > Fonctionnalites. Si un ecran a plus de 5 elements interactifs, il est trop complexe. Regrouper, cacher derriere des onglets, ou simplifier.', 'Simplicite UX regles', NULL, 'best_practice', 0.90, 'elite_boost_v2', 'system'),
('SHARED SATISFACTION: Le client doit sentir que KeiroAI travaille pour lui en permanence. Notifications de resultats (X posts publies, Y prospects contactes) = feeling de valeur continue meme sans connexion.', 'Notifications resultats satisfaction', NULL, 'insight', 0.92, 'elite_boost_v2', 'system'),
('SHARED SATISFACTION: Chaque interaction avec un agent doit laisser le client plus confiant qu avant. Si un agent ne peut pas aider, il doit rediriger vers le bon agent, jamais dire "je ne peux pas".', 'Confiance client interaction agent', NULL, 'best_practice', 0.93, 'elite_boost_v2', 'system')
ON CONFLICT DO NOTHING;
