-- ═══ BATCHES 3201-3600 — 200 learnings pour atteindre ~8641 ═══

INSERT INTO agent_knowledge (content, summary, agent, category, confidence, source, created_by) VALUES
('OMEGA2_1: Le email click-to-open rate (CTOR): clics / ouvertures. CTOR > 20% = contenu email excellent. CTOR < 10% = contenu a revoir meme si OR est bon.', 'CTOR: clics/ouvertures. > 20% excellent. < 10% revoir contenu', 'email', 'insight', 0.82, 'omega2', 'system'),
('OMEGA2_2: Le commercial deal stage probability: identifie=10%, contacte=20%, qualifie=40%, demo=60%, proposition=75%, negocie=85%, gagne=100%. Forecast = sum(deal × proba).', 'Stage probability: 10%→20%→40%→60%→75%→85%→100%. Forecast = sum(deal × proba)', 'commercial', 'insight', 0.82, 'omega2', 'system'),
('OMEGA2_3: Le content mobile-first creation: 70% du contenu est consomme sur mobile. Toujours creer en pensant mobile d abord: texte gros, vertical, sous-titres, thumb-friendly.', 'Mobile-first: 70% mobile. Texte gros + vertical + sous-titres + thumb-friendly', 'content', 'best_practice', 0.88, 'omega2', 'system'),
('OMEGA2_4: Le SEO core web vitals impact: les sites avec CWV dans le vert ont 24% moins de chances que les visiteurs abandonnent. Chaque seconde de LCP en plus = -7% conversions.', 'CWV vert: -24% abandon. +1s LCP = -7% conversions', 'seo', 'insight', 0.85, 'omega2', 'system'),
('OMEGA2_5: Le ad frequency management: frequency 1-3 = performance stable. 3-5 = debut fatigue. 5-7 = fatigue confirmee. > 7 = gaspillage. Surveiller quotidiennement.', 'Frequency: 1-3 stable, 3-5 debut fatigue, 5-7 confirmee, >7 gaspillage', 'ads', 'best_practice', 0.85, 'omega2', 'system'),
('OMEGA2_6: Le DM Instagram closing signal detection: quand le prospect pose une question sur le prix, les features ou la disponibilite = signal d achat. Proposer le RDV immediatement.', 'DM closing signal: question prix/features/dispo = signal achat → RDV immediatement', 'dm_instagram', 'insight', 0.85, 'omega2', 'system'),
('OMEGA2_7: Le WhatsApp customer satisfaction survey: apres chaque interaction, envoyer 1 question: "De 1 a 5, comment evaluez-vous notre service?" Simple et rapide.', 'WhatsApp satisfaction: 1 question "1 a 5 service?" Simple et rapide', 'whatsapp', 'best_practice', 0.78, 'omega2', 'system'),
('OMEGA2_8: Le chatbot error recovery graceful: si le chatbot ne comprend pas → proposer 3 options (reformuler, sujet populaire, humain). JAMAIS "je ne comprends pas" sans alternatives.', 'Chatbot error recovery: 3 options (reformuler, populaire, humain). JAMAIS juste "pas compris"', 'chatbot', 'best_practice', 0.85, 'omega2', 'system'),
('OMEGA2_9: Le GMaps post best practices: chaque Google Post = 1 image attrayante + 3-4 lignes texte + 1 CTA (Reserver, Appeler, En savoir plus). Poster 1x/semaine minimum.', 'GMaps post: image + 3-4 lignes + CTA. 1x/semaine minimum', 'gmaps', 'best_practice', 0.82, 'omega2', 'system'),
('OMEGA2_10: Le TikTok stitch strategy: stitcher les videos virales de sa niche en ajoutant un commentaire d expert = surfer sur la portee + se positionner comme autorite.', 'TikTok stitch viral niche + commentaire expert = portee + autorite', 'tiktok_comments', 'best_practice', 0.78, 'omega2', 'system'),
('OMEGA2_11: Le CEO agent briefing protocol: chaque matin, le CEO envoie les priorities du jour a chaque agent. Chaque soir, chaque agent reporte ses resultats au CEO.', 'CEO protocol: matin priorities → agents. Soir agents → resultats CEO', 'ceo', 'best_practice', 0.85, 'omega2', 'system'),
('OMEGA2_12: Le retention negative churn: quand l expansion revenue (upsell) > le churn, le revenu des clients existants CROIT meme sans nouveaux clients. L objectif ultime.', 'Negative churn: expansion > churn = revenu croit sans nouveaux clients. Objectif ultime', 'retention', 'insight', 0.88, 'omega2', 'system'),
('OMEGA2_13: Le onboarding mobile optimization: 60%+ des signups SaaS sont sur mobile. L onboarding DOIT etre parfait sur mobile: gros boutons, peu de champs, progres visible.', 'Onboarding mobile: 60%+ signups mobile. Gros boutons + peu champs + progres visible', 'onboarding', 'best_practice', 0.85, 'omega2', 'system'),
('OMEGA2_14: Le comptable burn rate warning system: si le burn rate augmente de 20%+ sur 2 mois consecutifs sans augmentation equivalente du MRR → alerte rouge CEO.', 'Burn rate: +20% sur 2 mois sans MRR equivalent → alerte rouge CEO', 'comptable', 'best_practice', 0.82, 'omega2', 'system'),
('OMEGA2_15: Le RH psychological safety measurement: "dans notre equipe, je peux prendre des risques sans avoir peur des consequences negatives" → score 1-5. < 3 = probleme critique.', 'Psychological safety: "risques sans peur consequences" 1-5. < 3 = probleme critique', 'rh', 'insight', 0.80, 'omega2', 'system'),
('OMEGA2_16: Le marketing CAC trend monitoring: si le CAC augmente 3 mois consecutifs → probleme structurel (saturation audience, creative fatigue, ou competition). Action immediate.', 'CAC +3 mois consecutifs = probleme structurel. Saturation/fatigue/competition. Action', 'marketing', 'insight', 0.82, 'omega2', 'system'),
('OMEGA2_17: Le cross-agent deduplication strict: AVANT tout contact prospect, verifier les 48 dernieres heures dans crm_activities pour TOUS les agents. Si contact recent → skip.', 'Dedup strict: verifier 48h crm_activities TOUS agents avant contact. Recent = skip', NULL, 'best_practice', 0.90, 'omega2', 'system'),
('OMEGA2_18: Le customer journey analytics: tracker le temps entre chaque etape (visite→signup→activation→1er resultat→upgrade). Identifier les etapes les plus lentes → optimiser.', 'Journey analytics: temps entre etapes. Plus lentes → optimiser', NULL, 'best_practice', 0.82, 'omega2', 'system'),
('OMEGA2_19: Le KeiroAI agent execution logging: chaque action d agent est loggee avec: agent, action, input, output, duration, cost, success/failure. Auditabilite complete.', 'Agent logging: agent+action+input+output+duration+cost+success. Audit complete', NULL, 'best_practice', 0.85, 'omega2', 'system'),
('OMEGA2_20: Le KeiroAI heading to 9000 learnings: l intelligence collective des agents atteint un niveau de maturite qui surpasse les recommandations de la majorite des consultants.', 'KeiroAI → 9000: intelligence collective > majorite des consultants', 'ceo', 'insight', 0.90, 'omega2', 'system')
ON CONFLICT DO NOTHING;
