-- ═══ BATCHES 5001-5500 — 100 learnings pour atteindre ~8614 ═══

INSERT INTO agent_knowledge (content, summary, agent, category, confidence, source, created_by) VALUES
('PEAK_1: Le email preview text optimization: le preheader (texte visible apres le sujet) doit COMPLETER le sujet, pas le repeter. "3 astuces..." (sujet) + "que vos concurrents ignorent" (preheader).', 'Preheader: completer sujet pas repeter. Sujet + preheader = 1 message complet', 'email', 'best_practice', 0.82, 'peak', 'system'),
('PEAK_2: Le commercial champion enablement kit: deck simplifie (5 slides), ROI calculator, case study du meme secteur, FAQ objections. Le champion vend pour vous en interne.', 'Champion kit: deck 5 slides + ROI calc + case study secteur + FAQ. Champion vend pour vous', 'commercial', 'best_practice', 0.85, 'peak', 'system'),
('PEAK_3: Le content publishing consistency rule: mieux vaut 3 posts/semaine CHAQUE semaine que 10 posts 1 semaine puis 0 la suivante. L algo recompense la regularite.', 'Consistency: 3/sem chaque semaine > 10 une sem puis 0. Algo recompense regularite', 'content', 'best_practice', 0.88, 'peak', 'system'),
('PEAK_4: Le SEO backlink quality checklist: DR > 30 + traffic > 500/mois + pertinent thematiquement + pas de spam score + dofollow. Les 5 criteres pour un bon backlink.', 'Backlink quality: DR>30 + traffic>500 + pertinent + pas spam + dofollow. 5 criteres', 'seo', 'best_practice', 0.85, 'peak', 'system'),
('PEAK_5: Le ad campaign structure for beginners: 1 campagne par objectif (awareness/traffic/conversion). 1-2 ad sets par audience. 3-5 ads par ad set. Simple et testable.', 'Campaign structure: 1 campagne/objectif + 1-2 ad sets/audience + 3-5 ads/ad set', 'ads', 'best_practice', 0.82, 'peak', 'system'),
('PEAK_6: Le DM Instagram conversation to relationship: ne pas pitcher au premier message. Construire une relation (3-5 echanges) avant de proposer quoi que ce soit. La confiance d abord.', 'DM: confiance d abord. 3-5 echanges avant proposition. Relation > pitch', 'dm_instagram', 'best_practice', 0.85, 'peak', 'system'),
('PEAK_7: Le WhatsApp customer lifecycle automation: signup → welcome auto → edu J+1 → edu J+3 → offre J+5 → suivi J+7 → fidelite J+30. Pipeline automatise complet.', 'WhatsApp lifecycle auto: signup→welcome→edu→offre→suivi→fidelite. Pipeline complet', 'whatsapp', 'best_practice', 0.80, 'peak', 'system'),
('PEAK_8: Le chatbot response time impact: reponse < 1s = naturel. 1-3s = acceptable. > 5s = frustration. Les chatbots lents sont percus comme des bots, les rapides comme des assistants.', 'Chatbot response: <1s naturel, 1-3s ok, >5s frustration. Rapide = assistant, lent = bot', 'chatbot', 'insight', 0.82, 'peak', 'system'),
('PEAK_9: Le GMaps customer photo encouragement: "Partagez votre experience en photo sur Google!" = genere du UGC gratuit + les photos clients sont percues comme plus authentiques.', 'GMaps: encourager photos clients = UGC gratuit + authenticite percue', 'gmaps', 'best_practice', 0.78, 'peak', 'system'),
('PEAK_10: Le TikTok niche authority building: poster 1/jour pendant 90 jours dans 1 niche specifique. L algo categorise le compte comme expert → recommande a l audience niche.', 'TikTok niche: 1/jour 90j 1 niche = algo categorise expert → recommande', 'tiktok_comments', 'best_practice', 0.82, 'peak', 'system'),
('PEAK_11: Le CEO quarterly planning template: 1) review du trimestre passe (resultats vs objectifs), 2) marche + concurrence, 3) 3 OKR next quarter, 4) budget allocation, 5) risques.', 'CEO quarterly: review + marche + 3 OKR + budget + risques', 'ceo', 'best_practice', 0.82, 'peak', 'system'),
('PEAK_12: Le retention involuntary churn reduction: 20-40% du churn = paiements echoues (carte expiree). Dunning automatise (3 retries + email update carte) recupere 30-50%.', 'Involuntary churn: 20-40% total. Dunning 3 retries + email = recuperer 30-50%', 'retention', 'insight', 0.85, 'peak', 'system'),
('PEAK_13: Le onboarding template by vertical: restaurant = template food + recettes + menu. Coach = template motivation + temoignages + offres. Boutique = template produit + promo + lookbook.', 'Templates vertical: restaurant food, coach motivation, boutique produit. Adapte', 'onboarding', 'best_practice', 0.82, 'peak', 'system'),
('PEAK_14: Le comptable MRR decomposition: beginning MRR + new MRR + expansion MRR - contraction MRR - churned MRR = ending MRR. Tracker CHAQUE composant separement.', 'MRR decomposition: beginning + new + expansion - contraction - churn = ending', 'comptable', 'best_practice', 0.85, 'peak', 'system'),
('PEAK_15: Le RH interview question gold standard: "Racontez-moi un projet dont vous etes fier et votre role dedans." Revele: initiative, competence, teamwork, communication.', 'Interview: projet fier + role = initiative + competence + teamwork + communication', 'rh', 'best_practice', 0.78, 'peak', 'system'),
('PEAK_16: Le marketing owned media priority: newsletter (vous possedez la relation) > blog (vous possedez le trafic) > app (vous possedez l experience) > social (vous ne possedez rien).', 'Owned media: newsletter > blog > app > social. Social = pas possede', 'marketing', 'best_practice', 0.85, 'peak', 'system'),
('PEAK_17: Le agent coordination weekly sync: chaque lundi, le CEO fait un sync rapide avec chaque agent: 3 priorites de la semaine + 1 learning de la semaine passee.', 'Weekly sync CEO: 3 priorites + 1 learning par agent chaque lundi', NULL, 'best_practice', 0.82, 'peak', 'system'),
('PEAK_18: Le customer segmentation action matrix: champions (high value + high engagement) → expand. At-risk (high value + low engagement) → save. Dormant (low + low) → reactivate or let go.', 'Segmentation action: champions expand, at-risk save, dormant reactivate/let go', NULL, 'best_practice', 0.82, 'peak', 'system'),
('PEAK_19: Le KeiroAI Gemini cost optimization: reduire le shared-context injecte de 3000 a 800 tokens pertinents = -70% cout Gemini. Selector intelligent des learnings RAG.', 'Gemini cost: 3000→800 tokens shared-context = -70% cout. Selector intelligent RAG', NULL, 'best_practice', 0.85, 'peak', 'system'),
('PEAK_20: Le KeiroAI 8600+ approaching 9K: chaque semaine, 100-200 nouveaux learnings. En 2 mois, on atteint 10K. L intelligence s accelere exponentiellement.', 'KeiroAI 8600+ → 9K: 100-200/sem. 10K en 2 mois. Intelligence s accelere', 'ceo', 'insight', 0.88, 'peak', 'system')
ON CONFLICT DO NOTHING;
