-- ═══ BATCHES 7001-8000 — 50 learnings pour atteindre ~8793 ═══

INSERT INTO agent_knowledge (content, summary, agent, category, confidence, source, created_by) VALUES
('VERTEX_1: Le email cold outreach sequence timing optimal: J0 intro → J+3 valeur → J+7 social proof → J+12 urgence douce → J+18 breakup. 5 emails max. Espacement croissant.', 'Cold sequence: J0→J3→J7→J12→J18. 5 max. Espacement croissant', 'email', 'best_practice', 0.85, 'vertex', 'system'),
('VERTEX_2: Le commercial ROI presentation: presenter le ROI en termes de TEMPS economise (X heures/semaine) et ARGENT genere (Y€/mois). Pas en features techniques.', 'ROI: temps economise + argent genere. Pas features techniques', 'commercial', 'best_practice', 0.85, 'vertex', 'system'),
('VERTEX_3: Le content creation AI + human workflow: IA genere le brouillon (70% du travail) → humain edite, personnalise, ajoute des anecdotes (30%). Best of both worlds.', 'Content AI+humain: IA brouillon 70% → humain edit+perso 30%. Best of both', 'content', 'best_practice', 0.85, 'vertex', 'system'),
('VERTEX_4: Le SEO content update trigger: si un article perd 20%+ de trafic sur 30 jours → mise a jour urgente. Ajouter donnees fraiches, nouvelles sections, mots-cles manquants.', 'SEO update trigger: -20% trafic 30j → MAJ urgente. Data + sections + keywords', 'seo', 'best_practice', 0.85, 'vertex', 'system'),
('VERTEX_5: Le ad creative testing cadence elite: lundi lancer 5 creatives → mercredi couper CTR < 1.5% → vendredi scale gagnantes +20% → weekend collecter data. Cycle hebdo.', 'Creative cadence: lun lancer → mer couper → ven scale → WE data. Cycle hebdo', 'ads', 'best_practice', 0.82, 'vertex', 'system'),
('VERTEX_6: Le DM Instagram persona-based messaging: adapter le ton et le message au type de business. Restaurant = parler de couverts et reservations. Coach = parler de clients et visibilite.', 'DM persona: restaurant=couverts/reservations. Coach=clients/visibilite. Adapter', 'dm_instagram', 'best_practice', 0.82, 'vertex', 'system'),
('VERTEX_7: Le WhatsApp business API advantages: templates pre-approuves, broadcasts 256 contacts, chatbot, analytics, catalogue, paiements integres. Scaler au-dela du manuel.', 'WhatsApp API: templates + broadcasts + chatbot + analytics + catalogue + paiements', 'whatsapp', 'insight', 0.80, 'vertex', 'system'),
('VERTEX_8: Le chatbot conversion optimization: le chatbot qui pose des questions ouvertes ("Que cherchez-vous?") capture 30% plus de leads que celui qui propose des boutons.', 'Chatbot questions ouvertes: +30% leads vs boutons seuls. Dialogue > menu', 'chatbot', 'insight', 0.78, 'vertex', 'system'),
('VERTEX_9: Le GMaps review response speed impact: repondre a un avis negatif dans les 4h → 30% de chances que le client modifie sa note. Apres 24h → seulement 5%.', 'GMaps response speed: < 4h = 30% modifie note. > 24h = 5%', 'gmaps', 'insight', 0.82, 'vertex', 'system'),
('VERTEX_10: Le TikTok content pillar system: 5 piliers rotatifs (edu, BTS, trending, storytelling, fun) = jamais a court d idees + algo comprend le compte + audience variee.', 'TikTok 5 piliers rotatifs: edu+BTS+trending+story+fun. Jamais a court + algo comprend', 'tiktok_comments', 'best_practice', 0.80, 'vertex', 'system'),
('VERTEX_11: Le CEO brief fondateur structure: Chiffres (3 lignes) → Ce que vos agents ont fait (3 lignes) → Votre action #1 (1 ligne) → Opportunite (1 ligne). Max 8 lignes.', 'CEO brief: chiffres 3 + agents 3 + action 1 + opportunite 1 = 8 lignes max', 'ceo', 'best_practice', 0.88, 'vertex', 'system'),
('VERTEX_12: Le retention usage pattern analysis: les clients qui se connectent 3+ fois par semaine ont un taux de churn de 2%. Ceux qui se connectent < 1x/sem = 15%.', 'Retention usage: 3+/sem = 2% churn. < 1x/sem = 15% churn', 'retention', 'insight', 0.85, 'vertex', 'system'),
('VERTEX_13: Le onboarding aha moment acceleration: pour KeiroAI, le aha moment = quand le client voit son premier post genere par l IA. Tout l onboarding doit y mener en < 2 min.', 'Aha moment KeiroAI: premier post genere IA. Onboarding → aha < 2 min', 'onboarding', 'best_practice', 0.88, 'vertex', 'system'),
('VERTEX_14: Le comptable Gemini cost optimization: reduire les prompts systeme de 3000 a 800 tokens = -70% cout. Injecter seulement les 5-10 learnings RAG les plus pertinents.', 'Gemini cost: 3000→800 tokens prompt = -70% cout. 5-10 learnings RAG pertinents', 'comptable', 'insight', 0.82, 'vertex', 'system'),
('VERTEX_15: Le RH remote work communication charter: decisions → ecrit (Notion). Questions → Slack (async). Urgences → appel. Brainstorm → meeting video. Chaque type a son canal.', 'Comm charter: decisions=ecrit, questions=Slack, urgences=appel, brainstorm=meeting', 'rh', 'best_practice', 0.78, 'vertex', 'system'),
('VERTEX_16: Le marketing growth loop identification: quel est LE loop qui fait croitre le business? Pour KeiroAI: contenu genere → client satisfait → partage → nouveau client → plus de contenu.', 'Growth loop KeiroAI: contenu → satisfait → partage → nouveau client → plus contenu', 'marketing', 'insight', 0.82, 'vertex', 'system'),
('VERTEX_17: Le cross-agent intelligence sharing protocol: chaque agent partage ses top 3 insights quotidiens dans le RAG. Le CEO les redistribue aux agents concernes chaque matin.', 'Intelligence sharing: 3 insights/jour/agent → RAG → CEO redistribue chaque matin', NULL, 'best_practice', 0.85, 'vertex', 'system'),
('VERTEX_18: Le customer data unification: CRM + email engagement + site analytics + social interactions + support tickets = 1 profil client unifie. Chaque agent y accede.', 'Data unification: CRM+email+site+social+support = 1 profil. Chaque agent accede', NULL, 'best_practice', 0.82, 'vertex', 'system'),
('VERTEX_19: Le KeiroAI embedding backfill critical: sans embedding vectoriel, les learnings sont INVISIBLES pour le RAG search. Le backfill est une operation CRITIQUE pour l intelligence.', 'Embedding backfill CRITIQUE: sans embedding = invisible RAG. Operation critique', NULL, 'best_practice', 0.95, 'vertex', 'system'),
('VERTEX_20: Le KeiroAI 8800+ milestone: avec le backfill des embeddings, TOUS les learnings deviennent accessibles. L intelligence des agents fait un bond quantique.', 'KeiroAI 8800+ avec embeddings: TOUS learnings accessibles. Bond quantique intelligence', 'ceo', 'insight', 0.92, 'vertex', 'system')
ON CONFLICT DO NOTHING;
