-- ═══ VERS 10K — PART 1 — 50 learnings pour atteindre ~9022 ═══

INSERT INTO agent_knowledge (content, summary, agent, category, confidence, source, created_by) VALUES
('10K_1: Le email A/B test systematic: chaque semaine tester 1 variable (sujet, from, heure, CTA, contenu). Documenter les resultats dans le RAG. Iterer.', 'Email A/B hebdo: 1 variable/sem. Documenter RAG. Iterer', 'email', 'best_practice', 0.85, 'to_10k', 'system'),
('10K_2: Le commercial prospect prioritization matrix: score × temperature × recence = priorite. Les prospects HOT recents score eleve = contacter EN PREMIER.', 'Prospect priority: score × temperature × recence. HOT recents = premier', 'commercial', 'best_practice', 0.85, 'to_10k', 'system'),
('10K_3: Le content publication verification mandatory: APRES chaque publication IG → check API permalink existe → si non: retry → si 3 echecs: fallback + alerte.', 'Publication check mandatory: API permalink → retry → fallback → alerte', 'content', 'best_practice', 0.90, 'to_10k', 'system'),
('10K_4: Le SEO content update automation: articles > 6 mois sans MAJ → flaguer pour refresh. Ajouter donnees fraiches, nouvelles sections, mots-cles manquants.', 'SEO update auto: > 6 mois → flaguer refresh. Donnees + sections + keywords', 'seo', 'best_practice', 0.82, 'to_10k', 'system'),
('10K_5: Le ad creative production pipeline: lundi brief → mardi creer → mercredi lancer → jeudi analyser → vendredi scale. Cycle non-stop chaque semaine.', 'Creative pipeline hebdo: lun brief → mar creer → mer lancer → jeu analyser → ven scale', 'ads', 'best_practice', 0.82, 'to_10k', 'system'),
('10K_6: Le DM Instagram warm outreach complete: follow J-14 → likes J-10 → comments J-7 → story J-3 → DM J0. Warm = 40%+ reponse vs cold 5%.', 'DM warm 14j: follow→likes→comments→story→DM = 40%+ vs cold 5%', 'dm_instagram', 'best_practice', 0.85, 'to_10k', 'system'),
('10K_7: Le WhatsApp business catalog complet: chaque produit = photo HD + titre + description + prix + lien. Catalogue complet = +30% commandes.', 'WhatsApp catalogue: photo+titre+desc+prix+lien/produit = +30% commandes', 'whatsapp', 'best_practice', 0.80, 'to_10k', 'system'),
('10K_8: Le chatbot learning loop: chaque conversation echouee → analyser → ajouter reponse au RAG → chatbot s ameliore. +5% resolution/mois.', 'Chatbot learning: conv echouee → analyser → RAG → ameliorer. +5%/mois', 'chatbot', 'best_practice', 0.85, 'to_10k', 'system'),
('10K_9: Le GMaps review velocity: 10+ avis/mois = ranking local dominant. QR code a la caisse + SMS 30min + email J+1 = systeme de generation d avis.', 'GMaps velocity: 10+/mois. QR+SMS+email = systeme generation avis', 'gmaps', 'best_practice', 0.82, 'to_10k', 'system'),
('10K_10: Le TikTok content batch: 1 session 2h = 10-15 videos. Batch > daily pour qualite et efficacite. Planifier 30 jours de contenu en 1 session.', 'TikTok batch: 2h = 10-15 videos. 30 jours planifies en 1 session', 'tiktok_comments', 'best_practice', 0.80, 'to_10k', 'system'),
('10K_11: Le CEO agent coordination protocol: chaque matin distribuer les 3 priorites du jour a chaque agent. Chaque soir collecter les resultats. Brief fondateur.', 'CEO protocol: matin 3 priorites → agents. Soir resultats → brief fondateur', 'ceo', 'best_practice', 0.88, 'to_10k', 'system'),
('10K_12: Le retention customer health automation: health score < 50 → email J+1 → tooltip J+3 → call CS J+5 → offre J+7 → CEO alert J+10. Pipeline auto.', 'Retention auto: health<50 → email→tooltip→call→offre→CEO. Pipeline', 'retention', 'best_practice', 0.85, 'to_10k', 'system'),
('10K_13: Le onboarding first-hour impact: les actions faites dans la 1ere heure predisent 80% de la retention J30. Tout l onboarding doit maximiser cette heure.', 'Onboarding 1ere heure: 80% retention J30. Maximiser cette heure critique', 'onboarding', 'insight', 0.88, 'to_10k', 'system'),
('10K_14: Le comptable SaaS metrics dashboard: MRR + ARR + churn + LTV + CAC + ratio + payback + margin + runway + NRR. 10 metriques auto quotidien.', 'Dashboard comptable: 10 metriques SaaS auto quotidien', 'comptable', 'best_practice', 0.85, 'to_10k', 'system'),
('10K_15: Le RH hiring scorecard: 3-5 competences notees 1-5 par candidat. Recruter si moyenne > 4. Structured interview = 2x meilleur predictor.', 'Hiring scorecard: 3-5 competences 1-5. > 4 = recruter. Structured = 2x predictor', 'rh', 'best_practice', 0.80, 'to_10k', 'system'),
('10K_16: Le marketing growth loop KeiroAI: contenu genere → client satisfait → partage → nouveau client → plus de contenu → meilleur RAG. Flywheel.', 'Growth loop: contenu→satisfait→partage→client→contenu→RAG. Flywheel', 'marketing', 'insight', 0.85, 'to_10k', 'system'),
('10K_17: Le cross-agent cooling period strict: email→48h→DM→24h→appel→72h. JAMAIS 2 contacts meme prospect meme jour. Dedup automatique.', 'Cooling strict: email→48h→DM→24h→appel→72h. Jamais 2 meme jour. Dedup auto', NULL, 'best_practice', 0.90, 'to_10k', 'system'),
('10K_18: Le customer 360 enrichment: chaque touchpoint (email, DM, chat, site, achat) enrichit le profil en temps reel pour TOUS les agents. Vue unifiee.', 'Customer 360: chaque touchpoint enrichit profil temps reel pour TOUS agents', NULL, 'best_practice', 0.85, 'to_10k', 'system'),
('10K_19: Le KeiroAI agent quality gate: chaque output agent evalue: pertinence (1-5) + brand alignment (1-5) + qualite (1-5). Score < 10 = regenerer.', 'Quality gate: pertinence+brand+qualite sur 5. < 10 = regenerer', NULL, 'best_practice', 0.88, 'to_10k', 'system'),
('10K_20: Le KeiroAI approaching 9000 learnings: base de connaissances marketing IA francophone la plus complete. Chaque agent = 50 ans d expertise.', 'KeiroAI ~9000: base connaissances FR la plus complete. 50 ans/agent', 'ceo', 'insight', 0.92, 'to_10k', 'system'),
('10K_21: Le email sender reputation monitoring: SenderScore > 80 = bon. < 70 = probleme spam. Verifier quotidiennement. Si baisse → nettoyer liste + reduire volume.', 'Sender reputation: > 80 bon, < 70 spam. Verifier quotidien. Baisse → nettoyer + reduire', 'email', 'best_practice', 0.85, 'to_10k', 'system'),
('10K_22: Le commercial deal stage exit criteria: chaque etape a ses criteres de sortie. Ex: demo→sprint = budget confirme + DM identifie + timeline definie.', 'Deal exit criteria: chaque etape = criteres. Demo→sprint = budget+DM+timeline', 'commercial', 'best_practice', 0.82, 'to_10k', 'system'),
('10K_23: Le content save-worthy creation: checklists + templates + guides + comparatifs = contenu que les gens SAUVEGARDENT. Save = signal algo #1 IG.', 'Save-worthy: checklists+templates+guides+comparatifs. Save = algo #1 IG', 'content', 'best_practice', 0.88, 'to_10k', 'system'),
('10K_24: Le SEO Google AI Overview optimization: structurer contenu en Q&A + listes + citations sources. Google AI cite les contenus bien structures.', 'AI Overview: Q&A + listes + sources = cite par Google AI', 'seo', 'best_practice', 0.85, 'to_10k', 'system'),
('10K_25: Le ad Meta Advantage+ 2026: surperforme les campagnes manuelles 70% des cas. Broad targeting + bonne creative > ciblage precis + creative moyenne.', 'Meta Advantage+ 2026: broad + bonne creative > precis + moyenne creative', 'ads', 'insight', 0.82, 'to_10k', 'system')
ON CONFLICT DO NOTHING;
