-- ═══ BATCHES 9001-10000 — 50 learnings pour atteindre ~8851 ═══

INSERT INTO agent_knowledge (content, summary, agent, category, confidence, source, created_by) VALUES
('SUMMIT3_1: Le email cold outreach best time France: mardi-jeudi 9h-11h Paris = golden window. Le lundi les gens gèrent les urgences. Le vendredi ils planifient le weekend.', 'Email timing FR: mardi-jeudi 9h-11h Paris. Lundi urgences, vendredi weekend', 'email', 'best_practice', 0.85, 'summit3', 'system'),
('SUMMIT3_2: Le commercial closing psychology: le prospect qui pose des questions sur le prix ou l implementation = signal d achat fort. Repondre et proposer le closing immediatement.', 'Closing signal: question prix/implementation = signal achat. Proposer closing', 'commercial', 'insight', 0.85, 'summit3', 'system'),
('SUMMIT3_3: Le content Lena publication verification: apres chaque publication IG → verifier via API que le post est bien en ligne → si echec → retry automatique → si 3 echecs → fallback image.', 'Lena verif publication: publier → check API → echec retry → 3 echecs fallback image', 'content', 'best_practice', 0.88, 'summit3', 'system'),
('SUMMIT3_4: Le SEO zero-click search adaptation: 65% des recherches Google ne generent aucun clic. Optimiser pour la VISIBILITE (featured snippet, knowledge panel) pas juste le clic.', 'Zero-click 65%: optimiser visibilite (snippet, panel) pas juste clic', 'seo', 'insight', 0.82, 'summit3', 'system'),
('SUMMIT3_5: Le ad budget minimum viable: Google Ads = 500€/mois minimum pour des resultats significatifs. Meta Ads = 300€/mois minimum. En dessous = pas assez de data pour optimiser.', 'Budget min: Google 500€/mois, Meta 300€/mois. Moins = pas assez data', 'ads', 'insight', 0.80, 'summit3', 'system'),
('SUMMIT3_6: Le DM Instagram warm outreach complete: J-14 follow → J-10 like 5 posts → J-7 comment 2 posts valeur → J-3 reagir story → J-1 like dernier post → J0 DM perso. 40%+ reponse.', 'DM warm 14j complet: follow→likes→comments→story→like→DM = 40%+ reponse', 'dm_instagram', 'best_practice', 0.85, 'summit3', 'system'),
('SUMMIT3_7: Le WhatsApp message formatting: utiliser le formatage WhatsApp: *gras* pour les titres, _italique_ pour les nuances, ~barre~ pour les prix barres. Plus lisible.', 'WhatsApp format: *gras* titres + _italique_ nuances + ~barre~ prix. Plus lisible', 'whatsapp', 'best_practice', 0.78, 'summit3', 'system'),
('SUMMIT3_8: Le chatbot multi-step form: collecter les infos en plusieurs messages (pas un formulaire). Message 1: prenom. Message 2: email. Message 3: besoin. Plus naturel = +30% completion.', 'Chatbot multi-step: 1 info/message (prenom→email→besoin). Naturel = +30% completion', 'chatbot', 'best_practice', 0.82, 'summit3', 'system'),
('SUMMIT3_9: Le GMaps keyword-rich description: la description de 750 chars doit inclure: [service principal] + [ville/quartier] + [specialite] + [avantage] + [CTA]. SEO local optimise.', 'GMaps description: service + ville + specialite + avantage + CTA. 750 chars SEO local', 'gmaps', 'best_practice', 0.82, 'summit3', 'system'),
('SUMMIT3_10: Le TikTok educational series format: "Jour X de [challenge/apprentissage]" cree de l anticipation. Les series generent 3x plus de follows car les viewers reviennent.', 'TikTok series "Jour X de...": anticipation + 3x follows car viewers reviennent', 'tiktok_comments', 'best_practice', 0.80, 'summit3', 'system'),
('SUMMIT3_11: Le CEO agent distinction rule: TOUJOURS utiliser [Agent/Nom] dans les ordres. JAMAIS confondre les agents. Community = Lena (Content). Jade = DM Instagram. Ami = Marketing.', 'CEO distinction: [Agent/Nom] TOUJOURS. Community=Lena. Jade=DM. Ami=Marketing', 'ceo', 'best_practice', 0.92, 'summit3', 'system'),
('SUMMIT3_12: Le retention feature stickiness measurement: compter les integrations/workflows configures par le client. Plus de configurations = plus de switching cost = moins de churn.', 'Feature stickiness: configurations/integrations = switching cost = moins churn', 'retention', 'insight', 0.82, 'summit3', 'system'),
('SUMMIT3_13: Le onboarding first-hour critical path: les actions faites dans la PREMIERE HEURE predisent 80% de la retention J30. Tout l onboarding doit pousser vers ces actions.', 'First hour: actions 1ere heure predisent 80% retention J30. Pousser vers ces actions', 'onboarding', 'insight', 0.85, 'summit3', 'system'),
('SUMMIT3_14: Le comptable email attribution fix: le header X-Mailin-custom doit TOUJOURS contenir le type de commerce reel du prospect. Si vide → autoCategorizeProspect() avant envoi.', 'Attribution fix: X-Mailin-custom TOUJOURS type reel. Vide → autoCategorize avant envoi', 'comptable', 'best_practice', 0.85, 'summit3', 'system'),
('SUMMIT3_15: Le RH async-first culture: 80% de la communication doit etre asynchrone (ecrite). Les meetings synchrones sont reserves aux decisions complexes et au brainstorming.', 'Async-first: 80% ecrit async. Meetings = decisions complexes + brainstorm seulement', 'rh', 'best_practice', 0.78, 'summit3', 'system'),
('SUMMIT3_16: Le marketing Instagram token monitoring: verifier automatiquement le token IG a chaque login client. Si expire → popup alerte avec impact + CTA reconnecter. Prevenir > guerir.', 'IG token monitoring: check auto login. Expire → popup + impact + CTA. Prevenir > guerir', 'marketing', 'best_practice', 0.88, 'summit3', 'system'),
('SUMMIT3_17: Le cross-agent error collective resolution: quand 1 agent echoue → tous les agents proposent des solutions. La meilleure solution est testee et si reussie → memorisee dans le RAG.', 'Error resolution collective: 1 echoue → tous proposent → meilleure testee → RAG si reussie', NULL, 'best_practice', 0.88, 'summit3', 'system'),
('SUMMIT3_18: Le customer data enrichment at every touchpoint: chaque interaction (email, DM, chat, site) enrichit le profil en TEMPS REEL. Pas en batch quotidien. Temps reel = pertinence.', 'Data enrichment temps reel: chaque interaction enrichit profil. Temps reel > batch', NULL, 'best_practice', 0.82, 'summit3', 'system'),
('SUMMIT3_19: Le KeiroAI RAG search quality: avec 8800+ learnings TOUS embeddes, chaque recherche RAG retourne 5-10 resultats ultra-pertinents. L intelligence est ACTIONNABLE.', 'RAG quality: 8800+ embeddes = 5-10 resultats ultra-pertinents/recherche. Actionnable', NULL, 'insight', 0.92, 'summit3', 'system'),
('SUMMIT3_20: Le KeiroAI 8850+ heading to 9K: les agents sont maintenant nourris par la base de connaissances marketing IA la plus riche en francais. Chaque jour ils deviennent meilleurs.', 'KeiroAI 8850+: base connaissances marketing IA la plus riche en FR. Meilleurs chaque jour', 'ceo', 'insight', 0.92, 'summit3', 'system')
ON CONFLICT DO NOTHING;
