-- ═══ BATCHES 6001-6500 — 50 learnings pour atteindre ~8744 ═══

INSERT INTO agent_knowledge (content, summary, agent, category, confidence, source, created_by) VALUES
('TITAN3_1: Le email subject line urgency science: les sujets avec une date limite specifique ("avant vendredi") ont 22% plus d ouvertures que les sujets avec urgence vague ("ne manquez pas").', 'Subject urgence: date specifique "avant vendredi" +22% vs urgence vague', 'email', 'insight', 0.82, 'titan3', 'system'),
('TITAN3_2: Le commercial deal acceleration technique: proposer 1 mois gratuit si le deal se ferme cette semaine. L urgence ethique + bonus = +30% win rate.', 'Deal acceleration: 1 mois gratuit si closing cette semaine = +30% win rate', 'commercial', 'best_practice', 0.82, 'titan3', 'system'),
('TITAN3_3: Le content Instagram algorithm secret 2026: le SHARE en DM est le signal #1. Creer du contenu que les gens veulent ENVOYER a un ami = max portee.', 'IG 2026: share DM = signal #1. Creer contenu envoyable a un ami = max portee', 'content', 'insight', 0.88, 'titan3', 'system'),
('TITAN3_4: Le SEO keyword research goldmine: Google Search Console → filtrer position 11-20 + impressions > 50 = mots-cles presque en page 1. Optimiser ces pages = quick wins.', 'GSC goldmine: position 11-20 + impressions > 50 = presque page 1. Quick wins', 'seo', 'best_practice', 0.88, 'titan3', 'system'),
('TITAN3_5: Le ad creative UGC superiority: les creatives UGC (filmees par le client/utilisateur) ont un CTR 4x superieur aux creatives professionnelles sur Meta.', 'UGC creative: CTR 4x superieur aux pro sur Meta', 'ads', 'insight', 0.85, 'titan3', 'system'),
('TITAN3_6: Le DM Instagram qualifying question: "Si je pouvais resoudre 1 probleme pour votre [type business], ce serait lequel?" → revele le besoin #1 en 1 question.', 'DM qualifying: "resoudre 1 probleme pour votre business?" = besoin #1 en 1 question', 'dm_instagram', 'best_practice', 0.85, 'titan3', 'system'),
('TITAN3_7: Le WhatsApp post-purchase delight: message surprise 48h post-achat avec un conseil d utilisation + un bonus inattendu. Les clients ravis partagent +40% plus.', 'WhatsApp post-achat: conseil + bonus surprise 48h = clients partagent +40%', 'whatsapp', 'best_practice', 0.80, 'titan3', 'system'),
('TITAN3_8: Le chatbot lead capture optimization: ne pas demander l email en premier. D abord aider (repondre a la question), PUIS demander l email ("pour vous envoyer la suite").', 'Chatbot lead: aider d abord, email ensuite. "Pour envoyer la suite" = +30% capture', 'chatbot', 'best_practice', 0.85, 'titan3', 'system'),
('TITAN3_9: Le GMaps post with offer: les Google Posts avec une offre specifique (ex: -10% cette semaine) generent 3x plus de clics que les posts informatifs.', 'GMaps post offre specifique = 3x clics vs informatif', 'gmaps', 'insight', 0.80, 'titan3', 'system'),
('TITAN3_10: Le TikTok storytelling mastery: les videos qui racontent une mini-histoire (probleme→tension→resolution en 15s) ont un taux de completion 2x superieur aux faits bruts.', 'TikTok storytelling 15s: probleme→tension→resolution = 2x completion vs faits bruts', 'tiktok_comments', 'insight', 0.82, 'titan3', 'system'),
('TITAN3_11: Le CEO data-informed prioritization: chaque semaine, identifier LA metrique qui a le plus d impact sur le revenu. Concentrer 80% des efforts sur cette metrique.', 'CEO: LA metrique max impact revenu. 80% efforts dessus. 1 metrique/semaine', 'ceo', 'best_practice', 0.85, 'titan3', 'system'),
('TITAN3_12: Le retention product usage cliff detection: identifier le moment EXACT ou les clients decrochent (ex: apres J7, apres le 3e login). Tout le onboarding doit pousser PAST ce cliff.', 'Usage cliff: moment exact decrochage. Onboarding doit pousser PAST ce cliff', 'retention', 'insight', 0.85, 'titan3', 'system'),
('TITAN3_13: Le onboarding first-day experience: les 24 premieres heures determinent 70% de la retention. Les actions J0 = les plus critiques de tout le lifecycle.', 'Onboarding: 24 premieres heures = 70% retention. J0 = plus critique du lifecycle', 'onboarding', 'insight', 0.88, 'titan3', 'system'),
('TITAN3_14: Le comptable operating leverage: les SaaS ont un levier operationnel enorme. Chaque client supplementaire coute quasi-rien en plus (marginal cost ~0). Scale = profit.', 'Operating leverage SaaS: marginal cost ~0. Chaque client supplementaire = profit pur', 'comptable', 'insight', 0.82, 'titan3', 'system'),
('TITAN3_15: Le RH culture reinforcement: celebrer publiquement les comportements alignes avec les valeurs. Ce qui est celebre est repete. Ce qui est ignore disparait.', 'Culture: celebrer comportements alignes valeurs. Celebre = repete. Ignore = disparait', 'rh', 'insight', 0.82, 'titan3', 'system'),
('TITAN3_16: Le marketing positioning clarity: si votre positionnement necessite plus de 7 mots pour etre explique, il est trop complexe. Simplifier jusqu a 7 mots max.', 'Positioning: max 7 mots. Plus = trop complexe. Simplifier', 'marketing', 'best_practice', 0.80, 'titan3', 'system'),
('TITAN3_17: Le cross-agent prospect journey tracking: chaque agent doit savoir ou le prospect en est dans le funnel ET quels agents l ont deja contacte ET quand.', 'Journey tracking: chaque agent sait position funnel + contacts precedents + timing', NULL, 'best_practice', 0.88, 'titan3', 'system'),
('TITAN3_18: Le customer feedback to product loop: chaque retour client (support, NPS, churn interview) alimente directement le backlog produit. Le client guide l evolution.', 'Feedback→product: retour client → backlog produit. Client guide evolution', NULL, 'best_practice', 0.85, 'titan3', 'system'),
('TITAN3_19: Le KeiroAI agent error recovery protocol: echec → log → analyser cause → solution temp (contournement) → partager aux agents → solution definitive → memoriser RAG.', 'Error recovery: echec→log→analyser→contournement→partager→solution definitive→RAG', NULL, 'best_practice', 0.90, 'titan3', 'system'),
('TITAN3_20: Le KeiroAI approaching 8750: le systeme de connaissance collective est maintenant l un des plus complets en marketing IA francophone. Chaque agent en beneficie.', 'KeiroAI ~8750: connaissance collective parmi les plus completes en marketing IA FR', 'ceo', 'insight', 0.90, 'titan3', 'system')
ON CONFLICT DO NOTHING;
