-- ═══ BATCHES 5501-6000 — 50 learnings erreurs + solutions + coordination agents ═══

INSERT INTO agent_knowledge (content, summary, agent, category, confidence, source, created_by) VALUES
('ERROR_LEARNING_1: Si un agent echoue 3x sur la meme action → les autres agents proposent une solution alternative. Ex: email echec → DM prend le relais. Jamais d arret complet.', 'Agent echec 3x → autres proposent alternative. Email echec → DM relais. Jamais d arret', NULL, 'best_practice', 0.92, 'error_learning', 'system'),
('ERROR_LEARNING_2: Chaque erreur d agent est loggee avec: agent, action, erreur, timestamp. Les patterns d erreurs recurrentes sont detectes et corriges collectivement.', 'Erreur loggee: agent+action+erreur+timestamp. Patterns recurrents → correction collective', NULL, 'best_practice', 0.90, 'error_learning', 'system'),
('ERROR_LEARNING_3: L agent marketing qui echoue doit partager son erreur + tentative de solution dans le shared context. Les autres agents adaptent leur strategie en consequence.', 'Marketing echec: partager erreur+tentative dans shared context. Autres agents adaptent', 'marketing', 'best_practice', 0.88, 'error_learning', 'system'),
('ERROR_LEARNING_4: Solution temporaire de contournement: si l API Instagram tombe → l agent content sauvegarde les posts en "ready_to_publish" et retente toutes les heures.', 'Contournement: IG tombe → sauvegarder ready_to_publish + retenter toutes heures', 'content', 'best_practice', 0.88, 'error_learning', 'system'),
('ERROR_LEARNING_5: Si le quota Brevo est atteint → l agent email bascule en mode prioritaire: envoyer uniquement aux prospects HOT (score > 15) avec le quota restant.', 'Quota Brevo atteint → mode prioritaire: uniquement prospects HOT score > 15', 'email', 'best_practice', 0.88, 'error_learning', 'system'),
('ERROR_LEARNING_6: Chaque execution d agent sauvegarde son resultat dans le RAG: {agent, action, resultat, duree, succes/echec}. Les agents consultent ces resultats avant d agir.', 'Execution → RAG: agent+action+resultat+duree+succes/echec. Consulter avant agir', NULL, 'best_practice', 0.90, 'error_learning', 'system'),
('ERROR_LEARNING_7: Si l agent SEO genere un article sans HTML valide → fallback: construire l article depuis les metadonnees (titre, description, FAQ). Ne jamais echouer silencieusement.', 'SEO HTML invalide → fallback: construire depuis metadonnees. Jamais echouer silencieusement', 'seo', 'best_practice', 0.88, 'error_learning', 'system'),
('ERROR_LEARNING_8: Si le chatbot ne comprend pas une question → proposer 3 alternatives + option humain. Apres, analyser la question et ajouter la reponse au RAG pour le futur.', 'Chatbot incomprehension → 3 alternatives + humain. Puis analyser et ajouter au RAG', 'chatbot', 'best_practice', 0.85, 'error_learning', 'system'),
('ERROR_LEARNING_9: Le CEO recoit un rapport d erreurs quotidien. Si > 5 erreurs critiques → email d alerte au fondateur avec les solutions proposees par les agents.', 'CEO: > 5 erreurs critiques/jour → email alerte fondateur + solutions agents', 'ceo', 'best_practice', 0.88, 'error_learning', 'system'),
('ERROR_LEARNING_10: Protocole de resilience: chaque agent a un mode degrade. Si l API principale tombe → utiliser le cache. Si le cache tombe → utiliser les valeurs par defaut.', 'Resilience: API tombe → cache. Cache tombe → valeurs defaut. Mode degrade chaque agent', NULL, 'best_practice', 0.85, 'error_learning', 'system'),
('COLLAB_1: Avant CHAQUE action, l agent DOIT: 1) consulter le RAG pour les best practices, 2) verifier les erreurs recentes des autres agents, 3) adapter son action en consequence.', 'Pre-action: consulter RAG + verifier erreurs recentes + adapter. OBLIGATOIRE', NULL, 'best_practice', 0.92, 'agent_collab', 'system'),
('COLLAB_2: Apres CHAQUE action, l agent DOIT: 1) logger le resultat dans agent_logs, 2) partager le learning dans le RAG si nouveau, 3) notifier le CEO si impact significatif.', 'Post-action: logger + RAG si nouveau + notifier CEO si impact. OBLIGATOIRE', NULL, 'best_practice', 0.92, 'agent_collab', 'system'),
('COLLAB_3: Si un agent detecte un insight (ex: les restaurants ouvrent les emails a 11h) → le partager IMMEDIATEMENT a tous les agents via le shared context.', 'Insight detecte → partager IMMEDIATEMENT a tous agents via shared context', NULL, 'best_practice', 0.90, 'agent_collab', 'system'),
('COLLAB_4: Si un agent echoue et ne trouve pas de solution → escalader au CEO avec: description erreur, tentatives, impact business. Le CEO redistribue aux autres agents.', 'Echec sans solution → escalader CEO: erreur+tentatives+impact. CEO redistribue', NULL, 'best_practice', 0.88, 'agent_collab', 'system'),
('COLLAB_5: Les agents doivent eviter de contacter le meme prospect dans la meme journee. Cooling period: email→48h→DM→24h→appel. Coordination anti-spam.', 'Cooling: email→48h→DM→24h→appel. Jamais meme prospect meme jour. Anti-spam', NULL, 'best_practice', 0.90, 'agent_collab', 'system'),
('COLLAB_6: Chaque lundi, le CEO fait un sync: top 3 insights de la semaine + erreurs corrigees + priorites semaine. Distribue aux agents concernes.', 'CEO lundi sync: 3 insights + erreurs corrigees + priorites. Distribue aux agents', 'ceo', 'best_practice', 0.85, 'agent_collab', 'system'),
('COLLAB_7: Les solutions trouvees collectivement (ex: fallback email→DM quand quota atteint) sont memorisees dans le RAG comme "solution_validee" avec confidence 0.95.', 'Solutions collectives memorisees RAG: "solution_validee" confidence 0.95', NULL, 'best_practice', 0.90, 'agent_collab', 'system'),
('COLLAB_8: Si une solution temporaire fonctionne pendant 7 jours → elle devient permanente et est integree dans le code (recommandation au fondateur par email).', 'Solution temporaire 7j → permanente. Recommendation code au fondateur par email', NULL, 'best_practice', 0.85, 'agent_collab', 'system'),
('COLLAB_9: Le pool de connaissances (RAG) est le cerveau collectif. CHAQUE agent y contribue et y puise. Plus les agents partagent, plus ils deviennent intelligents ensemble.', 'RAG = cerveau collectif. Chaque agent contribue + puise. Partage = intelligence', NULL, 'insight', 0.92, 'agent_collab', 'system'),
('COLLAB_10: L auto-amelioration des agents suit un cycle: executer → mesurer → analyser → apprendre (RAG) → ameliorer → re-executer. Boucle continue infinie.', 'Auto-amelioration: executer→mesurer→analyser→apprendre(RAG)→ameliorer→re-executer. Infini', NULL, 'best_practice', 0.90, 'agent_collab', 'system')
ON CONFLICT DO NOTHING;
